/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackPage: typeof import('./src/components/backPage/index.vue')['default']
    Chartbox: typeof import('./src/components/chartbox/index.vue')['default']
    DexBreadcrumb: typeof import('./src/components/dexBreadcrumb/index.vue')['default']
    DexButton1: typeof import('./src/components/dexButton1/index.vue')['default']
    DexButton2: typeof import('./src/components/dexButton2/index.vue')['default']
    DexShowInfo: typeof import('./src/components/dexShowInfo/index.vue')['default']
    DexTable: typeof import('./src/components/dexTable/index.vue')['default']
    DexTabs: typeof import('./src/components/dexTabs/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footers: typeof import('./src/components/footers/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Index_en: typeof import('./src/components/crossImg/index_en.vue')['default']
    Index_zh: typeof import('./src/components/crossImg/index_zh.vue')['default']
    ListLoadMore: typeof import('./src/components/listLoadMore/index.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper1: typeof import('./src/components/swiper1/index.vue')['default']
    Swiper2: typeof import('./src/components/swiper2/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanLoading: typeof import('vant/es')['Loading']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
