export default {
  text: {
    t1: "Home",
    t2: "Join us",
    t3: "Google Store",
    t4: "Apple Store",
    t5: "Download App",
    t6: "Chrome Download",
    t7: "Local download",
    t8: "BDX currency price",
    t9: "Trading volume",
    t10: "Community User",
    t11: "Number of transactions",
    t12: "BDX total transaction volume",
    t13: "Growth List",
    t14: "Decline list",
    t15: "New Coin List",
    t16: "Transaction Volume List",
    t17: "name",
    t18: "Latest price",
    t19: "price",
    t20: "Today's increase",
    t21: "Increase or decrease",
    t22: "24H trading volume",
    t23: "Transaction",
    t24: "No data yet",
    t25: "View all",
    t26: "Safe, efficient, low cost",
    t27: "Customer service online",
    t28: "Business Cooperation",
    t29: "Company",
    t30: "About us",
    t31: "Help Center",
    t32: "Announcement",
    t33: "BDX Token",
    t34: "product",
    t35: "Buy coins",
    t36: "Web3 wallet",
    t37: "Service",
    t38: "Feedback",
    t39: "Application for currency listing",
    t40: "Friend invitation",
    t41: "Legal and Risk Disclosure",
    t42: "Compliance license",
    t43: "Anti-Money Laundering Policy",
    t44: "Privacy Policy",
    t45: "User Agreement",
    t46: "Legal Statement",
    t47: "Risk Warning",
    t48: "ST rule",
    t49: "plug-in wallet",
    t50: "Download wallet",
    t51: "Language",
    t52: "Log out",
    t53: "Connect wallet",
    t54: "Loading...",
    t55: "No more...",
    t56: "About BeingDex",
    t57: "Behind BeingDex are a group of early adopters of blockchain technology and believers in the future development of blockchain.",
    t58: "Since 2018, we established a cryptocurrency exchange and have been committed to providing secure, one-stop trading solutions to help users trade smarter.",
    t59: "Full-chain pending order matching decentralized trading platform",
    t60: "Global registered address",
    t61: "100,000+",
    t62: "30 million USDT",
    t63: "Daily trading volume",
    t64: "Our Story",
    t65: "This is a group of geeks who have a firm belief in blockchain and encrypted assets. In 2010, we purchased our first Bitcoin through the e-commerce OTC platform. At that time, we were nervous and uneasy. As the industry cycle changes, transaction methods and product forms continue to innovate and evolve, presenting a situation where Cex and Dex are developing simultaneously. But at the same time, we also realize that the existing Dex is limited by its model mechanism and cannot maximize asset efficiency. <br>At the same time, as the encryption industry has an increasingly broad and profound influence around the world, in addition to developed areas, more and more people from areas with weak financial infrastructure are beginning to join, but they have difficulty understanding complex financial products and Algorithmic mechanism has become a gap that prevents them from connecting to new worlds and new assets. <br>BeingDex is committed to crossing this gap and building full-chain application products and ecology through new smart contracts. <br>Being has connotations such as 'existence', 'essence' and 'biological life', which expresses our spirit of exploring the origin of things, our fundamental practice of product value, and our ultimate pursuit of user experience. We encourage ourselves and at the same time We welcome more people to open their minds and embrace crypto assets, and help them start their own crypto wealth journey through easy-to-use and friendly product services.",
    t66: "Vision",
    t67: "Create a freer, fairer and more transparent future wealth world through Web3",
    t68: "Mission",
    t69: "Create the ultimate trading platform that everyone can use and become the leading digital asset financial service provider in the industry",
    t70: "Our values",
    t71: "User first",
    t72: "Pay attention to the needs and attitudes of each user, communicate objectively and candidly, and release platform information in a timely manner.",
    t73: "Integrity and rigor",
    t74: "We adhere to the principle of 'don't do evil' and win the trust of the market and users through responsibility and responsibility.",
    t75: "Innovation and enterprising",
    t76: "Extreme products and services and building structural advantages are our eternal pursuit.",
    t77: "Begin with the end in mind",
    t78: "Do long-term things with long-term partners, grasp the process, create conditions, pay attention to feedback results, and continuously achieve milestone goals.",
    t79: "Our team",
    t80: "With over 150 employees from over 10 countries, the BeingDEX team has senior talent from every corner of the planet, giving us a truly global reach.",
    t81: "Our Services",
    t82: "BeingDEX",
    t83: "BeingDex is a new decentralized exchange based on multi-chain development. It adopts an on-chain order matching model and the cross-chain bridge supports public chains BSC, TRON, and OKX.",
    t84: "Being Wallet",
    t85: "Being Wallet adopts two major security mechanisms: self-custody of user assets and complete anonymity. Its underlying wallet technology supports multiple security protections such as local biometric encryption and security isolation, and supports multi-chain asset management to protect users' safe transactions.",
    t86: "Being NFT",
    t87: "Being NFT supports ETH, BSC, Mango, TRON, Polygon, Solana multi-chain one-click issuance of NFT, transactions and other activities are completed through the chain protocol without third-party intervention. The NFT organized by the DAO is stored in the wallet. On-chain casting, intelligent transactions, safe and convenient.",
    t88: "Start your crypto journey now!",
    t89: "Trade on a platform trusted by millions of users.",
    t90: "Upload successful",
    t91: "Upload failed",
    t92: "Please select the public chain you belong to",
    t93: "Please enter the project name",
    t94: "Please upload logo",
    t95: "Please enter the token abbreviation",
    t96: "Please enter the contract address",
    t97: "Please enter the issuance quantity",
    t98: "Please enter the official website link",
    t99: "Please enter your email address",
    t100: "Please enter your token information",
    t101: "Submission successful",
    t102: "BeingDex currency listing application",
    t103: "Thank you for your interest in BeingDex Exchange. Please fill out the application form and provide valid information. We will review your project based on the information you provide. Please submit this application and your project will be sent to the currency listing department for review. After you pass the preliminary review, we will arrange for a currency listing specialist to share the currency listing process and techniques with you and guide you through the currency listing process.",
    t104: "Indicates required",
    t105: "Public chain to which it belongs",
    t106: "Project name",
    t107: "Token abbreviation",
    t108: "Contract address",
    t109: "Issuance quantity",
    t110: "Official website link",
    t111: "Mailbox",
    t112: "Token information",
    t113: "Please enter your token information, no more than 120 characters",
    t114: "Submit",
    t115: "Submit after connecting to wallet",
    t116: "Clear form content",
    t117: "BDX leads the revolution in the crypto industry",
    t118: "Connect your assets, DeFi applications, and NFTs to help you unlock the Web3 world quickly",
    t119: "Get BDX with one click",
    t120: "BDX White Paper",
    t121: "Introduction to BDX",
    t122: "Hold BDX and enjoy endless benefits",
    t123: "New subscription",
    t124: "Preferential service",
    t125: "Deflation mechanism",
    t126: "New online",
    t127: "Planning",
    t128: "Get BDX",
    t129: "BDX release information",
    t130: "Safe, easy to use, and closely connected to cultures and ideologies around the world",
    t131: "Token name",
    t132: "Token symbol",
    t133: "Owning chain",
    t134: "Contract address",
    t135: "Issue price",
    t136: "Circulation supply",
    t137: "Total supply",
    t138: "Issue date",
    t139: "Replace BDX",
    t140: "For redemption of existing BDX tokens",
    t141: "Team Motivation",
    t142: "2% unlocked every 6 months, will be fully unlocked in 5 years (60 months)",
    t143: "Economic and ecological investment",
    t144: "Go to BeingDex ecosystem for fund investment",
    t145: "Brand Promotion",
    t146: "Maximum releases per year ",
    t147: "User input",
    t148: "Protection Fund",
    t149: "For compensation for potential accidents on the platform",
    t150: "Work with us to create a safe and reliable BDX ecosystem and promote the rapid development of Web3",
    t151: "Get BDX with one click",
    t152: "Recommended",
    t153: "Latest Blog",
    t154: "No data yet",
    t155: "DApp Application Store",
    t156: "Search",
    t157: "Select category",
    t158: "Important Disclaimer",
    t159: "All content provided on this website, hyperlinked websites, related applications, forums, blogs, social media accounts and other platforms (the 'Site') is for your general information obtained from third party sources only. We are not responsible for our content No guarantees of any kind are made, including but not limited to accuracy and currency. No part of the content provided by us constitutes financial advice, legal advice or any other form of advice and is designed to satisfy your specific reliance for any purpose. Any Any use of or reliance on our content is done at your own risk and discretion. You should conduct your own research, review, analysis and verification before relying on our content. Trading is a high-risk activity that can result in significant losses , so please consult your financial advisor before making any decisions. Nothing on our website is a solicitation or offer.",
    t160: "Please enter the suggestion details",
    t161: "Submission successful",
    t162: "Each of your suggestions",
    t163: "We will listen carefully and treat it seriously",
    t164: "Feedback",
    t165: "If you find any security flaws or vulnerabilities, please give us timely feedback",
    t166: "If you have any questions, please consult the Help Center for answers to frequently asked questions.",
    t167: "What do you think of our product experience?",
    t168: "Not a good experience!",
    t169: "To be improved!",
    t170: "Quite satisfactory!",
    t171: "Super awesome!",
    t172: "Submit suggestion",
    t173: "Welcome to share your product suggestions. BeingDex will take your feedback seriously. If you have urgent inquiries, please contact customer service.",
    t174: "Suggested category",
    t175: "Safety recommendations",
    t176: "Feature Suggestions",
    t177: "Design Suggestions",
    t178: "Operation Suggestions",
    t179: "Other suggestions",
    t180: "Suggestion details",
    t181: "Please enter your feedback, no more than 500 characters",
    t182: "Upload pictures (optional)",
    t183: "Please upload screenshots related to the problem. The image format is JPG or PNG, and the size must not exceed 2M",
    t184: "Contact information (optional)",
    t185: "Please enter contact information",
    t186: "Confirm submission",
    t187: "Submit after connecting to wallet",
    t188: "Save draft",
    t189: "How does it work?",
    t190: "Submit suggestion",
    t191: "Team review",
    t192: "Distribute rewards",
    t193: "BeingDex serves users around the world, and we regard the safe and stable development of the platform as our top priority. We look forward to your valuable suggestions. Let's improve product quality and create a better future together.",
    t194: "A protocol that Web3 users can trust<br>enables Defi users to easily complete transactions",
    t195: "Asset self-custody, wallet point-to-point matching transactions",
    t196: "Safety with zero accidents and pure smart contract execution",
    t197: "Original decentralized K-line chart, native advantages",
    t198: "Popular Cryptocurrencies",
    t199: "BeingDex Ecology",
    t200: "Manage your assets easily",
    t201: "BeingDex is an order book matching decentralized trading platform built with pure smart contracts. The overall ecological layout covers Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, mining pools and other industries.",
    t202: "A decentralized product integrating wallet and transaction",
    t203: "BeingDex - an order matching decentralized trading platform built with pure smart contracts",
    t204: "Application - BeingDex diversified ecological products",
    t205: "Wallet - Manage your multi-chain assets",
    t206: "Trading should be done anytime and anywhere",
    t207: "Download the App and we will help you trade 24/7",
    t208: "Scan to download",
    t209: "Media Resources",
    t210: "Compliance and Policy",
    t211: "Global official certification of security compliance to ensure the security of user assets",
    t212: "Obtain US MSB license",
    t213: "November 28, 2023",
    t214: "Application for Dubai DMCC license is pending",
    t215: "Application for licenses from the Hong Kong Securities Regulatory Commission/VARA/DIFC/ADGM/US MTL etc.",
    t216: "Our partners",
    t217: "15+ years of experience in information technology.<br>Highly skilled senior cloud computing/DevOps and application architect with experience in AWS, GCP, Azure and DevOps/SystemOps/DevOps tools and Extensive understanding of services.<br>8+ years of experience working as a Cloud/DevSecOps/Application Architect in the financial sector<br>Designed Canada's first cryptocurrency hardware wallet prototype for my startup Blockchain Mind.",
    t218: "Invite friends and win up to<br>9,000 USDT",
    t219: "Invitation link",
    t220: "Invite now",
    t221: "Invite after connecting to wallet",
    t222: "Invitation record",
    t223: "Username",
    t224: "Registration time",
    t225: "Recharge reaches standard",
    t226: "Transaction meets standard",
    t227: "Deposit bonus",
    t228: "Blind box",
    t229: "Popular Events",
    t230: "Rules",
    t231: "1. When the invited friend completes the recharge task, the inviter can get a 100 USDT discount coupon. After the invited friend completes the transaction task, the inviter can randomly draw a blind box reward of 5-500 USDT.<br> 2. Recharge task : Within 30 days after the invited friend registers, recharge through designated channels and the cumulative net deposit exceeds 50USDT.<br> 3. Trading tasks: Within 30 days after the invited friend registers, the cumulative spot or contract transaction volume exceeds 200USDT. <br>4. Invited friends must complete the recharge task before you can unlock the trading task reward. If your invited friend does not successfully complete the recharge task, you will not be able to obtain the reward even if the transaction exceeds 200USDT.<br> 5. Designated recharge channel: Valid recharge Only on-chain recharges, legal currency recharges, card purchases, C2C transactions and third-party payments are allowed. Internal transfers and red envelopes are not included in the effective recharge. 6. Inviters can receive up to 15 fee deduction coupons and 15 cash per month Blind box rewards.<br> 7. Validity period: Handling fee deduction coupons must be collected within 14 days after issuance, and are valid for 14 days after collection. Please pay attention to receiving and using them in time to avoid reward expiration; the validity period for blind box reward redemption is 90 days. Please redeem the cash coupon reward as soon as possible after receiving the reward. The cash coupon is valid for 14 days after redemption.<br> 8. Invitations from the same IP address or device will be regarded as self-invitation. Self-invitation will cause the user to lose the The rewards obtained and the qualifications for receiving rewards in the future. BeingDex reserves the right to freeze illegal accounts and confiscate the assets in the accounts.<br>9. When the rewards are issued, the system will automatically determine whether the current two parties have exclusive partner status. If the inviter or If either of the invitees is an exclusive partner, the reward will conflict with the exclusive partner rebate reward, and the reward will not be issued. In addition, sub-accounts cannot participate in activities as independent accounts, and the data will not be merged into the main account.<br > 10. The above rules will be effective from 18:00 on May 11, 2023 (UTC+8). BeingDex reserves the right of final interpretation of this activity. If any malicious behavior or illegal and unethical behavior that exploits platform vulnerabilities is discovered, BeingDex will Have the right to handle user accounts and assets.<br> 11. You may not pretend to be BeingDex official and make misleading statements, including but not limited to purchasing keywords such as 'BeingDex', 'BeingDex Login', 'BeingDex Official', 'BeingDex C2C' Promote on search engines. Those who violate the requirements will be disqualified from rewards and promotions.",
    t232: "Compliance and Security",
    t233: "BeingDex insists on implementing a comprehensive compliance and security governance system and follows strict standards and processes developed by the compliance advisory team to ensure comprehensive risk management and monitoring. <br>The platform regularly conducts comprehensive risk assessments to identify potential risk points, including market risks and operational risks. Implement effective risk management strategies, actively track and identify possible internal and external risks, and take appropriate response measures. For risks caused by external factors, BeingDex will use advanced encryption technology to protect data security. For internal risks, establish a strict internal control mechanism, including an authorization mechanism to clarify responsibilities, and conduct regular internal and external audits. <br>Guarantee the compliance and compliance of the company's operations by regularly coordinating with local regulatory authorities and conducting compliance reviews, including domestic and foreign laws and regulations, especially those regarding financial services, data protection and anti-money laundering (AML). Security, ensuring the platform complies with all applicable financial regulations and standards.",
    t234: "Compliance Management Framework",
    t235: "Identification",
    t236: "Evaluation",
    t237: "Execute",
    t238: "evaluation",
    t239: "1. Compliance management",
    t240: "Under the supervision of a team of compliance experts, BeingDex follows strict compliance standards and protocols, implements a comprehensive compliance management structure, and conducts effective identification, assessment, execution and evaluation.<br>BeingDex actively detects and identifies sources from External and internal risks and take necessary remedial measures. External risks refer to risks that may be caused by external changes, such as wrong information published by third-party advertisements of BeingDex agents.<br> Internal risks refer to risks that may come from within the organization Risks, such as unauthorized, inappropriate, illegal or unethical conduct by internal employees.<br>BeingDex works with local regulators through a combination of assessments and annual compliance reviews to ensure that our compliance standards meet local requirements.",
    t241: "2.eKYC technology",
    t242: "BeingDex adopts electronic identity verification (eKYC) to secure the platform and reduce potential fraud and illegal risks. In addition to this, BeingDex has sanctions and anti-money laundering (AML) policies in place to comply with all relevant jurisdictions, And prevent counterfeiting or other criminal activities on the platform.<br>Efficiency is crucial for Customer Due Diligence (CDD), therefore, BeingDex adopts eKYC technology to optimize the user identity verification (KYC) process under the premise of compliance. <br>This technology enables facial recognition and automatic cross-matching between user-provided identification and real-time portraits, thereby preventing counterfeit identity and also greatly shortening the time for users to conduct personal identity verification on the BeingDex platform.",
    t243: "2. Blockchain analysis",
    t244: "BeingDex deploys external blockchain analysis tools to closely monitor transactions on the platform and reduce the risk of fraudulent activities and the emergence of high-risk users*. The immutable and transparent nature of the blockchain allows us to comprehensively detect transactions on the platform All transactions.<br>*High-risk users include but are not limited to:<br>- Customers in sensitive countries or regions<br>- Government officials<br>- Customers from sensitive industries (such as capital-intensive businesses)<br >Based on the assessment of our risk and governance team, we will take various measures against high-risk users, which may include asset seizure, multiple reviews or audits, etc., depending on the specific situation.",
    t245: "3.Network security",
    t246: "BeingDex consults independent network security experts to improve the security and stability of the platform. At the same time, network penetration testing and vulnerability assessments are conducted twice a year to promptly and quickly handle detected potential threats.<br>In addition to the above tests , BeingDex also encrypts all sensitive data to prevent risks such as theft, unauthorized access or modification. All data transferred or saved is encrypted and securely stored in fault-tolerant storage.",
    t247: "Operation successful",
    t248: "All read",
    t249: "Quotes",
    t250: "Today's change",
    t251: "24H trading volume",
    t252: "24H transaction volume",
    t253: "Popular currencies",
    t254: "Latest currency",
    t255: "The currency with the largest increase",
    t256: "Highest trading volume currency",
    t257: "Faster transactions, better assets",
    t258: "Your future Web3 transaction wallet",
    t259: "Super portal of the Web3 universe",
    t260: "Join 12 million users, easily browse the largest NFT market and securely interact with 20,000+ DApps on BeingDex Wallet",
    t261: "Enjoy the most comprehensive and easy-to-use NFT platform",
    t262: "Aggregating multiple mainstream NFT markets, supporting one-click batch placement of orders, and purchase of NFTs in any currency",
    t263: "Purchase",
    t264: "Let blockchain happen everywhere",
    t265: "Multi-chain wallet, safe and easy to use, blockchain entrance",
    t266: "Open source wallet",
    t267: "Open source wallet, self-sustaining private key, multi-layer encryption",
    t268: "Follow your heart and feel at ease",
    t269: "Cross-chain, convenient, decentralized, one-stop demand",
    t270: "Decentralized wallet",
    t271: "Separation of hot and cold assets, safe and convenient Token 40000+",
    t272: "Cryptoassets",
    t273: "Crypto assets 40,000+ support various assets for trading on DEX.",
    t274: "Multiple encryption technology",
    t275: "Store cryptocurrency securely and control your own assets.",
    t276: "Multiple gain mode",
    t277: "Staking, mining, DeFi, chain games.",
    t278: "Self-custody of assets, peer-to-peer matching of wallet transactions",
    t279: "Safety with zero accidents and pure smart contract execution",
    t280: "Original decentralized K-line chart, native advantages",
    t281: "Your choice is the same as theirs",
    t282: "Trust and choice of 1,000+ leading companies",
    t283: "plug-in wallet",
    t284: "Plug-in installation tutorial",
    t285: "The world's leading blockchain digital asset management tool",
    t286: "Pure smart contract execution",
    t287: "Download now",
    t288: "DApp Ecological Entrance",
    t289: "Explore DeFi, GameFi, etc., and quickly play with the DApp economy",
    t290: "Let's get started! Click here to submit suggestions or feedback",
    t291: "View more",
    t292: "Token type",
    t293: "BeingDex，Powerd by multi-chain<br>One-stop asset management trading platform<br>Safe, Efficient, Low cost",
    t294: "BeingDex cross-chain bridge",
    t295: "English",
    t296: "Not open yet",
    t297: "operate",
    t298: "wallet",
    t299: "Swap",
    t300: "Dapp",
    t301: "Blog"
  }
}