export default {
  text: {
    t1: "Inicio",
    t2: "Únase a nosotros",
    t3: "Tienda Google",
    t4: "Tienda Apple",
    t5: "Descargar aplicación",
    t6: "Descarga de Chrome",
    t7: "Descarga local",
    t8: "Precio de moneda BDX",
    t9: "Volumen de operaciones",
    t10: "Usuario de la comunidad",
    t11: "Número de transacciones",
    t12: "Volumen total de transacciones BDX",
    t13: "Lista de crecimiento",
    t14: "Lista de rechazos",
    t15: "Nueva lista de monedas",
    t16: "Lista de volúmenes de transacciones",
    t17: "nombre",
    t18: "Último precio",
    t19: "precio",
    t20: "El aumento de hoy",
    t21: "Aumentar o disminuir",
    t22: "volumen de operaciones 24 horas",
    t23: "Transacción",
    t24: "Aún no hay datos",
    t25: "Ver todo",
    t26: "Seguro, eficiente, de bajo costo",
    t27: "Servicio al cliente en línea",
    t28: "Cooperación empresarial",
    t29: "Empresa",
    t30: "Acerca de nosotros",
    t31: "Centro de ayuda",
    t32: "Anuncio",
    t33: "Token BDX",
    t34: "producto",
    t35: "Comprar monedas",
    t36: "billetera Web3",
    t37: "Servicio",
    t38: "Comentarios",
    t39: "Solicitud de cotización de divisas",
    t40: "Invitación de amigo",
    t41: "Divulgación legal y de riesgos",
    t42: "Licencia de cumplimiento",
    t43: "Política contra el blanqueo de capitales",
    t44: "Política de privacidad",
    t45: "Acuerdo de usuario",
    t46: "Declaración legal",
    t47: "Advertencia de riesgo",
    t48: "regla ST",
    t49: "billetera enchufable",
    t50: "Descargar billetera",
    t51: "Idioma",
    t52: "Cerrar sesión",
    t53: "Conectar billetera",
    t54: "Cargando...",
    t55: "No más...",
    t56: "Acerca de BeingDex",
    t57: "Detrás de BeingDex hay un grupo de pioneros en la adopción de la tecnología blockchain y creyentes en el desarrollo futuro de blockchain.",
    t58: "Desde 2018, establecimos un intercambio de criptomonedas y nos hemos comprometido a brindar soluciones comerciales seguras e integrales para ayudar a los usuarios a operar de manera más inteligente.",
    t59: "Orden pendiente de cadena completa que coincide con la plataforma comercial descentralizada",
    t60: "Dirección registrada global",
    t61: "100.000+",
    t62: "30 millones de USDT",
    t63: "Volumen de operaciones diario",
    t64: "Nuestra historia",
    t65: 'Este es un grupo de geeks que creen firmemente en blockchain y los activos cifrados. En 2010, compramos nuestro primer Bitcoin a través de una plataforma OTC de comercio electrónico. En ese momento, estábamos nerviosos e inquietos. A medida que avanzaba el ciclo de la industria Los cambios, los métodos de transacción y las formas de productos continúan innovando y evolucionando, presentando una situación en la que Cex y Dex se desarrollan simultáneamente. Sin embargo, también nos damos cuenta de que el Dex existente está sujeto a su mecanismo modelo y no puede maximizar la eficiencia de los activos.<br >Al mismo tiempo Al mismo tiempo, a medida que la industria del cifrado tiene una influencia cada vez más amplia y profunda a escala global, además de las áreas desarrolladas, cada vez más personas de áreas con infraestructura financiera débil están comenzando a unirse, pero tienen dificultades para comprender productos financieros complejos y mecanismos algorítmicos. ., esto se ha convertido en una brecha que les impide conectar el nuevo mundo y los nuevos activos.<br>BeingDex se compromete a cruzar esta brecha y construir productos de aplicaciones de cadena completa y ecología a través de nuevos contratos inteligentes.<br>Being tiene "existencia" " Las connotaciones como "esencia" y "vida biológica" expresan nuestro espíritu de explorar el origen de las cosas, nuestra práctica fundamental del valor del producto y nuestra búsqueda final de la experiencia del usuario. Nos animamos y damos la bienvenida a más personas para que abran sus mentes y adopte los activos de cifrado y ayúdelos a comenzar su propio viaje de riqueza criptográfica a través de servicios de productos amigables y fáciles de usar.',
    t66: "Visión",
    t67: "Crear un mundo de riqueza futuro más libre, más justo y más transparente a través de Web3",
    t68: "Misión",
    t69: "Cree la plataforma comercial definitiva que todos puedan usar y conviértase en el proveedor de servicios financieros de activos digitales líder en la industria",
    t70: "Nuestros valores",
    t71: "Usuario primero",
    t72: "Preste atención a las necesidades y actitudes de cada usuario, comuníquese de manera objetiva y sincera y publique información de la plataforma de manera oportuna.",
    t73: "Integridad y rigor",
    t74: 'Nos adherimos al principio de" no hacer el mal "y nos ganamos la confianza del mercado y de los usuarios a través de la responsabilidad y la responsabilidad.',
    t75: "Innovación y emprendimiento",
    t76: "Nuestro eterno objetivo son los productos y servicios extremos y la construcción de ventajas estructurales.",
    t77: "Empiece con el fin en mente",
    t78: "Haga cosas a largo plazo con socios a largo plazo, comprenda el proceso, cree condiciones, preste atención a los resultados de la retroalimentación y alcance continuamente objetivos importantes.",
    t79: "Nuestro equipo",
    t80: "Con más de 150 empleados de más de 10 países, el equipo de BeingDEX cuenta con talento senior de todos los rincones del planeta, lo que nos brinda un alcance verdaderamente global.",
    t81: "Nuestros servicios",
    t82: "SiendoDEX",
    t83: "BeingDex es un nuevo intercambio descentralizado basado en el desarrollo de múltiples cadenas. Adopta un modelo de coincidencia de pedidos en cadena y el puente entre cadenas admite las cadenas públicas BSC, TRON y OKX.",
    t84: "Ser billetera",
    t85: "Being Wallet adopta dos mecanismos de seguridad principales: autocustodia de los activos del usuario y anonimato total. Su tecnología de billetera subyacente admite múltiples protecciones de seguridad, como el cifrado biométrico local y el aislamiento de seguridad, y admite la gestión de activos de múltiples cadenas para proteger la seguridad de los usuarios. transacciones.",
    t86: "Ser NFT",
    t87: "Al ser NFT compatible con ETH, BSC, Mango, TRON, Polygon, Solana, la emisión de NFT con un solo clic en múltiples cadenas, las transacciones y otras actividades se completan a través del protocolo de cadena sin intervención de terceros. El NFT organizado por la DAO es almacenado en la billetera. Fundición en cadena, transacciones inteligentes, seguras y convenientes.",
    t88: "¡Comience su viaje criptográfico ahora!",
    t89: "Opere en una plataforma en la que confían millones de usuarios.",
    t90: "Carga exitosa",
    t91: "Error en la carga",
    t92: "Por favor seleccione la cadena pública a la que pertenece",
    t93: "Ingrese el nombre del proyecto",
    t94: "Por favor cargue el logotipo",
    t95: "Ingrese la abreviatura del token",
    t96: "Por favor ingrese la dirección del contrato",
    t97: "Ingrese la cantidad de emisión",
    t98: "Ingrese el enlace del sitio web oficial",
    t99: "Por favor ingrese su dirección de correo electrónico",
    t100: "Por favor ingrese la información de su token",
    t101: "Envío exitoso",
    t102: "Aplicación de listado de divisas BeingDex",
    t103: "Gracias por su atención a BeingDex Exchange. Complete el formulario de solicitud y proporcione información válida. Revisaremos su proyecto en función de la información que proporcionó. Envíe esta solicitud y su proyecto se enviará al departamento de listado de divisas. . Revisión. Después de pasar la revisión preliminar, haremos los arreglos necesarios para que un especialista en cotización de divisas comparta el proceso y las técnicas de cotización de divisas con usted y lo guíe a través del proceso de cotización de divisas.",
    t104: "Indica requerido",
    t105: "Cadena pública a la que pertenece",
    t106: "Nombre del proyecto",
    t107: "Abreviatura del token",
    t108: "Dirección del contrato",
    t109: "Cantidad de emisión",
    t110: "Enlace al sitio web oficial",
    t111: "Buzón",
    t112: "Información del token",
    t113: "Por favor ingrese la información de su token, no más de 120 caracteres",
    t114: "Enviar",
    t115: "Enviar después de conectarse a la billetera",
    t116: "Borrar contenido del formulario",
    t117: "BDX lidera la revolución en la industria de la criptografía",
    t118: "Conecte sus activos, aplicaciones DeFi y NFT para ayudarlo a desbloquear el mundo Web3 rápidamente",
    t119: "Obtén BDX con un clic",
    t120: "Informe técnico de BDX",
    t121: "Introducción a BDX",
    t122: "Mantén BDX y disfruta de infinitos beneficios",
    t123: "Nueva suscripción",
    t124: "Servicio preferencial",
    t125: "Mecanismo de deflación",
    t126: "Nuevo en línea",
    t127: "Planificación",
    t128: "Obtener BDX",
    t129: "Información de lanzamiento de BDX",
    t130: "Seguro, fácil de usar y estrechamente conectado con culturas e ideologías de todo el mundo",
    t131: "Nombre del token",
    t132: "Símbolo de ficha",
    t133: "Cadena de propiedad",
    t134: "Dirección del contrato",
    t135: "Precio de emisión",
    t136: "Suministro de circulación",
    t137: "Oferta total",
    t138: "Fecha de emisión",
    t139: "Reemplazar BDX",
    t140: "Para canjear tokens BDX existentes",
    t141: "Motivación del equipo",
    t142: "2% desbloqueado cada 6 meses, se desbloqueará por completo en 5 años (60 meses)",
    t143: "Inversión económica y ecológica",
    t144: "Ir al ecosistema BeingDex para inversión de fondos",
    t145: "Promoción de marca",
    t146: "Lanzamientos máximos por año",
    t147: "Entrada del usuario",
    t148: "Fondo de Protección",
    t149: "Para indemnización por posibles accidentes en la plataforma",
    t150: "Trabaja con nosotros para crear un ecosistema BDX seguro y confiable y promover el rápido desarrollo de Web3",
    t151: "Obtén BDX con un clic",
    t152: "Recomendado",
    t153: "Último blog",
    t154: "Aún no hay datos",
    t155: "Tienda de aplicaciones DApp",
    t156: "Buscar",
    t157: "Seleccionar categoría",
    t158: "Descargo de responsabilidad importante",
    t159: 'Todo el contenido proporcionado en este sitio web, sitios web con hipervínculos, aplicaciones relacionadas, foros, blogs, cuentas de redes sociales y otras plataformas (el "Sitio") es para su información general obtenida únicamente de fuentes de terceros. No somos responsables de nuestra contenido No se ofrecen garantías de ningún tipo, incluidas, entre otras, la precisión y la actualidad. Ninguna parte del contenido que proporcionamos constituye asesoramiento financiero, asesoramiento legal o cualquier otra forma de asesoramiento y está diseñado para satisfacer su confianza específica para cualquier propósito. Cualquier uso o confianza en nuestro contenido se realiza bajo su propio riesgo y discreción. Debe realizar su propia investigación, revisión, análisis y verificación antes de confiar en nuestro contenido. El comercio es una actividad de alto riesgo que puede resultar en pérdidas significativas, por lo que consulte a su asesor financiero antes de tomar cualquier decisión. Nada en nuestro sitio web es una solicitud u oferta.',
    t160: "Por favor ingrese los detalles de la sugerencia",
    t161: "Envío exitoso",
    t162: "Cada una de tus sugerencias",
    t163: "Escucharemos atentamente y lo trataremos con seriedad",
    t164: "Comentarios",
    t165: "Si encuentra algún fallo o vulnerabilidad de seguridad, envíenos sus comentarios a tiempo",
    t166: "Si tiene alguna pregunta, consulte el Centro de ayuda para obtener respuestas a las preguntas más frecuentes.",
    t167: "¿Qué opinas de nuestra experiencia con el producto?",
    t168: "¡No es una buena experiencia!",
    t169: "¡Para mejorar!",
    t170: "¡Bastante satisfactorio!",
    t171: "¡Súper increíble!",
    t172: "Enviar sugerencia",
    t173: "Bienvenido a compartir sus sugerencias de productos. BeingDex tomará en serio sus comentarios. Si tiene consultas urgentes, comuníquese con el servicio de atención al cliente.",
    t174: "Categoría sugerida",
    t175: "Recomendaciones de seguridad",
    t176: "Sugerencias de funciones",
    t177: "Sugerencias de diseño",
    t178: "Sugerencias de operación",
    t179: "Otras sugerencias",
    t180: "Detalles de la sugerencia",
    t181: "Por favor ingrese sus comentarios, no más de 500 caracteres",
    t182: "Subir imágenes (opcional)",
    t183: "Cargue capturas de pantalla relacionadas con el problema. El formato de la imagen es JPG o PNG y el tamaño no debe exceder los 2 M",
    t184: "Información de contacto (opcional)",
    t185: "Ingrese la información de contacto",
    t186: "Confirmar envío",
    t187: "Enviar después de conectarse a la billetera",
    t188: "Guardar borrador",
    t189: "¿Cómo funciona?",
    t190: "Enviar sugerencia",
    t191: "Revisión del equipo",
    t192: "Distribuir recompensas",
    t193: "BeingDex presta servicios a usuarios de todo el mundo. Consideramos que el desarrollo seguro y estable de la plataforma es nuestra máxima prioridad. Esperamos sus valiosas sugerencias. Mejoremos la calidad del producto y creemos juntos un futuro mejor.",
    t194: "Un protocolo en el que los usuarios de Web3 pueden confiar<br>permite a los usuarios de Defi completar transacciones fácilmente",
    t195: "Autocustodia de activos, transacciones de comparación punto a punto de billetera",
    t196: "Seguridad con cero accidentes y ejecución pura de contratos inteligentes",
    t197: "Gráfico de líneas K descentralizado original, ventajas nativas",
    t198: "Criptomonedas populares",
    t199: "BeingDex Ecología",
    t200: "Administre sus activos fácilmente",
    t201: "BeingDex es una plataforma comercial descentralizada que combina libros de pedidos construida con contratos puramente inteligentes. El diseño ecológico general cubre Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, pools de minería y otras industrias.",
    t202: "Un producto descentralizado que integra billetera y transacciones",
    t203: "BeingDex: una plataforma comercial descentralizada de coincidencia de órdenes construida con contratos puramente inteligentes",
    t204: "Aplicación - Productos ecológicos diversificados BeingDex",
    t205: "Monedero: administre sus activos de múltiples cadenas",
    t206: "El comercio debe realizarse en cualquier momento y en cualquier lugar",
    t207: "Descarga la aplicación y te ayudaremos a operar las 24 horas del día, los 7 días de la semana",
    t208: "Escanear para descargar",
    t209: "Recursos multimedia",
    t210: "Cumplimiento y política",
    t211: "Certificación oficial global de cumplimiento de seguridad para garantizar la seguridad de los activos de los usuarios",
    t212: "Obtener licencia MSB de EE. UU.",
    t213: "28 de noviembre de 2023",
    t214: "La solicitud de licencia DMCC de Dubai está pendiente",
    t215: "Solicitud de licencia de la Comisión Reguladora de Valores de Hong Kong/VARA/DIFC/ADGM/US MTL, etc.",
    t216: "Nuestros socios",
    t217: "Más de 15 años de experiencia en tecnología de la información.<br>Arquitecto de aplicaciones y computación en la nube/DevOps senior altamente calificado con experiencia en AWS, GCP, Azure y herramientas DevOps/SystemOps/DevOps y amplio conocimiento de los servicios.<br>8 + años de experiencia trabajando como Cloud/DevSecOps/Arquitecto de aplicaciones en el sector financiero<br>Diseñé el primer prototipo de billetera de hardware de criptomonedas de Canadá para mi startup Blockchain Mind.",
    t218: "Invita a amigos y gana hasta<br>9000 USDT",
    t219: "Enlace de invitación",
    t220: "Invitar ahora",
    t221: "Invitar después de conectarse a la billetera",
    t222: "Registro de invitación",
    t223: "Nombre de usuario",
    t224: "Hora de registro",
    t225: "La recarga alcanza el estándar",
    t226: "La transacción cumple con el estándar",
    t227: "Bono de depósito",
    t228: "Caja ciega",
    t229: "Eventos populares",
    t230: "Reglas",
    t231: '1. Cuando el amigo invitado completa la tarea de recarga, el que invita puede obtener un cupón de descuento de 100 USDT. Después de que el amigo invitado completa la tarea de transacción, el que invita puede sacar aleatoriamente una recompensa de caja ciega de 5-500 USDT.<br > 2. Tarea de recarga: dentro de los 30 días posteriores al registro del amigo invitado, recargue a través de los canales designados y el depósito neto acumulado supere los 50 USDT.<br> 3. Tareas comerciales: dentro de los 30 días posteriores al registro del amigo invitado, la transacción al contado o del contrato acumulada el volumen supera los 200 USDT. <br>4. Los amigos invitados deben completar la tarea de recarga antes de que usted pueda desbloquear la recompensa de la tarea comercial. Si su amigo invitado no completa con éxito la tarea de recarga, no podrá obtener la recompensa incluso si la transacción supera los 200USDT.<br> 5. Canal de recarga designado: Recarga válida Solo se permiten recargas en cadena, recargas en moneda legal, compras con tarjeta, transacciones C2C y pagos de terceros, las transferencias internas y los sobres rojos no están incluidos en la recarga efectiva. 6. Los invitados pueden recibir hasta 15 cupones de deducción de tarifas y 15 recompensas en efectivo por mes.<br> 7. Período de validez: los cupones de deducción de tarifas de manejo deben cobrarse dentro de los 14 días posteriores a su emisión y son válidos durante 14 días después de su recolección. Preste atención a recibirlos y usarlos a tiempo para evitar la caducidad de la recompensa; el período de validez para el canje de recompensas de caja ciega es de 90 días. Canjee la recompensa del cupón en efectivo lo antes posible después de recibir la recompensa. El cupón en efectivo es válido por 14 días después del canje.<br> 8. Las invitaciones desde la misma dirección IP o dispositivo se considerarán autoinvitaciones. La autoinvitación hará que el usuario pierda las recompensas obtenidas y las calificaciones para recibir recompensas en el futuro. BeingDex se reserva el derecho a congelar cuentas ilegales y confiscar los activos en las cuentas.<br>9. Cuando se emitan las recompensas, el sistema determinará automáticamente si las dos partes actuales tienen estatus de socio exclusivo. Si el que invita o si alguno de los invitados es un socio exclusivo, la recompensa entrará en conflicto con la recompensa de reembolso del socio exclusivo y la recompensa no se emitirá. Además, las subcuentas no pueden participar en actividades como cuentas independientes y los datos no se fusionarán con la cuenta principal.<br > 10. Las normas anteriores entrarán en vigor a partir de las 18:00 horas del 11 de mayo de 2023 (UTC+8). BeingDex se reserva el derecho de interpretación final de esta actividad. Si se descubre algún comportamiento malicioso o ilegal y poco ético que aproveche las vulnerabilidades de la plataforma , BeingDex tendrá derecho a manejar cuentas y activos de usuario.<br> 11. No puede pretender ser oficial de BeingDex y hacer declaraciones engañosas, incluidas, entre otras, la compra de palabras clave como "BeingDex", "BeingDex Login", " BeingDex Official", "BeingDex C2C" Promocionar en motores de búsqueda. Quienes violen los requisitos serán descalificados de recompensas y promociones.',
    t232: "Cumplimiento y seguridad",
    t233: "BeingDex insiste en implementar un sistema integral de gobierno de seguridad y cumplimiento y sigue estándares y procesos estrictos formulados por el equipo asesor de cumplimiento para garantizar la gestión y el monitoreo integrales de riesgos.<br>La plataforma realiza periódicamente evaluaciones integrales de riesgos para identificar riesgos potenciales Los puntos incluyen riesgo de mercado y riesgo operativo. Implementar estrategias efectivas de gestión de riesgos, rastrear e identificar activamente posibles riesgos internos y externos, y tomar medidas de respuesta adecuadas. Para los riesgos causados ​​por factores externos, BeingDex utilizará tecnología de cifrado avanzada que protege la seguridad de los datos. Para los riesgos internos. , establecer un estricto mecanismo de control interno, incluido un mecanismo de autorización para aclarar responsabilidades, y realizar auditorías internas y externas periódicas.<br>Al coordinar periódicamente con las agencias reguladoras locales y realizar revisiones de cumplimiento, esto incluye leyes y regulaciones externas nacionales, especialmente aquellas relacionadas con servicios financieros, protección de datos y lucha contra el lavado de dinero (AML), garantizar el cumplimiento y la seguridad de las operaciones de la empresa y garantizar que la plataforma cumpla con todas las regulaciones y estándares financieros aplicables.",
    t234: "Marco de gestión del cumplimiento",
    t235: "Identificación",
    t236: "Evaluación",
    t237: "Ejecutar",
    t238: "evaluación",
    t239: "1. Gestión del cumplimiento",
    t240: "Bajo la supervisión de un equipo de expertos en cumplimiento, BeingDex sigue estrictos estándares y protocolos de cumplimiento, implementa una estructura integral de gestión de cumplimiento y lleva a cabo una identificación, valoración, ejecución y evaluación efectivas.<br>BeingDex detecta e identifica activamente fuentes externas y riesgos internos y tomar las medidas correctivas necesarias. Los riesgos externos se refieren a los riesgos que pueden ser causados ​​por cambios externos, como información incorrecta publicada por anuncios de terceros de los agentes de BeingDex.<br> Los riesgos internos se refieren a los riesgos que pueden surgir dentro del Riesgos de la organización, como conductas no autorizadas, inapropiadas, ilegales o poco éticas por parte de empleados internos.<br>BeingDex trabaja con los reguladores locales a través de una combinación de evaluaciones y revisiones de cumplimiento anuales para garantizar que nuestros estándares de cumplimiento cumplan con los requisitos locales.",
    t241: "2.tecnología eKYC",
    t242: "BeingDex adopta la verificación de identidad electrónica (eKYC) para proteger la plataforma y reducir posibles fraudes y riesgos ilegales. Además de esto, BeingDex cuenta con sanciones y políticas contra el lavado de dinero (AML) para cumplir con todas las jurisdicciones relevantes, y prevenir la falsificación u otras actividades delictivas en la plataforma.<br>La eficiencia es crucial para la debida diligencia del cliente (CDD), por lo tanto, BeingDex adopta la tecnología eKYC para optimizar el proceso de verificación de identidad del usuario (KYC) bajo la premisa de cumplimiento.<br>Esto La tecnología permite el reconocimiento facial y la comparación automática entre la identificación proporcionada por el usuario y los retratos en tiempo real, evitando así identidades falsas y también acortando en gran medida el tiempo para que los usuarios realicen la verificación de identidad personal en la plataforma BeingDex.",
    t243: "2. Análisis de blockchain",
    t244: "BeingDex implementa herramientas externas de análisis de blockchain para monitorear de cerca las transacciones en la plataforma y reducir el riesgo de actividades fraudulentas y la aparición de usuarios de alto riesgo*. La naturaleza inmutable y transparente de blockchain nos permite detectar de manera integral las transacciones en la plataforma Todas las transacciones.<br>*Los usuarios de alto riesgo incluyen, entre otros:<br>- Clientes en países o regiones sensibles<br>- Funcionarios gubernamentales<br>- Clientes de industrias sensibles (como empresas con uso intensivo de capital) <br >Con base en la evaluación de nuestro equipo de riesgo y gobernanza, tomaremos varias medidas contra los usuarios de alto riesgo, que pueden incluir incautación de activos, múltiples revisiones o auditorías, etc., dependiendo de la situación específica.",
    t245: "3.Seguridad de la red",
    t246: "BeingDex consulta a expertos independientes en seguridad de redes para mejorar la seguridad y estabilidad de la plataforma. Al mismo tiempo, se realizan pruebas de penetración de redes y evaluaciones de vulnerabilidad dos veces al año para manejar rápida y rápidamente las posibles amenazas detectadas.<br>Además de Después de las pruebas anteriores, BeingDex también cifra todos los datos confidenciales para evitar riesgos como robo, acceso no autorizado o modificación. Todos los datos transferidos o guardados se cifran y se almacenan de forma segura en un almacenamiento tolerante a fallos.",
    t247: "Operación exitosa",
    t248: "Todo leído",
    t249: "Citas",
    t250: "El cambio de hoy",
    t251: "volumen de operaciones 24 horas",
    t252: "volumen de transacciones 24H",
    t253: "Monedas populares",
    t254: "Última moneda",
    t255: "La moneda con mayor aumento",
    t256: "Moneda con mayor volumen de operaciones",
    t257: "Transacciones más rápidas, mejores activos",
    t258: "Su futura billetera de transacciones Web3",
    t259: "Superportal del universo Web3",
    t260: "Únase a 12 millones de usuarios, explore fácilmente el mercado NFT más grande e interactúe de forma segura con más de 20 000 DApps en BeingDex Wallet",
    t261: "Disfrute de la plataforma NFT más completa y fácil de usar",
    t262: "Agregar múltiples mercados de NFT convencionales, admitir la realización de pedidos por lotes con un solo clic y la compra de NFT en cualquier moneda",
    t263: "Compra",
    t264: "Dejemos que blockchain suceda en todas partes",
    t265: "Monedero multicadena, seguro y fácil de usar, entrada blockchain",
    t266: "billetera de código abierto",
    t267: "Monedero de código abierto, clave privada autosostenible, cifrado multicapa",
    t268: "Sigue tu corazón y siéntete a gusto",
    t269: "Demanda única, conveniente, descentralizada y de cadena cruzada",
    t270: "Monedero descentralizado",
    t271: "Separación de activos fríos y calientes, Token 40000+ seguro y conveniente",
    t272: "Criptoactivos",
    t273: "Más de 40.000 activos criptográficos admiten varios activos para operar en DEX.",
    t274: "Tecnología de cifrado múltiple",
    t275: "Almacene criptomonedas de forma segura y controle sus propios activos.",
    t276: "Modo de ganancia múltiple",
    t277: "Apuestas, minería, DeFi, juegos en cadena.",
    t278: "Autocustodia de activos, comparación entre pares de transacciones de billetera",
    t279: "Seguridad con cero accidentes y ejecución pura de contratos inteligentes",
    t280: "Gráfico de líneas K descentralizado original, ventajas nativas",
    t281: "Tu elección es la misma que la de ellos",
    t282: "Confianza y elección de más de 1000 empresas líderes",
    t283: "billetera enchufable",
    t284: "Tutorial de instalación del complemento",
    t285: "La herramienta de gestión de activos digitales blockchain líder en el mundo",
    t286: "Ejecución pura de contrato inteligente",
    t287: "Descargar ahora",
    t288: "Entrada ecológica DApp",
    t289: "Explora DeFi, GameFi, etc. y juega rápidamente con la economía de DApp",
    t290: "¡Comencemos! Haga clic aquí para enviar sugerencias o comentarios",
    t291: "Ver más",
    t292: "Tipo de token",
    t293: "BeingDex, plataforma comercial de gestión de activos integral impulsada por múltiples cadenas<br>segura, eficiente y de bajo costo",
    t294: "Puente de cadenas cruzadas BeingDex",
    t295: "español",
    t296: "Aún no está abierto",
    t297: "funcionar",
    t298: "billetera",
    t299: "Intercambiar",
    t300: "Dapp",
    t301: "Blog"
  }
}