export default {
  text: {
    t1: "Accueil",
    t2: "Rejoignez-nous",
    t3: "GoogleStore",
    t4: "AppleStore",
    t5: "Télécharger l'application",
    t6: "Téléchargement Chrome",
    t7: "Téléchargement local",
    t8: "Prix de la devise BDX",
    t9: "Volume des échanges",
    t10: "Utilisateur de la communauté",
    t11: "Nombre de transactions",
    t12: "Volume total des transactions BDX",
    t13: "Liste de croissance",
    t14: "Liste de refus",
    t15: "Nouvelle liste de pièces",
    t16: "Liste des volumes de transactions",
    t17: "nom",
    t18: "Dernier prix",
    t19: "prix",
    t20: "Augmentation d'aujourd'hui",
    t21: "Augmentation ou diminution",
    t22: "Volume des échanges sur 24H",
    t23: "Transaction",
    t24: "Pas encore de données",
    t25: "Voir tout",
    t26: "Sûr, efficace, faible coût",
    t27: "Service client en ligne",
    t28: "Coopération commerciale",
    t29: "Société",
    t30: "À propos de nous",
    t31: "Centre d'aide",
    t32: "Annonce",
    t33: "Jeton BDX",
    t34: "produit",
    t35: "Acheter des pièces",
    t36: "Portefeuille Web3",
    t37: "Service",
    t38: "Retour d'information",
    t39: "Demande de listing des devises",
    t40: "Invitation d'un ami",
    t41: "Divulgation juridique et des risques",
    t42: "Licence de conformité",
    t43: "Politique de lutte contre le blanchiment d'argent",
    t44: "Politique de confidentialité",
    t45: "Contrat d'utilisation",
    t46: "Mention Légale",
    t47: "Avertissement de risque",
    t48: "Règle ST",
    t49: "portefeuille plug-in",
    t50: "Télécharger le portefeuille",
    t51: "Langue",
    t52: "Déconnexion",
    t53: "Connecter le portefeuille",
    t54: "Chargement...",
    t55: "Plus rien...",
    t56: "À propos de BeingDex",
    t57: "Derrière BeingDex se trouve un groupe de premiers utilisateurs de la technologie blockchain et de croyants au développement futur de la blockchain.",
    t58: "Depuis 2018, nous avons créé une bourse de crypto-monnaie et nous nous engageons à fournir des solutions de trading sécurisées et centralisées pour aider les utilisateurs à négocier plus intelligemment.",
    t59: "Ordre en attente de la chaîne complète correspondant à une plateforme de trading décentralisée ",
    t60: "Adresse enregistrée mondiale",
    t61: "100 000+",
    t62: "30 millions USDT",
    t63: "Volume quotidien des échanges",
    t64: "Notre histoire",
    t65: "Il s'agit d'un groupe de geeks qui croient fermement à la blockchain et aux actifs cryptés. En 2010, nous avons acheté notre premier Bitcoin via une plateforme de commerce électronique OTC. À cette époque, nous étions nerveux et inquiets. Les changements, les méthodes de transaction et les formes de produits continuent d'innover et d'évoluer, présentant une situation dans laquelle Cex et Dex se développent simultanément. Cependant, nous réalisons également que le Dex existant est soumis à son mécanisme de modèle et ne peut pas maximiser l'efficacité des actifs.<br >En même temps À mesure que l'industrie du cryptage exerce une influence de plus en plus large et profonde à l'échelle mondiale, en plus des zones développées, de plus en plus de personnes originaires de zones dotées d'une infrastructure financière faible commencent à la rejoindre, mais elles ont du mal à comprendre les produits financiers complexes et les mécanismes algorithmiques. . , c'est devenu un écart qui les empêche de connecter le nouveau monde et les nouveaux actifs.<br>BeingDex s'engage à combler cet écart et à créer des produits d'application et une écologie à chaîne complète grâce à de nouveaux contrats intelligents.<br>Être a 'une existence' Les connotations telles que 'essence' et 'vie biologique' expriment notre esprit d'exploration de l'origine des choses, notre pratique fondamentale de la valeur du produit et notre quête ultime de l'expérience utilisateur. Nous nous encourageons et invitons davantage de personnes à ouvrir leur esprit et adoptez le cryptage des actifs et aidez-les à démarrer leur propre parcours de richesse cryptographique grâce à des services de produits faciles à utiliser et conviviaux.",
    t66: "Vision",
    t67: " Créer un monde de richesse futur plus libre, plus juste et plus transparent grâce au Web3 ",
    t68: "Mission",
    t69: " Créez la plateforme de trading ultime que tout le monde peut utiliser et devenez le principal fournisseur de services financiers sur actifs numériques du secteur ",
    t70: "Nos valeurs",
    t71: "Utilisateur d'abord",
    t72: "Faites attention aux besoins et aux attitudes de chaque utilisateur, communiquez objectivement et franchement et publiez les informations sur la plateforme en temps opportun.",
    t73: " Intégrité et rigueur ",
    t74: 'Nous adhérons au principe de "ne pas faire le mal" et gagnons la confiance du marché et des utilisateurs par la responsabilité et la responsabilisation.',
    t75: "Innover et entreprendre",
    t76: "Les produits et services extrêmes et les avantages structurels du bâtiment sont notre quête éternelle.",
    t77: "Commencer avec la fin en tête",
    t78: " Faites des choses à long terme avec des partenaires à long terme, maîtrisez le processus, créez des conditions, faites attention aux résultats des retours et atteignez continuellement les objectifs des étapes. ",
    t79: "Notre équipe",
    t80: "Avec plus de 150 employés répartis dans plus de 10 pays, l'équipe BeingDEX compte des talents chevronnés venant des quatre coins de la planète, ce qui nous confère une portée véritablement mondiale.",
    t81: "Nos Prestations",
    t82: "ÊtreDEX",
    t83: "BeingDex est un nouvel échange décentralisé basé sur le développement multi-chaînes. Il adopte un modèle de correspondance des commandes en chaîne et le pont inter-chaînes prend en charge les chaînes publiques BSC, TRON et OKX.",
    t84: "Être portefeuille",
    t85: " Being Wallet adopte deux mécanismes de sécurité majeurs : l'auto-garde des actifs des utilisateurs et l'anonymat complet. Sa technologie de portefeuille sous-jacente prend en charge plusieurs protections de sécurité telles que le cryptage biométrique local et l'isolation de sécurité, et prend en charge la gestion des actifs multi-chaînes pour protéger la sécurité des utilisateurs. transactions.",
    t86: " Être NFT ",
    t87: " Étant donné que NFT prend en charge l'émission multi-chaînes en un clic de NFT ETH, BSC, Mango, TRON, Polygon, Solana, les transactions et autres activités sont effectuées via le protocole de chaîne sans intervention de tiers. Le NFT organisé par le DAO est stocké dans le portefeuille. Diffusion en chaîne, transactions intelligentes, sûres et pratiques.",
    t88: "Commencez votre voyage crypto maintenant !",
    t89: "Négociez sur une plateforme approuvée par des millions d'utilisateurs.",
    t90: "Téléchargement réussi",
    t91: "Échec du téléchargement",
    t92: "Veuillez sélectionner la chaîne publique à laquelle vous appartenez",
    t93: "Veuillez saisir le nom du projet",
    t94: "Veuillez télécharger le logo",
    t95: "Veuillez saisir l'abréviation du jeton",
    t96: "Veuillez saisir l'adresse du contrat",
    t97: "Veuillez saisir la quantité de sortie",
    t98: "Veuillez entrer le lien du site officiel",
    t99: "Veuillez saisir votre adresse email",
    t100: "Veuillez saisir les informations de votre jeton",
    t101: "Soumission réussie",
    t102: "Application de liste de devises BeingDex",
    t103: "Merci de l'attention que vous portez à BeingDex Exchange. Veuillez remplir le formulaire de candidature et fournir des informations valides. Nous examinerons votre projet en fonction des informations que vous avez fournies. Veuillez soumettre cette candidature et votre projet sera envoyé au service de liste des devises. . Révision. Une fois que vous aurez passé l'examen préliminaire, nous ferons en sorte qu'un spécialiste de la cotation des devises partage avec vous le processus et les techniques de cotation des devises et vous guidera tout au long du processus de cotation des devises.",
    t104: "Indique requis",
    t105: "Chaîne publique à laquelle il appartient",
    t106: "Nom du projet",
    t107: "Abréviation du jeton",
    t108: "Adresse du contrat",
    t109: "Quantité d'émission",
    t110: "Lien du site officiel",
    t111: "Boîte aux lettres",
    t112: "Informations sur le jeton",
    t113: "Veuillez saisir les informations de votre jeton, pas plus de 120 caractères",
    t114: "Envoyer",
    t115: "Soumettre après connexion au portefeuille",
    t116: "Effacer le contenu du formulaire",
    t117: "BDX mène la révolution dans l'industrie de la cryptographie",
    t118: "Connectez vos actifs, vos applications DeFi et vos NFT pour vous aider à débloquer rapidement le monde Web3",
    t119: "Obtenez BDX en un clic",
    t120: "Livre blanc BDX",
    t121: "Introduction à BDX",
    t122: "Détenez BDX et profitez d'avantages infinis",
    t123: "Nouvel abonnement",
    t124: "Service préférentiel",
    t125: "Mécanisme de déflation",
    t126: "Nouveau en ligne",
    t127: "Planification",
    t128: "Obtenir BDX",
    t129: "Informations sur la version BDX",
    t130: "Sûr, facile à utiliser et étroitement connecté aux cultures et idéologies du monde entier",
    t131: "Nom du jeton",
    t132: "Symbole du jeton",
    t133: "Chaîne propriétaire",
    t134: "Adresse du contrat",
    t135: "Prix d'émission",
    t136: "Alimentation circulation",
    t137: "Approvisionnement total",
    t138: "Date d'émission",
    t139: "Remplacer BDX",
    t140: "Pour le rachat de tokens BDX existants",
    t141: "Motivation de l'équipe",
    t142: "2% débloqués tous les 6mois, seront entièrement débloqués dans 5 ans (60 mois)",
    t143: "Investissement économique et écologique",
    t144: "Aller sur l'écosystème BeingDex pour investir dans des fonds",
    t145: "Promotion de la marque",
    t146: "Sorties maximales par an",
    t147: "Entrée utilisateur",
    t148: "Fonds de protection",
    t149: "Pour indemnisation d'éventuels accidents sur la plateforme",
    t150: "Travailler avec nous pour créer un écosystème BDX sûr et fiable et promouvoir le développement rapide du Web3",
    t151: "Obtenez BDX en un clic",
    t152: "Recommandé",
    t153: "Dernier blog",
    t154: "Pas encore de données",
    t155: "Magasin d'applications DApp",
    t156: "Rechercher",
    t157: "Sélectionner une catégorie",
    t158: " Avertissement important ",
    t159: " Tout le contenu fourni sur ce site Web, les sites Web hyperliés, les applications connexes, les forums, les blogs, les comptes de médias sociaux et autres plateformes (le ' Site ') sont destinés à votre information générale obtenue à partir de sources tierces uniquement. Nous ne sommes pas responsables de notre contenu Aucune garantie d'aucune sorte n'est faite, y compris, mais sans s'y limiter, l'exactitude et l'actualité. Aucune partie du contenu que nous fournissons ne constitue des conseils financiers, des conseils juridiques ou toute autre forme de conseil et n'est conçue pour satisfaire votre confiance spécifique à quelque fin que ce soit. Toute utilisation ou confiance en notre contenu se fait à vos propres risques et à votre discrétion. Vous devez effectuer vos propres recherches, examens, analyses et vérifications avant de vous fier à notre contenu. Le trading est une activité à haut risque qui peut entraîner des pertes importantes, donc veuillez consulter votre conseiller financier avant de prendre toute décision. Rien sur notre site Web ne constitue une sollicitation ou une offre. ",
    t160: "Veuillez saisir les détails de la suggestion",
    t161: "Soumission réussie",
    t162: "Chacune de vos suggestions",
    t163: "Nous l'écouterons attentivement et le traiterons sérieusement",
    t164: "Retour d'information",
    t165: "Si vous découvrez des failles de sécurité ou des vulnérabilités, veuillez nous faire part de vos commentaires en temps opportun",
    t166: "Si vous avez des questions, veuillez consulter le centre d'aide pour obtenir des réponses aux questions fréquemment posées.",
    t167: "Que pensez-vous de notre expérience produit ?",
    t168: "Ce n'est pas une bonne expérience !",
    t169: "A améliorer !",
    t170: "Plutôt satisfaisant !",
    t171: "Super génial !",
    t172: "Soumettre une suggestion",
    t173: "Bienvenue pour partager vos suggestions de produits. BeingDex prendra vos commentaires au sérieux. Si vous avez des demandes urgentes, veuillez contacter le service client.",
    t174: "Catégorie suggérée",
    t175: "Recommandations de sécurité",
    t176: "Suggestions de fonctionnalités",
    t177: "Suggestions de conception",
    t178: "Suggestions d'opération",
    t179: "Autres suggestions",
    t180: "Détails de la suggestion",
    t181: "Veuillez saisir votre commentaire, pas plus de 500 caractères",
    t182: "Télécharger des images (facultatif)",
    t183: "Veuillez télécharger des captures d'écran liées au problème. Le format de l'image est JPG ou PNG et la taille ne doit pas dépasser 2 Mo",
    t184: "Coordonnées (facultatif)",
    t185: "Veuillez saisir vos coordonnées",
    t186: "Confirmer la soumission",
    t187: "Soumettre après connexion au portefeuille",
    t188: "Enregistrer le brouillon",
    t189: "Comment ça marche ?",
    t190: "Soumettre une suggestion",
    t191: "Revue d'équipe",
    t192: "Distribuer les récompenses",
    t193: "BeingDex sert les utilisateurs du monde entier. Nous considérons le développement sûr et stable de la plateforme comme notre priorité absolue. Nous attendons avec impatience vos précieuses suggestions. Améliorons la qualité des produits et créons ensemble un avenir meilleur.",
    t194: "Un protocole auquel les utilisateurs Web3 peuvent faire confiance<br>permet aux utilisateurs Defi d'effectuer facilement des transactions",
    t195: " Auto-conservation des actifs, transactions de correspondance point à point du portefeuille ",
    t196: "Sécurité sans accident et exécution purement intelligente des contrats",
    t197: "Graphique K-line décentralisé original, avantages natifs",
    t198: "Cryptomonnaies populaires",
    t199: " BeingDex Ecologie ",
    t200: "Gérez votre patrimoine facilement",
    t201: "BeingDex est un carnet de commandes correspondant à une plateforme de trading décentralisée construite avec de purs contrats intelligents. La disposition écologique globale couvre Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, les pools miniers et d'autres industries.",
    t202: "Un produit décentralisé intégrant portefeuille et transaction",
    t203: "BeingDex - une plateforme de trading décentralisée de correspondance d'ordres construite avec de purs contrats intelligents",
    t204: "Application - Produits écologiques diversifiés BeingDex",
    t205: "Wallet - Gérez vos actifs multi-chaînes",
    t206: "Le trading doit être effectué à tout moment et n'importe où",
    t207: "Téléchargez l'application et nous vous aiderons à trader 24h/24 et 7j/7",
    t208: "Scanner pour télécharger",
    t209: "Ressources médias",
    t210: "Conformité et politique",
    t211: "Certification officielle mondiale de conformité en matière de sécurité pour garantir la sécurité des actifs des utilisateurs",
    t212: "Obtenir la licence US MSB",
    t213: "28 novembre 2023",
    t214: "La demande de licence DMCC de Dubaï est en attente",
    t215: "Demande de licence auprès de la Hong Kong Securities Regulatory Commission/VARA/DIFC/ADGM/US MTL etc.",
    t216: "Nos partenaires",
    t217: "Plus de 15 ans d'expérience dans les technologies de l'information.<br>Architecte senior hautement qualifié en cloud computing/DevOps et applications avec une expérience dans les outils AWS, GCP, Azure et DevOps/SystemOps/DevOps et une compréhension approfondie des services.<br>8 + années d'expérience en tant qu'architecte Cloud/DevSecOps/Application dans le secteur financier<br>Conception du premier prototype de portefeuille matériel de crypto-monnaie au Canada pour ma startup Blockchain Mind.",
    t218: "Invitez des amis et gagnez jusqu'à<br>9 000 USDT",
    t219: "Lien d'invitation",
    t220: "Inviter maintenant",
    t221: "Inviter après connexion au portefeuille",
    t222: "Enregistrement d'invitation",
    t223: "Nom d'utilisateur",
    t224: "Heure d'enregistrement",
    t225: "La recharge atteint la norme",
    t226: "La transaction répond aux normes",
    t227: "Bonus de dépôt",
    t228: "Boîte aveugle",
    t229: "Événements populaires",
    t230: "Règles",
    t231: "1. Lorsqu'un ami invité termine la tâche de recharge, l'invitant recevra un coupon de réduction de 100 USDT. Une fois que l'ami invité a terminé la tâche de transaction, l'invitant peut tirer au hasard une récompense aveugle de 5 à 500 USDT. <br> 2. Tâche de recharge : dans les 30 jours suivant l'inscription de l'ami invité, rechargez via les canaux désignés et la recharge nette cumulée dépasse 50USDT. <br> 3. Tâche de trading : dans les 30 jours suivant l'inscription de l'ami invité, le volume cumulé des transactions au comptant ou sous contrat dépasse 200 USDT. <br>4. Les amis invités doivent terminer la tâche de recharge avant de pouvoir débloquer les récompenses de la tâche d'échange. Si votre ami invité ne réussit pas la tâche de recharge, vous ne pourrez pas obtenir la récompense même si la transaction dépasse 200USDT. <br> 5. Canaux de recharge désignés : la recharge valide est limitée à la recharge en chaîne, à la recharge en monnaie fiduciaire, aux achats par carte, aux transactions C2C et aux paiements tiers. Les virements internes et les enveloppes rouges ne sont pas inclus dans la recharge effective. 6. L'invitant peut recevoir chaque mois jusqu'à 15 coupons de déduction des frais de traitement et 15 récompenses en espèces de blind box. <br> 7. Période de validité : Le coupon de déduction des frais de traitement doit être collecté dans les 14 jours suivant son émission. La période d'utilisation valide après la collecte est de 14 jours. Veuillez faire attention à le recevoir et à l'utiliser à temps pour éviter l'expiration de la récompense. ; la période d'échange des récompenses de la boîte aveugle est valable 90 jours. Veuillez utiliser la récompense du coupon en espèces dès que possible après avoir reçu la récompense. Après l'échange, le coupon en espèces est valable 14 jours. <br> 8. Les invitations provenant de la même adresse IP ou du même appareil seront considérées comme des auto-invitations. L'auto-invitation entraînera la perte des récompenses déjà gagnées et de l'éligibilité aux récompenses futures. BeingDex se réserve le droit de geler les comptes illégaux et de confisquer les actifs des comptes. <br>9. Lorsque les récompenses seront distribuées, le système déterminera automatiquement si les deux parties actuelles ont le statut de partenaire exclusif. Si l'invitant ou l'invité est un partenaire exclusif, la récompense entrera en conflit avec la remise exclusive du partenaire et la récompense ne sera pas émise. De plus, les sous-comptes ne peuvent pas participer aux activités en tant que comptes indépendants et les données ne seront pas fusionnées dans le compte principal. <br> 10. Les règles ci-dessus entreront en vigueur à partir de 18h00 le 11 mai 2023 (UTC+8). BeingDex se réserve le droit d’interprétation finale de cette activité. BeingDex se réserve le droit de traiter les comptes d'utilisateurs et les actifs si un comportement malveillant ou un comportement illégal et contraire à l'éthique exploitant les vulnérabilités de la plateforme est découvert. <br> 11. Vous ne pouvez pas prétendre être officiel de BeingDex et faire des déclarations trompeuses, y compris, mais sans s'y limiter, acheter des mots-clés tels que 'BeingDex', 'BeingDex login', 'BeingDex official', 'BeingDex C2C', etc. sur les moteurs de recherche. Ceux qui enfreignent les exigences seront disqualifiés des récompenses et des promotions. ",
    t232: "Conformité et sécurité",
    t233: "BeingDex insiste sur la mise en œuvre d'un système complet de gouvernance de conformité et de sécurité et suit des normes et des processus stricts formulés par l'équipe consultative en matière de conformité pour garantir une gestion et une surveillance globales des risques.<br>La plateforme effectue régulièrement des évaluations complètes des risques pour identifier les risques potentiels. les points incluent le risque de marché et le risque opérationnel. Mettre en œuvre des stratégies efficaces de gestion des risques, suivre et identifier activement les risques internes et externes possibles et prendre les mesures de réponse appropriées. Pour les risques causés par des facteurs externes, BeingDex utilisera une technologie de cryptage avancée qui protège la sécurité des données. Pour les risques internes , établir un mécanisme de contrôle interne strict, y compris un mécanisme d'autorisation pour clarifier les responsabilités, et mener des audits internes et externes réguliers.<br>En se coordonnant régulièrement avec les agences de réglementation locales et en effectuant des examens de conformité, cela inclut les lois et réglementations externes nationales, en particulier celles concernant les services financiers, la protection des données et la lutte contre le blanchiment d'argent (AML), veillent à la conformité et à la sécurité des opérations de l'entreprise et veillent à ce que la plateforme soit conforme à toutes les réglementations et normes financières applicables.",
    t234: "Cadre de gestion de la conformité",
    t235: "Identification",
    t236: "Évaluation",
    t237: "Exécuter",
    t238: "évaluation",
    t239: "1. Gestion de la conformité",
    t240: " Sous la supervision d'une équipe d'experts en conformité, BeingDex suit des normes et protocoles de conformité stricts, met en œuvre une structure complète de gestion de la conformité et procède à une identification, une évaluation, une exécution et une évaluation efficaces.<br>BeingDex détecte et identifie activement les sources externes. et les risques internes et prendre les mesures correctives nécessaires. Les risques externes font référence aux risques qui peuvent être causés par des changements externes, tels que des informations erronées publiées par des publicités tierces des agents BeingDex.<br> Les risques internes font référence aux risques qui peuvent provenir de l'intérieur du Risques liés à l'organisation, tels qu'une conduite non autorisée, inappropriée, illégale ou contraire à l'éthique de la part des employés internes.<br>BeingDex travaille avec les régulateurs locaux par le biais d'une combinaison d'évaluations et d'examens de conformité annuels pour garantir que nos normes de conformité répondent aux exigences locales.",
    t241: "Technologie 2.eKYC",
    t242: " BeingDex adopte la vérification d'identité électronique (eKYC) pour sécuriser la plateforme et réduire les risques potentiels de fraude et d'illégalité. En plus de cela, BeingDex a mis en place des sanctions et des politiques de lutte contre le blanchiment d'argent (AML) pour se conformer à toutes les juridictions concernées, et empêcher la contrefaçon ou d'autres activités criminelles sur la plate-forme.<br>L'efficacité est cruciale pour la diligence raisonnable du client (CDD), par conséquent, BeingDex adopte la technologie eKYC pour optimiser le processus de vérification de l'identité de l'utilisateur (KYC) dans un souci de conformité.<br>Ceci La technologie permet la reconnaissance faciale et la correspondance automatique entre l'identification fournie par l'utilisateur et les portraits en temps réel, empêchant ainsi les fausses identités et réduisant également considérablement le temps nécessaire aux utilisateurs pour effectuer une vérification d'identité personnelle sur la plateforme BeingDex. ",
    t243: "2. Analyse de la blockchain",
    t244: " BeingDex déploie des outils externes d'analyse de blockchain pour surveiller de près les transactions sur la plateforme et réduire le risque d'activités frauduleuses et l'émergence d'utilisateurs à haut risque*. La nature immuable et transparente de la blockchain nous permet de détecter de manière exhaustive les transactions sur la plateforme. Toutes les transactions.<br>*Les utilisateurs à haut risque incluent, sans s'y limiter :<br>- Les clients situés dans des pays ou des régions sensibles<br>- Représentants gouvernementaux<br>- Les clients issus de secteurs sensibles (tels que les entreprises à forte intensité de capital) <br >Sur la base de l'évaluation de notre équipe de gestion des risques et de la gouvernance, nous prendrons diverses mesures contre les utilisateurs à haut risque, qui peuvent inclure la saisie d'actifs, de multiples examens ou audits, etc., en fonction de la situation spécifique.",
    t245: "3.Sécurité réseau",
    t246: "BeingDex consulte des experts indépendants en sécurité réseau pour améliorer la sécurité et la stabilité de la plate-forme. Dans le même temps, des tests d'intrusion du réseau et des évaluations de vulnérabilité sont effectués deux fois par an pour traiter rapidement les menaces potentielles détectées.<br>En plus de ' Après les tests ci-dessus, BeingDex crypte également toutes les données sensibles pour éviter les risques tels que le vol, l'accès ou la modification non autorisés. Toutes les données transférées ou enregistrées sont cryptées et stockées en toute sécurité dans un stockage tolérant aux pannes. ",
    t247: "Opération réussie",
    t248: "Tout lu",
    t249: "Citations",
    t250: "Changement d'aujourd'hui",
    t251: "Volume des transactions sur 24 H",
    t252: "Volume de transactions 24H",
    t253: "Monnaies populaires",
    t254: "Dernière devise",
    t255: "La monnaie avec la plus forte augmentation",
    t256: "Devise du volume de transactions le plus élevé",
    t257: "Des transactions plus rapides, de meilleurs actifs",
    t258: "Votre futur portefeuille de transactions Web3",
    t259: "Super portail de l'univers Web3",
    t260: " Rejoignez 12 millions d'utilisateurs, parcourez facilement le plus grand marché NFT et interagissez en toute sécurité avec plus de 20 000 DApps sur BeingDex Wallet ",
    t261: "Profitez de la plateforme NFT la plus complète et la plus simple à utiliser",
    t262: " Agrégation de plusieurs marchés NFT grand public, prise en charge du placement de commandes par lots en un clic et de l'achat de NFT dans n'importe quelle devise ",
    t263: "Achat",
    t264: "Laissez la blockchain se produire partout",
    t265: "Portefeuille multi-chaînes, sûr et facile à utiliser, entrée blockchain",
    t266: "Portefeuille open source",
    t267: "Portefeuille open source, clé privée autonome, cryptage multicouche",
    t268: "Suivez votre cœur et sentez-vous à l'aise",
    t269: " Demande inter-chaînes, pratique, décentralisée, à guichet unique ",
    t270: "Portefeuille décentralisé",
    t271: "Séparation des actifs chauds et froids, Token 40000+ sûr et pratique",
    t272: "Cryptoactifs",
    t273: "Plus de 40 000 actifs cryptographiques prennent en charge divers actifs à négocier sur DEX.",
    t274: "Technologie de cryptage multiple",
    t275: "Stockez la crypto-monnaie en toute sécurité et contrôlez vos propres actifs.",
    t276: "Mode gain multiple",
    t277: "Staking, minage, DeFi, jeux en chaîne.",
    t278: "Auto-garde des actifs, correspondance peer-to-peer des transactions de portefeuille",
    t279: "Sécurité sans accident et exécution purement intelligente des contrats",
    t280: "Graphique K-line décentralisé original, avantages natifs",
    t281: "Votre choix est le même que le leur",
    t282: "Confiance et choix de plus de 1 000 entreprises leaders",
    t283: "portefeuille plug-in",
    t284: "Tutoriel d'installation du plug-in",
    t285: " Le premier outil de gestion d'actifs numériques blockchain au monde ",
    t286: "Exécution pure de contrats intelligents",
    t287: "Télécharger maintenant",
    t288: " Entrée écologique DApp ",
    t289: "Explorez DeFi, GameFi, etc. et jouez rapidement avec l'économie DApp",
    t290: "Commençons ! Cliquez ici pour soumettre des suggestions ou des commentaires",
    t291: "Voir plus",
    t292: "Type de jeton",
    t293: "BeingDex, plateforme de négociation de gestion d'actifs à guichet unique pilotée par plusieurs chaînes<br>sûre, efficace et peu coûteuse",
    t294: "Pont inter-chaînes BeingDex",
    t295: "Français",
    t296: "Pas encore ouvert",
    t297: "fonctionner",
    t298: "portefeuille",
    t299: "Echanger",
    t300: "Dapp",
    t301: "Blog"
  }
}