export default {
  text: {
    t1: "Rumah",
    t2: "Bergabunglah dengan kami",
    t3: "Toko Google",
    t4: "Toko Apple",
    t5: "Unduh Aplikasi",
    t6: "Unduh Chrome",
    t7: "Unduhan lokal",
    t8: "harga mata uang BDX",
    t9: "Volume perdagangan",
    t10: "Pengguna Komunitas",
    t11: "Jumlah transaksi",
    t12: "Total volume transaksi BDX",
    t13: "Daftar Pertumbuhan",
    t14: "Daftar tolak",
    t15: "Daftar Koin Baru",
    t16: "Daftar Volume Transaksi",
    t17: "nama",
    t18: "Harga terbaru",
    t19: "harga",
    t20: "Peningkatan hari ini",
    t21: "Menambah atau mengurangi",
    t22: "Volume perdagangan 24 jam",
    t23: "Transaksi",
    t24: "Belum ada data",
    t25: "Lihat semua",
    t26: "Aman, efisien, biaya rendah",
    t27: "Layanan pelanggan online",
    t28: "Kerjasama Bisnis",
    t29: "Perusahaan",
    t30: "Tentang kami",
    t31: "Pusat Bantuan",
    t32: "Pengumuman",
    t33: "Token BDX",
    t34: "produk",
    t35: "Beli koin",
    t36: "Dompet Web3",
    t37: "Layanan",
    t38: "Umpan Balik",
    t39: "Permohonan untuk pencatatan mata uang",
    t40: "Undangan teman",
    t41: "Pengungkapan Hukum dan Risiko",
    t42: "Lisensi kepatuhan",
    t43: "Kebijakan Anti Pencucian Uang",
    t44: "Kebijakan Privasi",
    t45: "Perjanjian Pengguna",
    t46: "Pernyataan Hukum",
    t47: "Peringatan Resiko",
    t48: "aturan ST",
    t49: "dompet plug-in",
    t50: "Unduh dompet",
    t51: "Bahasa",
    t52: "Keluar",
    t53: "Hubungkan dompet",
    t54: "Memuat...",
    t55: "Tidak ada lagi...",
    t56: "Tentang MenjadiDex",
    t57: "Di belakang BeingDex terdapat sekelompok pengguna awal teknologi blockchain dan yang percaya pada pengembangan blockchain di masa depan.",
    t58: "Sejak tahun 2018, kami mendirikan bursa mata uang kripto dan berkomitmen untuk menyediakan solusi perdagangan terpadu yang aman untuk membantu pengguna melakukan perdagangan dengan lebih cerdas.",
    t59: "Platform perdagangan terdesentralisasi pending order pencocokan rantai penuh",
    t60: "Alamat terdaftar global",
    t61: "100.000+",
    t62: "30 juta USDT",
    t63: "Volume perdagangan harian",
    t64: "Kisah Kita",
    t65: 'Ini adalah sekelompok geek yang sangat percaya pada blockchain dan aset terenkripsi. Pada tahun 2010, kami membeli Bitcoin pertama kami melalui platform e-commerce OTC. Saat itu, kami merasa gugup dan gelisah. Seiring siklus industri perubahan, metode transaksi dan bentuk produk terus berinovasi dan berkembang, menghadirkan situasi di mana Cex dan Dex berkembang secara bersamaan. Namun, kami juga menyadari bahwa Dex yang ada tunduk pada mekanisme modelnya dan tidak dapat memaksimalkan efisiensi aset.<br >Pada saat yang sama Saat ini, seiring dengan semakin luas dan mendalamnya pengaruh industri enkripsi pada skala global, selain wilayah maju, semakin banyak orang dari wilayah dengan infrastruktur keuangan yang lemah mulai bergabung, namun mereka mengalami kesulitan dalam memahami produk keuangan yang kompleks dan mekanisme algoritmik. . , hal ini telah menjadi celah yang menghalangi mereka untuk menghubungkan dunia baru dan aset baru.<br>BeingDex berkomitmen untuk mengatasi kesenjangan ini dan membangun produk aplikasi dan ekologi rantai penuh melalui kontrak pintar baru.<br>Being memiliki "eksistensi " Konotasi seperti "esensi" dan "kehidupan biologis" mengekspresikan semangat kami dalam mengeksplorasi asal usul sesuatu, praktik dasar kami dalam nilai produk, dan upaya utama kami dalam mencapai pengalaman pengguna. Kami mendorong diri kami sendiri dan menyambut lebih banyak orang untuk membuka pikiran dan merangkul enkripsi aset, dan membantu mereka memulai perjalanan kekayaan kripto mereka sendiri melalui layanan produk yang mudah digunakan dan ramah.',
    t66: "Visi",
    t67: "Ciptakan dunia kekayaan masa depan yang lebih bebas, adil, dan transparan melalui Web3",
    t68: "Misi",
    t69: "Menciptakan platform perdagangan terbaik yang dapat digunakan semua orang dan menjadi penyedia layanan keuangan aset digital terkemuka di industri",
    t70: "Nilai-nilai kita",
    t71: "Pengguna terlebih dahulu",
    t72: "Perhatikan kebutuhan dan sikap setiap pengguna, komunikasikan secara objektif dan jujur, dan rilis informasi platform pada waktu yang tepat.",
    t73: "Integritas dan ketelitian",
    t74: 'Kami menganut prinsip" jangan berbuat jahat "dan memenangkan kepercayaan pasar dan pengguna melalui tanggung jawab dan tanggung jawab.',
    t75: "Inovasi dan giat",
    t76: "Produk dan layanan ekstrem serta membangun keunggulan struktural adalah upaya abadi kami.",
    t77: "Mulailah dengan tujuan akhir",
    t78: "Lakukan hal-hal jangka panjang dengan mitra jangka panjang, pahami prosesnya, ciptakan kondisi, perhatikan hasil umpan balik, dan terus capai tujuan pencapaian.",
    t79: "Tim kami",
    t80: "Dengan lebih dari 150 karyawan dari lebih dari 10 negara, tim BeingDEX memiliki talenta senior dari seluruh penjuru dunia, memberi kami jangkauan global yang sesungguhnya.",
    t81: "Layanan Kami",
    t82: "MenjadiDEX",
    t83: "BeingDex adalah pertukaran terdesentralisasi baru berdasarkan pengembangan multi-rantai. Ini mengadopsi model pencocokan pesanan on-chain dan jembatan lintas rantai mendukung rantai publik BSC, TRON, dan OKX.",
    t84: "Menjadi Dompet",
    t85: "Being Wallet mengadopsi dua mekanisme keamanan utama: hak asuh sendiri atas aset pengguna dan anonimitas lengkap. Teknologi dompet yang mendasarinya mendukung berbagai perlindungan keamanan seperti enkripsi biometrik lokal dan isolasi keamanan, dan mendukung manajemen aset multi-rantai untuk melindungi keamanan pengguna transaksi.",
    t86: "Menjadi NFT",
    t87: "Menjadi NFT mendukung penerbitan NFT sekali klik multi-rantai ETH, BSC, Mango, TRON, Polygon, Solana, transaksi dan aktivitas lainnya diselesaikan melalui protokol rantai tanpa intervensi pihak ketiga. NFT yang diselenggarakan oleh DAO adalah disimpan di dompet. Pengecoran on-chain, transaksi cerdas, aman dan nyaman.",
    t88: "Mulailah perjalanan kripto Anda sekarang!",
    t89: "Berdaganglah di platform yang dipercaya oleh jutaan pengguna.",
    t90: "Upload berhasil",
    t91: "Upload gagal",
    t92: "Silakan pilih rantai publik tempat Anda berada",
    t93: "Silakan masukkan nama proyek",
    t94: "Silakan unggah logo",
    t95: "Silakan masukkan singkatan tokennya",
    t96: "Silakan masukkan alamat kontrak",
    t97: "Silakan masukkan jumlah penerbitan",
    t98: "Silahkan masukkan link website resminya",
    t99: "Silakan masukkan alamat email anda",
    t100: "Silahkan masukkan informasi token anda",
    t101: "Pengajuan berhasil",
    t102: "Aplikasi pencatatan mata uang BeingDex",
    t103: "Terima kasih atas perhatian Anda pada BeingDex Exchange. Silakan isi formulir aplikasi dan berikan informasi yang valid. Kami akan meninjau proyek Anda berdasarkan informasi yang Anda berikan. Silakan kirimkan aplikasi ini dan proyek Anda akan dikirim ke departemen pencatatan mata uang . Tinjauan. Setelah Anda lulus tinjauan awal, kami akan mengatur spesialis pencatatan mata uang untuk berbagi proses dan teknik pencatatan mata uang dengan Anda dan memandu Anda melalui proses pencatatan mata uang.",
    t104: "Menunjukkan diperlukan",
    t105: "Rantai publik yang memilikinya",
    t106: "Nama proyek",
    t107: "Singkatan token",
    t108: "Alamat kontrak",
    t109: "Jumlah penerbitan",
    t110: "Tautan situs resmi",
    t111: "Kotak Surat",
    t112: "Informasi token",
    t113: "Silakan masukkan informasi token Anda, tidak lebih dari 120 karakter",
    t114: "Kirim",
    t115: "Kirim setelah terhubung ke dompet",
    t116: "Hapus isi formulir",
    t117: "BDX memimpin revolusi dalam industri kripto",
    t118: "Hubungkan aset Anda, aplikasi DeFi, dan NFT untuk membantu Anda membuka dunia Web3 dengan cepat",
    t119: "Dapatkan BDX dengan satu klik",
    t120: "Buku Putih BDX",
    t121: "Pengantar BDX",
    t122: "Pegang BDX dan nikmati keuntungan tanpa akhir",
    t123: "Langganan baru",
    t124: "Layanan istimewa",
    t125: "Mekanisme deflasi",
    t126: "Baru daring",
    t127: "Perencanaan",
    t128: "Dapatkan BDX",
    t129: "Informasi rilis BDX",
    t130: "Aman, mudah digunakan, dan berhubungan erat dengan budaya dan ideologi di seluruh dunia",
    t131: "Nama token",
    t132: "Simbol tanda",
    t133: "Memiliki rantai",
    t134: "Alamat kontrak",
    t135: "Keluarkan harga",
    t136: "Pasokan sirkulasi",
    t137: "Total persediaan",
    t138: "Tanggal penerbitan",
    t139: "Ganti BDX",
    t140: "Untuk penukaran token BDX yang ada",
    t141: "Motivasi Tim",
    t142: "2% terbuka setiap 6 bulan, akan terbuka sepenuhnya dalam 5 tahun (60 bulan)",
    t143: "Investasi ekonomi dan ekologi",
    t144: "Buka ekosistem BeingDex untuk investasi dana",
    t145: "Promosi Merek",
    t146: "Rilis maksimum per tahun",
    t147: "Masukan pengguna",
    t148: "Dana Perlindungan",
    t149: "Untuk kompensasi atas potensi kecelakaan di peron",
    t150: "Bekerja sama dengan kami untuk menciptakan ekosistem BDX yang aman dan andal serta mendorong perkembangan pesat Web3",
    t151: "Dapatkan BDX dengan satu klik",
    t152: "Direkomendasikan",
    t153: "Blog Terbaru",
    t154: "Belum ada datanya",
    t155: "Toko Aplikasi DApp",
    t156: "Cari",
    t157: "Pilih kategori",
    t158: "Penafian Penting",
    t159: 'Semua konten yang disediakan di situs web ini, situs web hyperlink, aplikasi terkait, forum, blog, akun media sosial, dan platform lainnya ("Situs") adalah untuk informasi umum Anda yang diperoleh dari sumber pihak ketiga saja. Kami tidak bertanggung jawab atas konten Tidak ada jaminan dalam bentuk apa pun, termasuk namun tidak terbatas pada keakuratan dan kemutakhiran. Tidak ada bagian dari konten yang kami sediakan yang merupakan nasihat keuangan, nasihat hukum, atau bentuk nasihat lainnya dan dirancang untuk memuaskan ketergantungan spesifik Anda untuk tujuan apa pun. Segala penggunaan atau ketergantungan pada konten kami dilakukan atas risiko dan kebijaksanaan Anda sendiri. Anda harus melakukan penelitian, peninjauan, analisis, dan verifikasi sendiri sebelum mengandalkan konten kami. Perdagangan adalah aktivitas berisiko tinggi yang dapat mengakibatkan kerugian besar, jadi silakan berkonsultasi dengan penasihat keuangan Anda sebelum mengambil keputusan apa pun. Tidak ada apa pun di situs web kami yang merupakan ajakan atau penawaran.',
    t160: "Silakan masukkan rincian saran",
    t161: "Pengajuan berhasil",
    t162: "Setiap saranmu",
    t163: "Kami akan mendengarkan baik-baik dan menyikapinya dengan serius",
    t164: "Umpan Balik",
    t165: "Jika Anda menemukan kelemahan atau kerentanan keamanan, tolong beri kami umpan balik tepat waktu",
    t166: "Jika Anda mempunyai pertanyaan, silakan berkonsultasi dengan Pusat Bantuan untuk mendapatkan jawaban atas pertanyaan umum.",
    t167: "Apa pendapat Anda tentang pengalaman produk kami?",
    t168: "Bukan pengalaman yang bagus!",
    t169: "Untuk ditingkatkan!",
    t170: "Cukup memuaskan!",
    t171: "Sangat hebat!",
    t172: "Kirim saran",
    t173: "Selamat datang untuk membagikan saran produk Anda. BeingDex akan menanggapi masukan Anda dengan serius. Jika Anda memiliki pertanyaan mendesak, silakan hubungi layanan pelanggan.",
    t174: "Kategori yang disarankan",
    t175: "Rekomendasi keselamatan",
    t176: "Saran Fitur",
    t177: "Saran Desain",
    t178: "Saran Operasi",
    t179: "Saran lainnya",
    t180: "Detail saran",
    t181: "Silakan masukkan tanggapan Anda, tidak lebih dari 500 karakter",
    t182: "Unggah gambar (opsional)",
    t183: "Silakan unggah screenshot terkait masalah tersebut. Format gambarnya adalah JPG atau PNG, dan ukurannya tidak boleh lebih dari 2M",
    t184: "Informasi kontak (opsional)",
    t185: "Silakan masukkan informasi kontak",
    t186: "Konfirmasi penyerahan",
    t187: "Kirim setelah terhubung ke dompet",
    t188: "Simpan draf",
    t189: "Bagaimana cara kerjanya?",
    t190: "Kirim saran",
    t191: "Ulasan tim",
    t192: "Bagikan hadiah",
    t193: "BeingDex melayani pengguna di seluruh dunia. Kami menganggap pengembangan platform yang aman dan stabil sebagai prioritas utama kami. Kami menantikan saran berharga Anda. Mari tingkatkan kualitas produk dan ciptakan masa depan yang lebih baik bersama-sama.",
    t194: "Protokol yang dapat dipercaya oleh pengguna Web3<br>memungkinkan pengguna Defi menyelesaikan transaksi dengan mudah",
    t195: "Penitipan aset sendiri, transaksi pencocokan dompet point-to-point",
    t196: "Keamanan tanpa kecelakaan dan eksekusi kontrak cerdas murni",
    t197: "Grafik K-line terdesentralisasi asli, keunggulan asli",
    t198: "Mata Uang Kripto Populer",
    t199: "Menjadi Ekologi Dex",
    t200: "Kelola aset Anda dengan mudah",
    t201: "BeingDex adalah platform perdagangan terdesentralisasi yang cocok dengan buku pesanan yang dibangun dengan kontrak pintar murni. Tata letak ekologi keseluruhan mencakup Kripto, Dompet, DEX, DeFi, GameFi, DAO, NFT, kumpulan penambangan, dan industri lainnya.",
    t202: "Produk terdesentralisasi yang mengintegrasikan dompet dan transaksi",
    t203: "BeingDex - platform perdagangan terdesentralisasi pencocokan pesanan yang dibangun dengan kontrak pintar murni",
    t204: "Aplikasi - BeingDex mendiversifikasi produk ekologi",
    t205: "Dompet - Kelola aset multi-rantai Anda",
    t206: "Trading harus dilakukan kapanpun dan dimanapun",
    t207: "Unduh Aplikasinya dan kami akan membantu Anda berdagang 24/7",
    t208: "Pindai untuk mengunduh",
    t209: "Sumber Daya Media",
    t210: "Kepatuhan dan Kebijakan",
    t211: "Sertifikasi resmi global atas kepatuhan keamanan untuk memastikan keamanan aset pengguna",
    t212: "Dapatkan lisensi MSB AS",
    t213: "28 November 2023",
    t214: "Permohonan lisensi DMCC Dubai tertunda",
    t215: "Permohonan lisensi dari Hong Kong Securities Regulatory Commission/VARA/DIFC/ADGM/US MTL dll.",
    t216: "Mitra kami",
    t217: "15+ tahun pengalaman dalam teknologi informasi.<br>Komputasi awan/DevOps senior yang sangat terampil dan arsitek aplikasi dengan pengalaman dalam alat AWS, GCP, Azure dan DevOps/SystemOps/DevOps serta pemahaman layanan yang luas.<br>8 + pengalaman bertahun-tahun bekerja sebagai Cloud/DevSecOps/Arsitek Aplikasi di sektor keuangan<br>Merancang prototipe dompet perangkat keras mata uang kripto pertama di Kanada untuk startup saya, Blockchain Mind.",
    t218: "Undang teman dan menangkan hingga<br>9.000 USDT",
    t219: "Tautan undangan",
    t220: "Undang sekarang",
    t221: "Undang setelah terhubung ke dompet",
    t222: "Catatan undangan",
    t223: "Nama Pengguna",
    t224: "Waktu pendaftaran",
    t225: "Isi ulang mencapai standar",
    t226: "Transaksi memenuhi standar",
    t227: "Bonus setoran",
    t228: "Kotak buta",
    t229: "Acara Populer",
    t230: "Aturan",
    t231: '1. Ketika teman yang diundang menyelesaikan tugas isi ulang, pengundang bisa mendapatkan kupon diskon 100 USDT. Setelah teman yang diundang menyelesaikan tugas transaksi, pengundang dapat secara acak mengambil hadiah kotak buta sebesar 5-500 USDT.<br > 2. Tugas isi ulang: Dalam waktu 30 hari setelah teman yang diundang mendaftar, isi ulang melalui saluran yang ditentukan dan setoran bersih kumulatif melebihi 50USDT.<br> 3. Tugas perdagangan: Dalam waktu 30 hari setelah teman yang diundang mendaftar, transaksi spot atau kontrak kumulatif volume melebihi 200USDT. <br>4. Teman yang diundang harus menyelesaikan tugas isi ulang sebelum Anda dapat membuka hadiah tugas perdagangan. Jika teman yang Anda undang tidak berhasil menyelesaikan tugas isi ulang, Anda tidak akan dapat memperoleh hadiah meskipun telah melakukan transaksi melebihi 200USDT.<br> 5. Saluran isi ulang yang ditunjuk: Isi ulang yang valid Hanya isi ulang on-chain, isi ulang mata uang legal, pembelian kartu, transaksi C2C, dan pembayaran pihak ketiga yang diperbolehkan. Transfer internal dan amplop merah tidak termasuk dalam isi ulang efektif. 6. Pengundang dapat menerima hingga 15 kupon potongan biaya dan 15 uang tunai per bulan Hadiah kotak buta.<br> 7. Masa berlaku: Kupon potongan biaya penanganan harus diambil dalam waktu 14 hari setelah diterbitkan, dan berlaku selama 14 hari setelah pengambilan. Harap perhatikan untuk menerima dan menggunakannya tepat waktu untuk menghindari kedaluwarsa hadiah; masa berlaku penukaran hadiah blind box adalah 90 hari. Harap tukarkan hadiah kupon tunai sesegera mungkin setelah menerima hadiah. Kupon tunai berlaku selama 14 hari setelah penukaran.<br> 8. Undangan dari alamat IP atau perangkat yang sama akan dianggap sebagai undangan mandiri. Undangan mandiri akan menyebabkan pengguna kehilangan hadiah yang diperoleh dan kualifikasi untuk menerima hadiah di masa mendatang. BeingDex mencadangkan hak untuk membekukan akun ilegal dan menyita aset di akun tersebut.<br>9. Ketika hadiah diberikan, sistem akan secara otomatis menentukan apakah kedua pihak saat ini memiliki status mitra eksklusif. Jika pengundang atau salah satu dari yang diundang adalah mitra eksklusif, hadiah akan bertentangan dengan hadiah rabat mitra eksklusif, dan hadiah tidak akan diberikan. Selain itu, sub-akun tidak dapat berpartisipasi dalam aktivitas sebagai akun independen, dan data tidak akan digabungkan ke dalam akun utama.<br > 10. Aturan di atas akan berlaku mulai pukul 18:00 tanggal 11 Mei 2023 (UTC+8). BeingDex berhak interpretasi akhir atas aktivitas ini. Jika ditemukan perilaku berbahaya atau perilaku ilegal dan tidak etis yang mengeksploitasi kerentanan platform , BeingDex berhak menangani akun dan aset pengguna.<br> 11. Anda tidak boleh berpura-pura menjadi pejabat BeingDex dan membuat pernyataan yang menyesatkan, termasuk namun tidak terbatas pada membeli kata kunci seperti "BeingDex", "Login BeingDex", " BeingDex Official", "BeingDex C2C" Promosikan di mesin pencari. Mereka yang melanggar persyaratan akan didiskualifikasi dari hadiah dan promosi.',
    t232: "Kepatuhan dan Keamanan",
    t233: "BeingDex bersikeras menerapkan sistem tata kelola kepatuhan dan keamanan yang komprehensif serta mengikuti standar dan proses ketat yang dirumuskan oleh tim penasihat kepatuhan untuk memastikan manajemen dan pemantauan risiko menyeluruh.<br>Platform ini secara rutin melakukan penilaian risiko komprehensif untuk mengidentifikasi Potensi risiko poinnya mencakup risiko pasar dan risiko operasional. Menerapkan strategi manajemen risiko yang efektif, secara aktif melacak dan mengidentifikasi kemungkinan risiko internal dan eksternal, dan mengambil tindakan respons yang tepat. Untuk risiko yang disebabkan oleh faktor eksternal, BeingDex akan menggunakan enkripsi canggih Teknologi melindungi keamanan data. Untuk risiko internal , menetapkan mekanisme pengendalian internal yang ketat, termasuk mekanisme otorisasi untuk memperjelas tanggung jawab, dan melakukan audit internal dan eksternal secara berkala.<br>Dengan berkoordinasi secara teratur dengan badan pengatur setempat dan melakukan tinjauan kepatuhan, hal ini mencakup undang-undang dan peraturan eksternal dalam negeri, terutama yang berkaitan dengan layanan keuangan, perlindungan data dan anti pencucian uang (AML), memastikan kepatuhan dan keamanan operasi perusahaan dan memastikan bahwa platform mematuhi semua peraturan dan standar keuangan yang berlaku.",
    t234: "Kerangka Manajemen Kepatuhan",
    t235: "Identifikasi",
    t236: "Evaluasi",
    t237: "Jalankan",
    t238: "evaluasi",
    t239: "1. Manajemen kepatuhan",
    t240: "Di bawah pengawasan tim ahli kepatuhan, BeingDex mengikuti standar dan protokol kepatuhan yang ketat, menerapkan struktur manajemen kepatuhan yang komprehensif, dan melakukan identifikasi, penilaian, pelaksanaan, dan evaluasi yang efektif.<br>BeingDex secara aktif mendeteksi dan mengidentifikasi sumber dari Eksternal dan risiko internal serta mengambil tindakan perbaikan yang diperlukan. Risiko eksternal mengacu pada risiko yang mungkin disebabkan oleh perubahan eksternal, seperti informasi yang salah yang dipublikasikan oleh iklan pihak ketiga dari agen BeingDex.<br> Risiko internal mengacu pada risiko yang mungkin berasal dari dalam Risiko organisasi, seperti perilaku karyawan internal yang tidak sah, tidak pantas, ilegal, atau tidak etis.<br>BeingDex bekerja sama dengan regulator lokal melalui kombinasi penilaian dan tinjauan kepatuhan tahunan untuk memastikan bahwa standar kepatuhan kami memenuhi persyaratan lokal.",
    t241: "teknologi 2.eKYC",
    t242: "BeingDex mengadopsi verifikasi identitas elektronik (eKYC) untuk mengamankan platform dan mengurangi potensi penipuan dan risiko ilegal. Selain itu, BeingDex menerapkan kebijakan sanksi dan anti pencucian uang (AML) untuk mematuhi semua yurisdiksi terkait, dan mencegah pemalsuan atau aktivitas kriminal lainnya di platform.<br>Efisiensi sangat penting untuk Uji Tuntas Pelanggan (CDD), oleh karena itu, BeingDex mengadopsi teknologi eKYC untuk mengoptimalkan proses verifikasi identitas pengguna (KYC) berdasarkan premis kepatuhan.<br>Ini teknologi memungkinkan pengenalan wajah dan pencocokan silang otomatis antara identifikasi yang diberikan pengguna dan potret waktu nyata, sehingga mencegah identitas palsu dan juga sangat mempersingkat waktu bagi pengguna untuk melakukan verifikasi identitas pribadi di platform BeingDex.",
    t243: "2. Analisis Blockchain",
    t244: "BeingDex menerapkan alat analisis blockchain eksternal untuk memonitor transaksi di platform dengan cermat dan mengurangi risiko aktivitas penipuan dan munculnya pengguna berisiko tinggi*. Sifat blockchain yang tidak dapat diubah dan transparan memungkinkan kami mendeteksi transaksi di platform secara komprehensif Semua transaksi.<br>*Pengguna berisiko tinggi termasuk namun tidak terbatas pada:<br>- Pelanggan di negara atau wilayah sensitif<br>- Pejabat pemerintah<br>- Pelanggan dari industri sensitif (seperti bisnis padat modal) <br >Berdasarkan penilaian tim risiko dan tata kelola kami, kami akan mengambil berbagai tindakan terhadap pengguna berisiko tinggi, yang mungkin mencakup penyitaan aset, peninjauan atau audit berulang kali, dll., tergantung pada situasi spesifik.",
    t245: "3.Keamanan jaringan",
    t246: "BeingDex berkonsultasi dengan pakar keamanan jaringan independen untuk meningkatkan keamanan dan stabilitas platform. Pada saat yang sama, pengujian penetrasi jaringan dan penilaian kerentanan dilakukan dua kali setahun untuk menangani potensi ancaman yang terdeteksi dengan cepat dan cepat.<br>Selain itu pengujian di atas, BeingDex juga mengenkripsi semua data sensitif untuk mencegah risiko seperti pencurian, akses tidak sah, atau modifikasi. Semua data yang ditransfer atau disimpan dienkripsi dan disimpan dengan aman di penyimpanan yang toleran terhadap kesalahan.",
    t247: "Operasi berhasil",
    t248: "Semua sudah dibaca",
    t249: "Kutipan",
    t250: "Perubahan hari ini",
    t251: "Volume perdagangan 24 jam",
    t252: "Volume transaksi 24 jam",
    t253: "Mata uang populer",
    t254: "Mata uang terbaru",
    t255: "Mata uang dengan kenaikan terbesar",
    t256: "Mata uang dengan volume perdagangan tertinggi",
    t257: "Transaksi lebih cepat, aset lebih baik",
    t258: "Dompet transaksi Web3 masa depan Anda",
    t259: "Portal super alam semesta Web3",
    t260: "Bergabunglah dengan 12 juta pengguna, jelajahi pasar NFT terbesar dengan mudah dan berinteraksi secara aman dengan 20.000+ DApps di BeingDex Wallet",
    t261: "Nikmati platform NFT terlengkap dan mudah digunakan",
    t262: "Menggabungkan beberapa pasar NFT arus utama, mendukung penempatan pesanan batch sekali klik, dan pembelian NFT dalam mata uang apa pun",
    t263: "Pembelian",
    t264: "Biarkan blockchain terjadi di mana saja",
    t265: "Dompet multi-rantai, aman dan mudah digunakan, pintu masuk blockchain",
    t266: "Dompet sumber terbuka",
    t267: "Dompet sumber terbuka, kunci pribadi mandiri, enkripsi multi-lapis",
    t268: "Ikuti kata hatimu dan merasa nyaman",
    t269: "Permintaan lintas rantai, nyaman, terdesentralisasi, satu atap",
    t270: "Dompet terdesentralisasi",
    t271: "Pemisahan aset panas dan dingin, Token 40000+ yang aman dan nyaman",
    t272: "Aset Kripto",
    t273: "Aset kripto 40.000+ mendukung berbagai aset untuk diperdagangkan di DEX.",
    t274: "Teknologi enkripsi ganda",
    t275: "Simpan mata uang kripto dengan aman dan kendalikan aset Anda sendiri.",
    t276: "Mode penguatan ganda",
    t277: "Staking, mining, DeFi, permainan berantai.",
    t278: "Aset hak asuh sendiri, pencocokan transaksi dompet peer-to-peer",
    t279: "Keamanan tanpa kecelakaan dan eksekusi kontrak cerdas murni",
    t280: "Grafik K-line terdesentralisasi asli, keunggulan asli",
    t281: "Pilihanmu sama dengan pilihan mereka",
    t282: "Kepercayaan dan pilihan 1.000+ perusahaan terkemuka",
    t283: "dompet plug-in",
    t284: "Tutorial instalasi plugin",
    t285: "Alat manajemen aset digital blockchain terkemuka di dunia",
    t286: "Eksekusi kontrak cerdas murni",
    t287: "Unduh sekarang",
    t288: "Pintu Masuk Ekologis DApp",
    t289: "Jelajahi DeFi, GameFi, dll., dan mainkan ekonomi DApp dengan cepat",
    t290: "Mari kita mulai! Klik di sini untuk menyampaikan saran atau masukan",
    t291: "Lihat lebih lanjut",
    t292: "Jenis token",
    t293: "MenjadiDex, berbasis multi-rantai<br>platform perdagangan manajemen aset terpadu<br>aman, efisien, dan berbiaya rendah",
    t294: "Jembatan lintas rantai BeingDex",
    t295: "bahasa Indonesia",
    t296: "Belum dibuka",
    t297: "beroperasi",
    t298: "dompet",
    t299: "Tukar",
    t300: "Dap",
    t301: "Blognya"
  }
}