export default {
  text: {
    t1: "Casa",
    t2: "Unisciti a noi",
    t3: "Google Store",
    t4: "Apple Store",
    t5: "Scarica l'app",
    t6: "Scarica Chrome",
    t7: "Download locale",
    t8: "Prezzo valuta BDX",
    t9: "Volume degli scambi",
    t10: "Utente della comunità",
    t11: "Numero di transazioni",
    t12: "Volume totale delle transazioni BDX",
    t13: "Elenco crescita",
    t14: "Lista rifiutata",
    t15: "Nuova lista monete",
    t16: "Elenco volumi di transazioni",
    t17: "nome",
    t18: "Ultimo prezzo",
    t19: "prezzo",
    t20: "Aumento di oggi",
    t21: "Aumenta o diminuisce",
    t22: "Volume degli scambi nelle 24 ore",
    t23: "Transazione",
    t24: "Ancora nessun dato",
    t25: "Visualizza tutto",
    t26: "Sicuro, efficiente, a basso costo",
    t27: "Servizio clienti online",
    t28: "Cooperazione commerciale",
    t29: "Azienda",
    t30: "Chi siamo",
    t31: "Centro assistenza",
    t32: "Annuncio",
    t33: "Token BDX",
    t34: "prodotto",
    t35: "Acquista monete",
    t36: "Portafoglio Web3",
    t37: "Servizio",
    t38: "Risposta",
    t39: "Richiesta di quotazione valutaria",
    t40: "Invito amico",
    t41: "Informativa legale e sui rischi",
    t42: "Licenza di conformità",
    t43: "Politica antiriciclaggio",
    t44: "Informativa sulla privacy",
    t45: "Accordo con l'utente",
    t46: "Dichiarazione legale",
    t47: "Avviso di rischio",
    t48: "Regola ST",
    t49: "portafoglio plug-in",
    t50: "Scarica portafoglio",
    t51: "Lingua",
    t52: "Esci",
    t53: "Connetti portafoglio",
    t54: "Caricamento in corso...",
    t55: "Non più...",
    t56: "Informazioni su BeingDex",
    t57: "Dietro BeingDex c'è un gruppo di primi ad adottare la tecnologia blockchain e credenti nel futuro sviluppo della blockchain.",
    t58: "Dal 2018, abbiamo creato uno scambio di criptovalute e ci siamo impegnati a fornire soluzioni di trading sicure e complete per aiutare gli utenti a fare trading in modo più intelligente.",
    t59: "Ordini pendenti dell'intera catena che corrispondono alla piattaforma di trading decentralizzata",
    t60: "Indirizzo registrato globale",
    t61: "100.000+",
    t62: "30 milioni di USDT",
    t63: "Volume degli scambi giornalieri",
    t64: "La nostra storia",
    t65: "Questo è un gruppo di geek che credono fermamente nella blockchain e negli asset crittografati. Nel 2010, abbiamo acquistato il nostro primo Bitcoin attraverso una piattaforma di e-commerce OTC. A quel tempo eravamo nervosi e a disagio. Mentre il ciclo industriale i cambiamenti, i metodi di transazione e le forme dei prodotti continuano a innovarsi ed evolversi, presentando una situazione in cui Cex e Dex si sviluppano simultaneamente. Tuttavia, ci rendiamo anche conto che il Dex esistente è soggetto al suo meccanismo modello e non può massimizzare l'efficienza degli asset.<br >Allo stesso tempo tempo, poiché l’industria della crittografia ha un’influenza sempre più ampia e profonda su scala globale, oltre alle aree sviluppate, sempre più persone provenienti da aree con infrastrutture finanziarie deboli stanno cominciando ad aderire, ma hanno difficoltà a comprendere prodotti finanziari complessi e meccanismi algoritmici . , questo è diventato un divario che impedisce loro di connettere il nuovo mondo e le nuove risorse.<br>BeingDex si impegna a colmare questo divario e a costruire prodotti applicativi a catena completa ed ecologia attraverso nuovi contratti intelligenti.<br>Essere ha 'esistenza' 'Connotazioni come'  'essenza' e 'vita biologica' esprimono il nostro spirito di esplorazione dell'origine delle cose, la nostra pratica fondamentale del valore del prodotto e la nostra ricerca finale dell'esperienza dell'utente. Incoraggiamo noi stessi e diamo il benvenuto a più persone ad aprire le loro menti e abbracciare le risorse crittografiche e aiutarli a iniziare il proprio viaggio verso la ricchezza criptata attraverso servizi di prodotti facili da usare e intuitivi.",
    t66: "Visione",
    t67: "Creare un futuro mondo di ricchezza più libero, più giusto e più trasparente attraverso il Web3",
    t68: "Missione",
    t69: "Creare la piattaforma di trading definitiva che tutti possano utilizzare e diventare il principale fornitore di servizi finanziari per asset digitali nel settore",
    t70: "I nostri valori",
    t71: "Prima l'utente",
    t72: "Prestare attenzione alle esigenze e agli atteggiamenti di ciascun utente, comunicare in modo obiettivo e sincero e rilasciare le informazioni sulla piattaforma in modo tempestivo.",
    t73: "Integrità e rigore",
    t74: 'Aderiamo al principio "non fare il male" e conquistiamo la fiducia del mercato e degli utenti attraverso responsabilità e responsabilità.',
    t75: "Innovazione e intraprendenza",
    t76: "Prodotti e servizi estremi e vantaggi strutturali dell'edificio sono la nostra ricerca eterna.",
    t77: "Inizia con la fine in mente",
    t78: "Fai cose a lungo termine con partner a lungo termine, afferra il processo, crea condizioni, presta attenzione ai risultati del feedback e raggiungi continuamente obiettivi fondamentali.",
    t79: "La nostra squadra",
    t80: "Con oltre 150 dipendenti provenienti da più di 10 paesi, il team di BeingDEX vanta talenti senior provenienti da ogni angolo del pianeta, dandoci una portata veramente globale.",
    t81: "I nostri servizi",
    t82: "EssereDEX",
    t83: "BeingDex è un nuovo scambio decentralizzato basato sullo sviluppo multi-catena. Adotta un modello di corrispondenza degli ordini su catena e il ponte cross-chain supporta le catene pubbliche BSC, TRON e OKX.",
    t84: "Essere portafoglio",
    t85: "Being Wallet adotta due principali meccanismi di sicurezza: autocustodia delle risorse dell'utente e completo anonimato. La sua tecnologia di portafoglio sottostante supporta molteplici protezioni di sicurezza come la crittografia biometrica locale e l'isolamento di sicurezza e supporta la gestione delle risorse multi-catena per proteggere la sicurezza degli utenti transazioni.",
    t86: "Essere NFT",
    t87: "Essendo NFT supporta ETH, BSC, Mango, TRON, Polygon, Solana emissione multi-catena con un clic di NFT, le transazioni e altre attività vengono completate attraverso il protocollo della catena senza intervento di terze parti. L'NFT organizzato dal DAO è archiviato nel portafoglio. Cast on-chain, transazioni intelligenti, sicure e convenienti.",
    t88: "Inizia il tuo viaggio nel mondo delle criptovalute adesso!",
    t89: "Fai trading su una piattaforma considerata affidabile da milioni di utenti.",
    t90: "Caricamento riuscito",
    t91: "Caricamento fallito",
    t92: "Seleziona la catena pubblica a cui appartieni",
    t93: "Inserisci il nome del progetto",
    t94: "Carica il logo",
    t95: "Inserisci l'abbreviazione del token",
    t96: "Inserisci l'indirizzo del contratto",
    t97: "Inserisci la quantità di emissione",
    t98: "Inserisci il link al sito ufficiale",
    t99: "Inserisci il tuo indirizzo email",
    t100: "Inserisci le informazioni sul token",
    t101: "Invio riuscito",
    t102: "Applicazione di quotazione valuta BeingDex",
    t103: "Grazie per l'attenzione a BeingDex Exchange. Compila il modulo di domanda e fornisci informazioni valide. Esamineremo il tuo progetto in base alle informazioni fornite. Ti preghiamo di inviare questa domanda e il tuo progetto verrà inviato al dipartimento di quotazione valutaria Revisione. Dopo aver superato la revisione preliminare, provvederemo a far sì che uno specialista di quotazione delle valute condivida con te il processo e le tecniche di quotazione delle valute e ti guidi attraverso il processo di quotazione delle valute.",
    t104: "Indica obbligatorio",
    t105: "Catena pubblica a cui appartiene",
    t106: "Nome progetto",
    t107: "Abbreviazione del token",
    t108: "Indirizzo del contratto",
    t109: "Quantità di emissione",
    t110: "Link al sito ufficiale",
    t111: "Cassetta postale",
    t112: "Informazioni sul token",
    t113: "Inserisci le informazioni sul token, non più di 120 caratteri",
    t114: "Invia",
    t115: "Invia dopo la connessione al portafoglio",
    t116: "Cancella contenuto modulo",
    t117: "BDX guida la rivoluzione nel settore delle criptovalute",
    t118: "Connetti i tuoi asset, applicazioni DeFi e NFT per aiutarti a sbloccare rapidamente il mondo Web3",
    t119: "Ottieni BDX con un clic",
    t120: "Libro bianco BDX",
    t121: "Introduzione a BDX",
    t122: "Tieni BDX e goditi infiniti vantaggi",
    t123: "Nuovo abbonamento",
    t124: "Servizio preferenziale",
    t125: "Meccanismo di deflazione",
    t126: "Nuovo online",
    t127: "Pianificazione",
    t128: "Ottieni BDX",
    t129: "Informazioni sulla versione BDX",
    t130: "Sicuro, facile da usare e strettamente connesso alle culture e alle ideologie di tutto il mondo",
    t131: "Nome token",
    t132: "Simbolo gettone",
    t133: "Catena proprietaria",
    t134: "Indirizzo del contratto",
    t135: "Prezzo di emissione",
    t136: "Fornitura di circolazione",
    t137: "Fornitura totale",
    t138: "Data di emissione",
    t139: "Sostituisci BDX",
    t140: "Per il riscatto di token BDX esistenti",
    t141: "Motivazione della squadra",
    t142: "2% sbloccato ogni 6 mesi, verrà sbloccato completamente tra 5 anni (60 mesi)",
    t143: "Investimenti economici ed ecologici",
    t144: "Vai all'ecosistema BeingDex per l'investimento in fondi",
    t145: "Promozione del marchio",
    t146: "Rilasci massimi all'anno",
    t147: "Input utente",
    t148: "Fondo di tutela",
    t149: "Per il risarcimento di eventuali incidenti sulla piattaforma",
    t150: "Lavora con noi per creare un ecosistema BDX sicuro e affidabile e promuovere il rapido sviluppo di Web3",
    t151: "Ottieni BDX con un clic",
    t152: "Consigliato",
    t153: "Ultimo blog",
    t154: "Ancora nessun dato",
    t155: "Negozio di applicazioni DApp",
    t156: "Cerca",
    t157: "Seleziona categoria",
    t158: "Importante esclusione di responsabilità",
    t159: "Tutti i contenuti forniti su questo sito Web, siti Web con collegamenti ipertestuali, applicazioni correlate, forum, blog, account di social media e altre piattaforme (il 'Sito') sono solo per informazioni generali ottenute da fonti di terze parti. Non siamo responsabili per i nostri contenuto Non viene fornita alcuna garanzia di alcun tipo, incluso ma non limitato all'accuratezza e all'attualità. Nessuna parte del contenuto da noi fornito costituisce consulenza finanziaria, consulenza legale o qualsiasi altra forma di consulenza progettata per soddisfare la tua specifica dipendenza per qualsiasi scopo. l'uso o l'affidamento sui nostri contenuti avviene a proprio rischio e discrezione. È necessario condurre ricerche, revisioni, analisi e verifiche prima di fare affidamento sui nostri contenuti. Il trading è un'attività ad alto rischio che può comportare perdite significative, quindi per favore consulta il tuo consulente finanziario prima di prendere qualsiasi decisione. Niente sul nostro sito web costituisce una sollecitazione o un'offerta.",
    t160: "Inserisci i dettagli del suggerimento",
    t161: "Invio riuscito",
    t162: "Ognuno dei tuoi suggerimenti",
    t163: "Ascolteremo attentamente e tratteremo la questione seriamente",
    t164: "Feedback",
    t165: "Se trovi difetti o vulnerabilità nella sicurezza, ti preghiamo di fornirci un feedback tempestivo",
    t166: "In caso di domande, consultare il Centro assistenza per le risposte alle domande più frequenti.",
    t167: "Cosa ne pensi della nostra esperienza con il prodotto?",
    t168: "Non è stata una bella esperienza!",
    t169: "Da migliorare!",
    t170: "Abbastanza soddisfacente!",
    t171: "Super fantastico!",
    t172: "Invia suggerimento",
    t173: "Benvenuto per condividere i tuoi suggerimenti sui prodotti. BeingDex prenderà sul serio il tuo feedback. Se hai domande urgenti, contatta il servizio clienti.",
    t174: "Categoria suggerita",
    t175: "Raccomandazioni di sicurezza",
    t176: "Suggerimenti sulle funzionalità",
    t177: "Suggerimenti per la progettazione",
    t178: "Suggerimenti operativi",
    t179: "Altri suggerimenti",
    t180: "Dettagli suggerimento",
    t181: "Inserisci il tuo feedback, non più di 500 caratteri",
    t182: "Carica immagini (opzionale)",
    t183: "Carica screenshot relativi al problema. Il formato dell'immagine è JPG o PNG e la dimensione non deve superare i 2 MB",
    t184: "Informazioni di contatto (facoltativo)",
    t185: "Inserisci le informazioni di contatto",
    t186: "Conferma invio",
    t187: "Invia dopo la connessione al portafoglio",
    t188: "Salva bozza",
    t189: "Come funziona?",
    t190: "Invia suggerimento",
    t191: "Revisione del team",
    t192: "Distribuisci premi",
    t193: "BeingDex è al servizio degli utenti di tutto il mondo. Consideriamo lo sviluppo sicuro e stabile della piattaforma come la nostra massima priorità. Attendiamo con ansia i vostri preziosi suggerimenti. Miglioriamo la qualità del prodotto e creiamo insieme un futuro migliore.",
    t194: "Un protocollo di cui gli utenti Web3 possono fidarsi<br>consente agli utenti Defi di completare facilmente le transazioni",
    t195: "Autocustodia degli asset, transazioni di abbinamento punto a punto del portafoglio",
    t196: "Sicurezza con zero incidenti ed esecuzione pura di contratti intelligenti",
    t197: "Grafico K-line decentralizzato originale, vantaggi nativi",
    t198: "Criptovalute popolari",
    t199: "EssereDex Ecologia",
    t200: "Gestisci facilmente le tue risorse",
    t201: "BeingDex è una piattaforma di trading decentralizzata che abbina il registro degli ordini costruita con contratti intelligenti puri. Il layout ecologico generale copre Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, pool minerari e altri settori.",
    t202: "Un prodotto decentralizzato che integra portafoglio e transazione",
    t203: "BeingDex - una piattaforma di trading decentralizzata per l'abbinamento degli ordini costruita con puri contratti intelligenti",
    t204: "Applicazione - Prodotti ecologici diversificati BeingDex",
    t205: "Portafoglio - Gestisci le tue risorse multi-catena",
    t206: "Il trading dovrebbe essere effettuato sempre e ovunque",
    t207: "Scarica l'App e ti aiuteremo a fare trading 24 ore su 24, 7 giorni su 7",
    t208: "Scansiona per scaricare",
    t209: "Risorse multimediali",
    t210: "Conformità e politica",
    t211: "Certificazione ufficiale globale di conformità alla sicurezza per garantire la sicurezza dei beni degli utenti",
    t212: "Ottieni licenza US MSB",
    t213: "28 novembre 2023",
    t214: "La domanda per la licenza DMCC di Dubai è in sospeso",
    t215: "Domanda di licenza da parte della Hong Kong Securities Regulatory Commission/VARA/DIFC/ADGM/US MTL ecc.",
    t216: "I nostri partner",
    t217: "Più di 15 anni di esperienza nella tecnologia dell'informazione.<br>Architetto di applicazioni e cloud computing/DevOps senior altamente qualificato con esperienza in AWS, GCP, Azure e strumenti DevOps/SystemOps/DevOps e vasta conoscenza dei servizi.<br>8 + anni di esperienza di lavoro come Cloud/DevSecOps/Application Architect nel settore finanziario<br>Ho progettato il primo prototipo di portafoglio hardware di criptovaluta canadese per la mia startup Blockchain Mind.",
    t218: "Invita i tuoi amici e vinci fino a<br>9.000 USDT",
    t219: "Link di invito",
    t220: "Invita ora",
    t221: "Invita dopo la connessione al portafoglio",
    t222: "Registro invito",
    t223: "Nome utente",
    t224: "Ora di registrazione",
    t225: "La ricarica raggiunge lo standard",
    t226: "La transazione soddisfa gli standard",
    t227: "Bonus sul deposito",
    t228: "Scatola cieca",
    t229: "Eventi popolari",
    t230: "Regole",
    t231: "1. Quando un amico invitato completa l'attività di ricarica, l'invitante riceverà un buono sconto di 100 USDT. Dopo che l'amico invitato ha completato l'attività di transazione, l'invitante può estrarre casualmente una ricompensa blind box di 5-500 USDT. <br> 2. Attività di ricarica: entro 30 giorni dalla registrazione dell'amico invitato, ricarica attraverso i canali designati e la ricarica netta cumulativa supera i 50 USDT. <br> 3. Attività di trading: entro 30 giorni dalla registrazione dell'amico invitato, il volume cumulativo delle transazioni spot o dei contratti supera i 200 USDT. <br>4. Gli amici invitati devono completare l'attività di ricarica prima di poter sbloccare i premi dell'attività di scambio. Se il tuo amico invitato non completa con successo l'attività di ricarica, non potrai ottenere il premio anche se la transazione supera i 200USDT. <br> 5. Canali di ricarica designati: la ricarica valida è limitata alla ricarica on-chain, alla ricarica in valuta fiat, agli acquisti con carta, alle transazioni C2C e ai pagamenti di terze parti. I bonifici interni e le buste rosse non sono compresi nella ricarica effettiva. 6. L'invitante può ricevere fino a 15 coupon di detrazione delle spese di gestione e 15 premi in contanti blind box ogni mese. <br> 7. Periodo di validità: il coupon per la detrazione delle spese di gestione deve essere ritirato entro 14 giorni dall'emissione. Il periodo di validità dopo il ritiro è di 14 giorni. Si prega di prestare attenzione a riceverlo e utilizzarlo in tempo per evitare la scadenza del premio ; il periodo di riscatto del premio blind box è valido per 90 giorni. Ti invitiamo a riscattare il premio in coupon in contanti il ​​prima possibile dopo aver ricevuto il premio. Dopo il riscatto, il coupon in contanti è valido per 14 giorni. <br> 8. Gli inviti provenienti dallo stesso indirizzo IP o dispositivo saranno considerati autoinviti. L'auto-invito comporterà la perdita da parte dell'utente dei premi già guadagnati e dell'idoneità a ricevere premi futuri. BeingDex si riserva il diritto di congelare i conti illegali e confiscare i beni nei conti. <br>9. Quando i premi vengono distribuiti, il sistema determinerà automaticamente se le due parti attuali hanno lo status di partner esclusivo. Se l'invitante o l'invitato è un partner esclusivo, il premio entrerà in conflitto con il premio sconto del partner esclusivo e il premio non verrà assegnato. Inoltre, gli account secondari non possono partecipare alle attività come account indipendenti e i dati non verranno uniti nell'account principale. <br> 10. Le regole di cui sopra entreranno in vigore dalle ore 18:00 dell'11 maggio 2023 (UTC+8). BeingDex si riserva il diritto di interpretazione finale di questa attività. BeingDex si riserva il diritto di trattare gli account e le risorse degli utenti se viene scoperto un comportamento dannoso o un comportamento illegale e non etico che sfrutta le vulnerabilità della piattaforma. <br> 11. Non puoi fingere di essere ufficiale di BeingDex e fare dichiarazioni fuorvianti, incluso ma non limitato all'acquisto di parole chiave come 'BeingDex', 'login di BeingDex', 'ufficiale di BeingDex', 'BeingDex C2C', ecc. per promuovere sui motori di ricerca. Coloro che violano i requisiti saranno squalificati da premi e promozioni.",
    t232: "Conformità e sicurezza",
    t233: "BeingDex insiste sull'implementazione di un sistema completo di conformità e governance della sicurezza e segue standard e processi rigorosi formulati dal team di consulenza sulla conformità per garantire la gestione e il monitoraggio del rischio a tutto tondo.<br>La piattaforma conduce regolarmente valutazioni complete del rischio per identificare il rischio potenziale i punti includono il rischio di mercato e il rischio operativo. Implementare strategie efficaci di gestione del rischio, monitorare e identificare attivamente i possibili rischi interni ed esterni e adottare misure di risposta adeguate. Per i rischi causati da fattori esterni, BeingDex utilizzerà la tecnologia di crittografia avanzata che protegge la sicurezza dei dati. Per i rischi interni , stabilire un rigoroso meccanismo di controllo interno, compreso un meccanismo di autorizzazione per chiarire le responsabilità, e condurre regolari audit interni ed esterni.<br>Coordinandosi regolarmente con le agenzie di regolamentazione locali e conducendo revisioni di conformità, ciò include le leggi e i regolamenti esterni nazionali, in particolare quelli riguardanti servizi finanziari, protezione dei dati e antiriciclaggio (AML), garantire la conformità e la sicurezza delle operazioni dell'azienda e garantire che la piattaforma sia conforme a tutte le normative e gli standard finanziari applicabili.",
    t234: "Quadro di gestione della conformità",
    t235: "Identificazione",
    t236: "Valutazione",
    t237: "Esegui",
    t238: "valutazione",
    t239: "1. Gestione della conformità",
    t240: "Sotto la supervisione di un team di esperti di conformità, BeingDex segue rigorosi standard e protocolli di conformità, implementa una struttura completa di gestione della conformità e conduce un'efficace identificazione, valutazione, esecuzione e valutazione.<br>BeingDex rileva e identifica attivamente fonti esterne e rischi interni e adottare le misure correttive necessarie. I rischi esterni si riferiscono a rischi che possono essere causati da cambiamenti esterni, come informazioni errate pubblicate da annunci pubblicitari di terze parti di agenti BeingDex.<br> I rischi interni si riferiscono a rischi che possono provenire dall'interno Rischi dell'organizzazione, come condotta non autorizzata, inappropriata, illegale o non etica da parte di dipendenti interni.<br>BeingDex collabora con le autorità di regolamentazione locali attraverso una combinazione di valutazioni e revisioni annuali di conformità per garantire che i nostri standard di conformità soddisfino i requisiti locali.",
    t241: "Tecnologia 2.eKYC",
    t242: "BeingDex adotta la verifica dell'identità elettronica (eKYC) per proteggere la piattaforma e ridurre potenziali frodi e rischi illegali. Oltre a ciò, BeingDex dispone di sanzioni e politiche antiriciclaggio (AML) per conformarsi a tutte le giurisdizioni pertinenti e prevenire la contraffazione o altre attività criminali sulla piattaforma.<br>L'efficienza è fondamentale per la due diligence del cliente (CDD), pertanto BeingDex adotta la tecnologia eKYC per ottimizzare il processo di verifica dell'identità dell'utente (KYC) sotto la premessa della conformità.<br>Questo la tecnologia consente il riconoscimento facciale e la corrispondenza incrociata automatica tra l'identificazione fornita dall'utente e i ritratti in tempo reale, prevenendo così identità false e riducendo notevolmente anche il tempo necessario agli utenti per condurre la verifica dell'identità personale sulla piattaforma BeingDex.",
    t243: "2. Analisi blockchain",
    t244: "BeingDex utilizza strumenti esterni di analisi blockchain per monitorare da vicino le transazioni sulla piattaforma e ridurre il rischio di attività fraudolente e l'emergere di utenti ad alto rischio*. La natura immutabile e trasparente della blockchain ci consente di rilevare in modo completo le transazioni sulla piattaforma Tutte le transazioni.<br>*Gli utenti ad alto rischio includono, a titolo esemplificativo:<br>- Clienti in paesi o regioni sensibili<br>- Funzionari governativi<br>- Clienti di settori sensibili (come le aziende ad alta intensità di capitale) <br >Sulla base della valutazione del nostro team di rischio e governance, adotteremo varie misure contro gli utenti ad alto rischio, che potrebbero includere il sequestro dei beni, molteplici revisioni o audit, ecc., a seconda della situazione specifica.",
    t245: "3.Sicurezza della rete",
    t246: "BeingDex consulta esperti indipendenti di sicurezza di rete per migliorare la sicurezza e la stabilità della piattaforma. Allo stesso tempo, due volte all'anno vengono condotti test di penetrazione della rete e valutazioni di vulnerabilità per gestire tempestivamente e rapidamente le potenziali minacce rilevate.<br>Oltre a Dopo i test di cui sopra, BeingDex crittografa anche tutti i dati sensibili per prevenire rischi come furto, accesso o modifica non autorizzati. Tutti i dati trasferiti o salvati vengono crittografati e archiviati in modo sicuro in un archivio a tolleranza di errore.",
    t247: "Operazione riuscita",
    t248: "Tutti letti",
    t249: "Virgolette",
    t250: "Il cambiamento di oggi",
    t251: "Volume degli scambi 24 ore su 24",
    t252: "Volume delle transazioni 24 ore su 24",
    t253: "Valute popolari",
    t254: "Ultima valuta",
    t255: "La valuta con il maggiore incremento",
    t256: "Valuta con il volume di scambi più elevato",
    t257: "Transazioni più veloci, asset migliori",
    t258: "Il tuo futuro portafoglio di transazioni Web3",
    t259: "Super portale dell'universo Web3",
    t260: "Unisciti a 12 milioni di utenti, naviga facilmente nel più grande mercato NFT e interagisci in modo sicuro con oltre 20.000 DApp su BeingDex Wallet",
    t261: "Goditi la piattaforma NFT più completa e facile da usare",
    t262: "Aggregazione di più mercati NFT tradizionali, supporto del posizionamento batch di ordini con un clic e acquisto di NFT in qualsiasi valuta",
    t263: "Acquisto",
    t264: "Lascia che la blockchain esista ovunque",
    t265: "Portafoglio multi-catena, sicuro e facile da usare, ingresso blockchain",
    t266: "Portafoglio open source",
    t267: "Portafoglio open source, chiave privata autosufficiente, crittografia multistrato",
    t268: "Segui il tuo cuore e sentiti a tuo agio",
    t269: "Domanda multicatena, conveniente, decentralizzata, con uno sportello unico",
    t270: "Portafoglio decentralizzato",
    t271: "Separazione delle risorse calde e fredde, Token 40000+ sicuro e conveniente",
    t272: "Criptoasset",
    t273: "Oltre 40.000 asset crittografici supportano vari asset per il trading su DEX.",
    t274: "Tecnologia di crittografia multipla",
    t275: "Conserva la criptovaluta in modo sicuro e controlla le tue risorse.",
    t276: "Modalità guadagno multiplo",
    t277: "Staking, mining, DeFi, giochi a catena.",
    t278: "Autocustodia di beni, abbinamento peer-to-peer delle transazioni del portafoglio",
    t279: "Sicurezza con zero incidenti ed esecuzione pura di contratti intelligenti",
    t280: "Grafico K-line decentralizzato originale, vantaggi nativi",
    t281: "La tua scelta è uguale alla loro",
    t282: "Fiducia e scelta di oltre 1.000 aziende leader",
    t283: "portafoglio plug-in",
    t284: "Tutorial sull'installazione del plug-in",
    t285: "Lo strumento di gestione delle risorse digitali blockchain leader a livello mondiale",
    t286: "Esecuzione pura del contratto intelligente",
    t287: "Scarica ora",
    t288: "Ingresso Ecologico DApp",
    t289: "Esplora DeFi, GameFi, ecc. e gioca rapidamente con l'economia DApp",
    t290: "Cominciamo! Clicca qui per inviare suggerimenti o feedback",
    t291: "Visualizza altro",
    t292: "Tipo di token",
    t293: "BeingDex, piattaforma di trading di gestione patrimoniale unica e multicatena<br>sicura, efficiente e a basso costo",
    t294: "Ponte a catene incrociate BeingDex",
    t295: "Italiano",
    t296: "Non ancora aperto",
    t297: "operare",
    t298: "portafoglio",
    t299: "Scambia",
    t300: "Dapp",
    t301: "Blog"
  }
}