export default {
  text: {
    t1: "Zuhause",
    t2: "Kommen Sie zu uns",
    t3: "Google Store",
    t4: "Apple Store",
    t5: "App herunterladen",
    t6: "Chrome-Download",
    t7: "Lokaler Download",
    t8: "BDX-Währungspreis",
    t9: "Handelsvolumen",
    t10: "Community-Benutzer",
    t11: "Anzahl der Transaktionen",
    t12: "BDX-Gesamttransaktionsvolumen",
    t13: "Wachstumsliste",
    t14: "Ablehnungsliste",
    t15: "Neue Münzliste",
    t16: "Transaktionsvolumenliste",
    t17: "Name",
    t18: "Aktuellster Preis",
    t19: "Preis",
    t20: "Heutiger Anstieg",
    t21: "Erhöhen oder verringern",
    t22: "24H-Handelsvolumen",
    t23: "Transaktion",
    t24: "Noch keine Daten",
    t25: "Alle anzeigen",
    t26: "Sicher, effizient, kostengünstig",
    t27: "Kundenservice online",
    t28: "Geschäftskooperation",
    t29: "Firma",
    t30: "Über uns",
    t31: "Hilfecenter",
    t32: "Ankündigung",
    t33: "BDX-Token",
    t34: "Produkt",
    t35: "Münzen kaufen",
    t36: "Web3-Wallet",
    t37: "Dienst",
    t38: "Feedback",
    t39: "Antrag auf Währungsnotierung",
    t40: "Einladung eines Freundes",
    t41: "Rechtliche und Risikooffenlegung",
    t42: "Compliance-Lizenz",
    t43: "Richtlinie zur Bekämpfung der Geldwäsche",
    t44: "Datenschutzerklärung",
    t45: "Nutzungsvereinbarung",
    t46: "Rechtliche Erklärung",
    t47: "Risikowarnung",
    t48: "ST-Regel",
    t49: "Plug-in-Wallet",
    t50: "Wallet herunterladen",
    t51: "Sprache",
    t52: "Abmelden",
    t53: "Wallet verbinden",
    t54: "Laden…",
    t55: "Nicht mehr…",
    t56: "Über BeingDex",
    t57: "Hinter BeingDex steht eine Gruppe von Early Adopters der Blockchain-Technologie und Gläubigen an die zukünftige Entwicklung der Blockchain.",
    t58: "Seit 2018 haben wir eine Kryptowährungsbörse eingerichtet und sind bestrebt, sichere Handelslösungen aus einer Hand bereitzustellen, um Benutzern zu helfen, intelligenter zu handeln.",
    t59: "Dezentrale Handelsplattform für die vollständige Kette ausstehender Orders",
    t60: "Global registrierte Adresse",
    t61: "100.000+",
    t62: "30 Millionen USDT",
    t63: "Tägliches Handelsvolumen",
    t64: "Unsere Geschichte",
    t65: 'Das ist eine Gruppe von Geeks, die fest an Blockchain und Kryptowährungs-Assets glauben. Im Jahr 2010 kauften wir unsere ersten Bitcoins über eine E-Commerce-OTC-Plattform. Damals waren wir nervös und unruhig. Als sich der Branchenzyklus änderte." Änderungen, Transaktionsmethoden und Produktformen werden weiterhin innovativ und weiterentwickelt, was zu einer Situation führt, in der sich Cex und Dex gleichzeitig entwickeln. Wir sind uns jedoch auch darüber im Klaren, dass der bestehende Dex seinem Modellmechanismus unterliegt und die Vermögenseffizienz nicht maximieren kann.<br >Gleichzeitig Mit der Zeit, da die Verschlüsselungsindustrie einen immer breiteren und tiefgreifenderen Einfluss auf globaler Ebene hat, schließen sich neben den entwickelten Gebieten auch immer mehr Menschen aus Gebieten mit schwacher Finanzinfrastruktur an, die jedoch Schwierigkeiten haben, komplexe Finanzprodukte und algorithmische Mechanismen zu verstehen . . Dies ist zu einer Lücke geworden, die sie daran hindert, die neue Welt und neue Vermögenswerte zu verbinden.<br>BeingDex ist bestrebt, diese Lücke zu schließen und durch neue intelligente Verträge vollständige Anwendungsprodukte und Ökologie aufzubauen.<br>Das Sein hat "Existenz". "Die Konnotationen wie "Essenz" und "biologisches Leben" drücken unseren Geist der Erforschung des Ursprungs der Dinge, unsere grundlegende Praxis des Produktwerts und unser ultimatives Streben nach Benutzererfahrung aus. Wir ermutigen uns selbst und heißen mehr Menschen willkommen, ihren Geist zu öffnen und Nehmen Sie Verschlüsselung an. Vermögenswerte, und helfen Sie ihnen, ihre eigene Reise zum Krypto-Vermögen durch benutzerfreundliche und benutzerfreundliche Produktdienstleistungen zu beginnen.',
    t66: "Vision",
    t67: "Schaffen Sie eine freiere, gerechtere und transparentere Vermögenswelt der Zukunft durch Web3",
    t68: "Mission",
    t69: "Erstellen Sie die ultimative Handelsplattform, die jeder nutzen kann, und werden Sie zum führenden Finanzdienstleister für digitale Vermögenswerte in der Branche",
    t70: "Unsere Werte",
    t71: "Benutzer zuerst",
    t72: "Achten Sie auf die Bedürfnisse und Einstellungen jedes Benutzers, kommunizieren Sie objektiv und offen und veröffentlichen Sie Plattforminformationen zeitnah.",
    t73: "Integrität und Genauigkeit",
    t74: 'Wir halten uns an den Grundsatz "Tue nichts Böses" und gewinnen durch Verantwortung und Verantwortung das Vertrauen des Marktes und der Nutzer.',
    t75: "Innovation und Unternehmertum",
    t76: "Extreme Produkte und Dienstleistungen sowie Gebäudestrukturvorteile sind unser ewiges Streben.",
    t77: "Beginnen Sie mit dem Ende im Hinterkopf",
    t78: "Machen Sie langfristige Dinge mit langfristigen Partnern, verstehen Sie den Prozess, schaffen Sie Bedingungen, achten Sie auf Feedback-Ergebnisse und erreichen Sie kontinuierlich Meilensteinziele.",
    t79: "Unser Team",
    t80: "Mit über 150 Mitarbeitern aus über 10 Ländern verfügt das BeingDEX-Team über hochrangige Talente aus allen Teilen der Welt, was uns eine wirklich globale Reichweite verschafft.",
    t81: "Unsere Leistungen",
    t82: "BeingDEX",
    t83: "BeingDex ist eine neue dezentrale Börse, die auf der Multi-Chain-Entwicklung basiert. Sie verwendet ein On-Chain-Order-Matching-Modell und die Cross-Chain-Brücke unterstützt die öffentlichen Ketten BSC, TRON und OKX.",
    t84: "Brieftasche sein",
    t85: "Being Wallet nutzt zwei wichtige Sicherheitsmechanismen: Selbstverwahrung der Benutzerressourcen und vollständige Anonymität. Die zugrunde liegende Wallet-Technologie unterstützt mehrere Sicherheitsschutzmaßnahmen wie lokale biometrische Verschlüsselung und Sicherheitsisolierung und unterstützt die Verwaltung von Multi-Chain-Assets, um die Sicherheit der Benutzer zu schützen. Transaktionen.",
    t86: "NFT sein",
    t87: "Being NFT unterstützt ETH, BSC, Mango, TRON, Polygon, Solana Multi-Chain-Ein-Klick-Ausgabe von NFT, Transaktionen und andere Aktivitäten werden über das Kettenprotokoll ohne Eingreifen Dritter abgeschlossen. Der von der DAO organisierte NFT ist in der Brieftasche gespeichert. On-Chain-Casting, intelligente Transaktionen, sicher und bequem.",
    t88: "Beginnen Sie jetzt Ihre Krypto-Reise!",
    t89: "Handeln Sie auf einer Plattform, der Millionen von Benutzern vertrauen.",
    t90: "Upload erfolgreich",
    t91: "Upload fehlgeschlagen",
    t92: "Bitte wählen Sie die öffentliche Kette aus, zu der Sie gehören",
    t93: "Bitte geben Sie den Projektnamen ein",
    t94: "Bitte Logo hochladen",
    t95: "Bitte geben Sie die Token-Abkürzung ein",
    t96: "Bitte geben Sie die Vertragsadresse ein",
    t97: "Bitte geben Sie die Ausgabemenge ein",
    t98: "Bitte geben Sie den offiziellen Website-Link ein",
    t99: "Bitte geben Sie Ihre E-Mail-Adresse ein",
    t100: "Bitte geben Sie Ihre Token-Informationen ein",
    t101: "Übermittlung erfolgreich",
    t102: "BeingDex-Währungslistungsanwendung",
    t103: "Vielen Dank für Ihre Aufmerksamkeit für BeingDex Exchange. Bitte füllen Sie das Antragsformular aus und geben Sie gültige Informationen an. Wir werden Ihr Projekt anhand der von Ihnen bereitgestellten Informationen prüfen. Bitte reichen Sie diesen Antrag ein und Ihr Projekt wird an die Abteilung für Währungsnotierung gesendet . Überprüfung. Nachdem Sie die vorläufige Prüfung bestanden haben, beauftragen wir einen Währungslistungsspezialisten, der Ihnen den Prozess und die Techniken der Währungslistung erläutert und Sie durch den Prozess der Währungslistung führt.",
    t104: "Zeigt erforderlich an",
    t105: "Öffentliche Kette, zu der es gehört",
    t106: "Projektname",
    t107: "Token-Abkürzung",
    t108: "Vertragsadresse",
    t109: "Ausgabemenge",
    t110: "Offizieller Website-Link",
    t111: "Postfach",
    t112: "Token-Informationen",
    t113: "Bitte geben Sie Ihre Token-Informationen ein, nicht mehr als 120 Zeichen",
    t114: "Senden",
    t115: "Senden nach Verbindung mit der Wallet",
    t116: "Formularinhalt löschen",
    t117: "BDX führt die Revolution in der Kryptoindustrie an",
    t118: "Verbinden Sie Ihre Vermögenswerte, DeFi-Anwendungen und NFTs, um Ihnen zu helfen, die Web3-Welt schnell zu erschließen",
    t119: "BDX mit einem Klick holen",
    t120: "BDX-Whitepaper",
    t121: "Einführung in BDX",
    t122: "Halten Sie BDX und genießen Sie endlose Vorteile",
    t123: "Neues Abonnement",
    t124: "Vorzugsdienst",
    t125: "Deflationsmechanismus",
    t126: "Neu online",
    t127: "Planung",
    t128: "BDX holen",
    t129: "BDX-Release-Informationen",
    t130: "Sicher, einfach zu bedienen und eng mit Kulturen und Ideologien auf der ganzen Welt verbunden",
    t131: "Tokenname",
    t132: "Token-Symbol",
    t133: "Besitzende Kette",
    t134: "Vertragsadresse",
    t135: "Ausgabepreis",
    t136: "Zirkulationsversorgung",
    t137: "Gesamtvorrat",
    t138: "Ausgabedatum",
    t139: "BDX ersetzen",
    t140: "Zur Einlösung vorhandener BDX-Tokens",
    t141: "Teammotivation",
    t142: "2 % werden alle 6 Monate freigeschaltet, werden in 5 Jahren (60 Monaten) vollständig freigeschaltet",
    t143: "Ökonomische und ökologische Investition",
    t144: "Gehen Sie zum BeingDex-Ökosystem für Fondsinvestitionen",
    t145: "Markenwerbung",
    t146: "Maximale Veröffentlichungen pro Jahr",
    t147: "Benutzereingabe",
    t148: "Schutzfonds",
    t149: "Zur Entschädigung für mögliche Unfälle auf dem Bahnsteig",
    t150: "Arbeiten Sie mit uns zusammen, um ein sicheres und zuverlässiges BDX-Ökosystem zu schaffen und die schnelle Entwicklung von Web3 zu fördern",
    t151: "BDX mit einem Klick holen",
    t152: "Empfohlen",
    t153: "Neuester Blog",
    t154: "Noch keine Daten",
    t155: "DApp Application Store",
    t156: "Suchen",
    t157: "Kategorie auswählen",
    t158: "Wichtiger Haftungsausschluss",
    t159: 'Alle auf dieser Website, mit Hyperlinks versehenen Websites, verwandten Anwendungen, Foren, Blogs, Social-Media-Konten und anderen Plattformen (die "Website") bereitgestellten Inhalte dienen ausschließlich Ihrer allgemeinen Information und stammen aus Quellen Dritter. Wir sind nicht verantwortlich für unsere Inhalt Es werden keine Garantien jeglicher Art übernommen, einschließlich, aber nicht beschränkt auf Genauigkeit und Aktualität. Kein Teil der von uns bereitgestellten Inhalte stellt eine Finanzberatung, Rechtsberatung oder eine andere Form der Beratung dar und ist dazu bestimmt, Ihr spezifisches Vertrauen zu irgendeinem Zweck zu befriedigen. Beliebig Jegliche Nutzung oder das Vertrauen auf unsere Inhalte erfolgt auf Ihr eigenes Risiko und nach eigenem Ermessen. Sie sollten Ihre eigenen Recherchen, Überprüfungen, Analysen und Verifizierungen durchführen, bevor Sie sich auf unsere Inhalte verlassen. Der Handel ist eine risikoreiche Aktivität, die zu erheblichen Verlusten führen kann Bitte konsultieren Sie Ihren Finanzberater, bevor Sie Entscheidungen treffen. Nichts auf unserer Website stellt eine Aufforderung oder ein Angebot dar.',
    t160: "Bitte geben Sie die Vorschlagsdetails ein",
    t161: "Übermittlung erfolgreich",
    t162: "Jeder Ihrer Vorschläge",
    t163: "Wir werden aufmerksam zuhören und es ernst nehmen",
    t164: "Feedback",
    t165: "Wenn Sie Sicherheitslücken oder Schwachstellen feststellen, geben Sie uns bitte zeitnah Feedback",
    t166: "Wenn Sie Fragen haben, wenden Sie sich bitte an die Hilfe, um Antworten auf häufig gestellte Fragen zu erhalten.",
    t167: "Was halten Sie von unserem Produkterlebnis?",
    t168: "Keine gute Erfahrung!",
    t169: "Zu verbessern!",
    t170: "Ganz zufriedenstellend!",
    t171: "Super genial!",
    t172: "Vorschlag einreichen",
    t173: "Willkommen, Ihre Produktvorschläge zu teilen. BeingDex wird Ihr Feedback ernst nehmen. Wenn Sie dringende Anfragen haben, wenden Sie sich bitte an den Kundendienst.",
    t174: "Vorgeschlagene Kategorie",
    t175: "Sicherheitsempfehlungen",
    t176: "Funktionsvorschläge",
    t177: "Designvorschläge",
    t178: "Betriebsvorschläge",
    t179: "Andere Vorschläge",
    t180: "Vorschlagsdetails",
    t181: "Bitte geben Sie Ihr Feedback ein, nicht mehr als 500 Zeichen",
    t182: "Bilder hochladen (optional)",
    t183: "Bitte laden Sie Screenshots hoch, die sich auf das Problem beziehen. Das Bildformat ist JPG oder PNG und die Größe darf 2 MB nicht überschreiten.",
    t184: "Kontaktinformationen (optional)",
    t185: "Bitte geben Sie Kontaktinformationen ein",
    t186: "Übermittlung bestätigen",
    t187: "Senden nach Verbindung mit der Wallet",
    t188: "Entwurf speichern",
    t189: "Wie funktioniert es?",
    t190: "Vorschlag einreichen",
    t191: "Teambewertung",
    t192: "Belohnungen verteilen",
    t193: "BeingDex bedient Nutzer auf der ganzen Welt. Wir betrachten die sichere und stabile Entwicklung der Plattform als unsere oberste Priorität. Wir freuen uns auf Ihre wertvollen Vorschläge. Lassen Sie uns gemeinsam die Produktqualität verbessern und eine bessere Zukunft schaffen.",
    t194: "Ein Protokoll, dem Web3-Benutzer vertrauen können<br>ermöglicht Defi-Benutzern die einfache Durchführung von Transaktionen",
    t195: "Asset Self-Custody, Wallet Point-to-Point-Matching-Transaktionen",
    t196: "Sicherheit ohne Unfälle und rein intelligente Vertragsausführung",
    t197: "Ursprüngliches dezentrales K-Linien-Diagramm, native Vorteile",
    t198: "Beliebte Kryptowährungen",
    t199: "BeingDex Ökologie",
    t200: "Verwalten Sie Ihr Vermögen einfach",
    t201: "BeingDex ist eine auf Orderbücher abgestimmte dezentrale Handelsplattform, die auf reinen Smart Contracts basiert. Das ökologische Gesamtlayout umfasst Krypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, Mining-Pools und andere Branchen.",
    t202: "Ein dezentrales Produkt, das Wallet und Transaktion integriert",
    t203: "BeingDex – eine dezentrale Handelsplattform zum Order-Matching, die auf reinen Smart Contracts basiert",
    t204: "Anwendung – Diversifizierte ökologische Produkte von BeingDex",
    t205: "Wallet – Verwalten Sie Ihre Multi-Chain-Assets",
    t206: "Der Handel sollte jederzeit und überall erfolgen",
    t207: "Laden Sie die App herunter und wir helfen Ihnen rund um die Uhr beim Handel",
    t208: "Zum Herunterladen scannen",
    t209: "Medienressourcen",
    t210: "Compliance und Richtlinien",
    t211: "Globale offizielle Zertifizierung der Sicherheitskonformität, um die Sicherheit der Benutzerressourcen zu gewährleisten",
    t212: "US-MSB-Lizenz erhalten",
    t213: "28. November 2023",
    t214: "Antrag auf Dubai DMCC-Lizenz steht noch aus",
    t215: "Antrag auf Lizenzen bei der Hong Kong Securities Regulatory Commission/VARA/DIFC/ADGM/US MTL usw.",
    t216: "Unsere Partner",
    t217: "Über 15 Jahre Erfahrung in der Informationstechnologie.<br>Hochqualifizierter Senior Cloud Computing/DevOps und Anwendungsarchitekt mit Erfahrung in AWS, GCP, Azure und DevOps/SystemOps/DevOps-Tools und umfassendem Verständnis von Diensten.<br>8 + jahrelange Erfahrung als Cloud-/DevSecOps-/Anwendungsarchitekt im Finanzsektor<br>Entwarf Kanadas ersten Kryptowährungs-Hardware-Wallet-Prototyp für mein Startup Blockchain Mind.",
    t218: "Freunde einladen und bis zu<br>9.000 USDT gewinnen",
    t219: "Einladungslink",
    t220: "Jetzt einladen",
    t221: "Einladung nach Verbindung mit Wallet",
    t222: "Einladungsdatensatz",
    t223: "Benutzername",
    t224: "Registrierungszeit",
    t225: "Aufladung erreicht Standard",
    t226: "Transaktion entspricht dem Standard",
    t227: "Einzahlungsbonus",
    t228: "Blindbox",
    t229: "Beliebte Ereignisse",
    t230: "Regeln",
    t231: '1. Wenn der eingeladene Freund die Aufladeaufgabe abschließt, kann der Einladende einen Rabattcoupon im Wert von 100 USDT erhalten. Nachdem der eingeladene Freund die Transaktionsaufgabe abgeschlossen hat, kann der Einladende nach dem Zufallsprinzip eine Blindbox-Belohnung von 5-500 USDT ziehen.<br > 2. Aufladeaufgabe: Innerhalb von 30 Tagen, nachdem sich der eingeladene Freund registriert hat, über bestimmte Kanäle aufladen und die kumulierte Nettoeinzahlung 50 USDT übersteigt.<br> 3. Handelsaufgaben: Innerhalb von 30 Tagen, nachdem sich der eingeladene Freund registriert hat, die kumulative Spot- oder Vertragstransaktion Das Volumen überschreitet 200 USDT. <br>4. Eingeladene Freunde müssen die Aufladeaufgabe abschließen, bevor Sie die Belohnung für die Handelsaufgabe freischalten können. Wenn Ihr eingeladener Freund die Aufladeaufgabe nicht erfolgreich abschließt, können Sie die Belohnung auch nach der Transaktion nicht erhalten übersteigt 200 USDT.<br> 5. Ausgewiesener Aufladekanal: Gültige Aufladung. Nur On-Chain-Aufladungen, Aufladungen in gesetzlicher Währung, Kartenkäufe, C2C-Transaktionen und Zahlungen Dritter sind zulässig. Interne Überweisungen und rote Umschläge sind nicht in der effektiven Aufladung enthalten. 6. Einladende können bis zu 15 Gebührenabzugsgutscheine und 15 Bargeld-Blindbox-Prämien pro Monat erhalten.<br> 7. Gültigkeitsdauer: Bearbeitungsgebührenabzugsgutscheine müssen innerhalb von 14 Tagen nach Ausstellung abgeholt werden und sind 14 Tage nach Abholung gültig. Bitte achten Sie darauf, diese rechtzeitig zu erhalten und zu verwenden, um ein Ablaufen der Prämie zu vermeiden. Die Gültigkeitsdauer für die Einlösung der Blindbox-Prämie beträgt 90 Tage. Bitte lösen Sie die Bargeldcoupon-Prämie so schnell wie möglich nach Erhalt der Prämie ein. Der Bargeldcoupon ist 14 Tage lang gültig nach der Einlösung.<br> 8. Einladungen von derselben IP-Adresse oder demselben Gerät werden als Selbsteinladung betrachtet. Eine Selbsteinladung führt dazu, dass der Benutzer die erhaltenen Belohnungen und die Qualifikationen für den zukünftigen Erhalt von Belohnungen verliert. BeingDex behält sich die vor Recht, illegale Konten einzufrieren und die Vermögenswerte auf den Konten zu beschlagnahmen.<br>9. Wenn die Belohnungen ausgegeben werden, stellt das System automatisch fest, ob die beiden aktuellen Parteien den exklusiven Partnerstatus haben. Wenn der Einladende oder einer der Eingeladenen ein ist Exklusiver Partner, die Prämie steht im Widerspruch zur exklusiven Partner-Rabattprämie und die Prämie wird nicht ausgegeben. Darüber hinaus können Unterkonten nicht als unabhängige Konten an Aktivitäten teilnehmen und die Daten werden nicht mit dem Hauptkonto zusammengeführt.<br > 10. Die oben genannten Regeln treten am 11. Mai 2023 um 18:00 Uhr (UTC+8) in Kraft. BeingDex behält sich das Recht auf die endgültige Auslegung dieser Aktivität vor. Wenn böswilliges Verhalten oder illegales und unethisches Verhalten entdeckt wird, das Plattformschwachstellen ausnutzt , BeingDex hat das Recht, Benutzerkonten und Vermögenswerte zu verwalten.<br> 11. Sie dürfen nicht vorgeben, BeingDex-Beamter zu sein und irreführende Aussagen machen, einschließlich, aber nicht beschränkt auf Kaufschlüsselwörter wie "BeingDex", "BeingDex-Login", " BeingDex Official", "BeingDex C2C" In Suchmaschinen bewerben. Wer gegen die Anforderungen verstößt, wird von Prämien und Werbeaktionen ausgeschlossen.',
    t232: "Compliance und Sicherheit",
    t233: "BeingDex besteht auf der Implementierung eines umfassenden Compliance- und Sicherheits-Governance-Systems und befolgt strenge Standards und Prozesse, die vom Compliance-Beratungsteam formuliert wurden, um ein umfassendes Risikomanagement und -überwachung sicherzustellen.<br>Die Plattform führt regelmäßig umfassende Risikobewertungen durch, um potenzielle Risiken zu identifizieren Zu den Punkten gehören das Marktrisiko und das Betriebsrisiko. Implementieren Sie wirksame Risikomanagementstrategien, verfolgen und identifizieren Sie aktiv mögliche interne und externe Risiken und ergreifen Sie geeignete Reaktionsmaßnahmen. Für Risiken, die durch externe Faktoren verursacht werden, verwendet BeingDex fortschrittliche Verschlüsselungstechnologie, um die Datensicherheit zu schützen. Für interne Risiken , richten Sie einen strengen internen Kontrollmechanismus ein, einschließlich eines Autorisierungsmechanismus zur Klärung von Verantwortlichkeiten, und führen Sie regelmäßige interne und externe Audits durch.<br>Durch die regelmäßige Abstimmung mit lokalen Regulierungsbehörden und die Durchführung von Compliance-Überprüfungen umfasst dies auch inländische externe Gesetze und Vorschriften, insbesondere solche in Bezug auf Finanzdienstleistungen, Datenschutz und Geldwäschebekämpfung (AML), stellen die Compliance und Sicherheit des Unternehmensbetriebs sicher und stellen sicher, dass die Plattform allen geltenden Finanzvorschriften und -standards entspricht.",
    t234: "Compliance Management Framework",
    t235: "Identifikation",
    t236: "Bewertung",
    t237: "Ausführen",
    t238: "Bewertung",
    t239: "1. Compliance-Management",
    t240: "Unter der Aufsicht eines Teams von Compliance-Experten befolgt BeingDex strenge Compliance-Standards und -Protokolle, implementiert eine umfassende Compliance-Management-Struktur und führt eine effektive Identifizierung, Bewertung, Ausführung und Bewertung durch.<br>BeingDex erkennt und identifiziert aktiv externe Quellen und interne Risiken und ergreifen die erforderlichen Abhilfemaßnahmen. Externe Risiken beziehen sich auf Risiken, die durch externe Änderungen verursacht werden können, wie z. B. falsche Informationen, die durch Werbung Dritter für BeingDex-Agenten veröffentlicht werden.<br> Interne Risiken beziehen sich auf Risiken, die von innerhalb des Unternehmens ausgehen können Organisationsrisiken, wie unbefugtes, unangemessenes, illegales oder unethisches Verhalten interner Mitarbeiter.<br>BeingDex arbeitet mit lokalen Aufsichtsbehörden durch eine Kombination aus Bewertungen und jährlichen Compliance-Überprüfungen zusammen, um sicherzustellen, dass unsere Compliance-Standards den lokalen Anforderungen entsprechen.",
    t241: "2.eKYC-Technologie",
    t242: "BeingDex führt die elektronische Identitätsüberprüfung (eKYC) ein, um die Plattform zu sichern und potenziellen Betrug und illegale Risiken zu reduzieren. Darüber hinaus verfügt BeingDex über Sanktionen und Richtlinien zur Bekämpfung der Geldwäsche (AML), um alle relevanten Gerichtsbarkeiten einzuhalten Verhindern Sie Fälschungen oder andere kriminelle Aktivitäten auf der Plattform.<br>Effizienz ist für die Sorgfaltspflicht des Kunden (Customer Due Diligence, CDD) von entscheidender Bedeutung. Daher setzt BeingDex die eKYC-Technologie ein, um den Prozess zur Überprüfung der Benutzeridentität (KYC) unter der Prämisse der Compliance zu optimieren. <br>Dies Die Technologie ermöglicht die Gesichtserkennung und den automatischen Abgleich zwischen vom Benutzer bereitgestellten Identifikationen und Echtzeitporträts, wodurch gefälschte Identitäten verhindert und außerdem die Zeit für Benutzer, die persönliche Identitätsüberprüfung auf der BeingDex-Plattform durchzuführen, erheblich verkürzt wird.",
    t243: "2. Blockchain-Analyse",
    t244: "BeingDex setzt externe Blockchain-Analysetools ein, um Transaktionen auf der Plattform genau zu überwachen und das Risiko betrügerischer Aktivitäten und das Auftreten von Hochrisikobenutzern zu reduzieren*. Die unveränderliche und transparente Natur der Blockchain ermöglicht es uns, Transaktionen auf der Plattform umfassend zu erkennen Alle Transaktionen.<br>*Zu den Nutzern mit hohem Risiko gehören unter anderem:<br>- Kunden in sensiblen Ländern oder Regionen<br>- Regierungsbeamte<br>- Kunden aus sensiblen Branchen (z. B. kapitalintensive Unternehmen) <br >Basierend auf der Einschätzung unseres Risiko- und Governance-Teams werden wir verschiedene Maßnahmen gegen Benutzer mit hohem Risiko ergreifen, die je nach konkreter Situation die Beschlagnahme von Vermögenswerten, mehrere Überprüfungen oder Audits usw. umfassen können.",
    t245: "3.Netzwerksicherheit",
    t246: "BeingDex konsultiert unabhängige Netzwerksicherheitsexperten, um die Sicherheit und Stabilität der Plattform zu verbessern. Gleichzeitig werden zweimal im Jahr Netzwerkpenetrationstests und Schwachstellenbewertungen durchgeführt, um erkannte potenzielle Bedrohungen umgehend und schnell zu bewältigen.<br>Darüber hinaus Nach den oben genannten Tests verschlüsselt BeingDex außerdem alle sensiblen Daten, um Risiken wie Diebstahl, unbefugtem Zugriff oder Änderung vorzubeugen. Alle übertragenen oder gespeicherten Daten werden verschlüsselt und sicher im fehlertoleranten Speicher gespeichert",
    t247: "Vorgang erfolgreich",
    t248: "Alles gelesen",
    t249: "Zitate",
    t250: "Heutige Änderung",
    t251: "24H-Handelsvolumen",
    t252: "24H-Transaktionsvolumen",
    t253: "Beliebte Währungen",
    t254: "Neueste Währung",
    t255: "Die Währung mit dem größten Anstieg",
    t256: "Währung mit dem höchsten Handelsvolumen",
    t257: "Schnellere Transaktionen, bessere Vermögenswerte",
    t258: "Ihr zukünftiges Web3-Transaktions-Wallet",
    t259: "Superportal des Web3-Universums",
    t260: "Schließen Sie sich 12 Millionen Benutzern an, durchsuchen Sie ganz einfach den größten NFT-Markt und interagieren Sie sicher mit über 20.000 DApps auf BeingDex Wallet",
    t261: "Genießen Sie die umfassendste und benutzerfreundlichste NFT-Plattform",
    t262: "Aggregation mehrerer Mainstream-NFT-Märkte, Unterstützung der Batch-Auftragserteilung mit einem Klick und Kauf von NFTs in jeder Währung",
    t263: "Kauf",
    t264: "Blockchain überall geschehen lassen",
    t265: "Multi-Chain-Wallet, sicher und einfach zu bedienen, Blockchain-Eingang",
    t266: "Open-Source-Wallet",
    t267: "Open-Source-Wallet, selbsterhaltender privater Schlüssel, mehrschichtige Verschlüsselung",
    t268: "Folge deinem Herzen und fühle dich wohl",
    t269: "Kettenübergreifend, bequem, dezentral, Nachfrage aus einer Hand",
    t270: "Dezentrales Wallet",
    t271: "Trennung von heißen und kalten Vermögenswerten, sicher und bequem Token 40000+",
    t272: "Kryptoassets",
    t273: "Über 40.000 Krypto-Assets unterstützen verschiedene Assets für den Handel auf DEX.",
    t274: "Mehrfache Verschlüsselungstechnologie",
    t275: "Bewahren Sie Kryptowährungen sicher auf und kontrollieren Sie Ihr eigenes Vermögen.",
    t276: "Multiple-Gain-Modus",
    t277: "Abstecken, Mining, DeFi, Kettenspiele.",
    t278: "Selbstverwahrung von Vermögenswerten, Peer-to-Peer-Abgleich von Wallet-Transaktionen",
    t279: "Sicherheit ohne Unfälle und rein intelligente Vertragsausführung",
    t280: "Ursprüngliches dezentrales K-Linien-Diagramm, native Vorteile",
    t281: "Ihre Wahl ist die gleiche wie ihre",
    t282: "Vertrauen und Auswahl von über 1.000 führenden Unternehmen",
    t283: "Plug-in-Wallet",
    t284: "Tutorial zur Plug-in-Installation",
    t285: "Das weltweit führende Blockchain-Tool zur Verwaltung digitaler Vermögenswerte",
    t286: "Reine intelligente Vertragsausführung",
    t287: "Jetzt herunterladen",
    t288: "DApp Ökologischer Eingang",
    t289: "Entdecken Sie DeFi, GameFi usw. und spielen Sie schnell mit der DApp-Wirtschaft",
    t290: "Lass uns anfangen! Klicken Sie hier, um Vorschläge oder Feedback einzureichen",
    t291: "Mehr anzeigen",
    t292: "Token-Typ",
    t293: "BeingDex, Multi-Chain-gesteuerte<br>One-Stop-Asset-Management-Handelsplattform<br>sicher, effizient und kostengünstig",
    t294: "BeingDex Cross-Chain-Brücke",
    t295: "Deutsch",
    t296: "Noch nicht geöffnet",
    t297: "arbeiten",
    t298: "Geldbörse",
    t299: "Tausch",
    t300: "Dapp",
    t301: "Blog"
  }
}