export default {
  text: {
    t1: "Casa",
    t2: "Junte-se a nós",
    t3: "Google Store",
    t4: "Apple Store",
    t5: "Baixar aplicativo",
    t6: "Download do Chrome",
    t7: "Download local",
    t8: "Preço da moeda BDX",
    t9: "Volume de negociação",
    t10: "Usuário da comunidade",
    t11: "Número de transações",
    t12: "Volume total de transações BDX",
    t13: "Lista de crescimento",
    t14: "Lista de recusas",
    t15: "Nova Lista de Moedas",
    t16: "Lista de volumes de transações",
    t17: "nome",
    t18: "Último preço",
    t19: "preço",
    t20: "Aumento de hoje",
    t21: "Aumentar ou diminuir",
    t22: "Volume de negociação 24H",
    t23: "Transação",
    t24: "Ainda não há dados",
    t25: "Ver tudo",
    t26: "Seguro, eficiente, baixo custo",
    t27: "Atendimento ao cliente on-line",
    t28: "Cooperação Empresarial",
    t29: "Empresa",
    t30: "Sobre nós",
    t31: "Centro de Ajuda",
    t32: "Anúncio",
    t33: "Token BDX",
    t34: "produto",
    t35: "Comprar moedas",
    t36: "Carteira Web3",
    t37: "Serviço",
    t38: "Comentários",
    t39: "Solicitação de listagem de moeda",
    t40: "Convite de amigo",
    t41: "Divulgação Legal e de Riscos",
    t42: "Licença de conformidade",
    t43: "Política Antilavagem de Dinheiro",
    t44: "Política de Privacidade",
    t45: "Contrato do Usuário",
    t46: "Declaração Legal",
    t47: "Aviso de risco",
    t48: "Regra ST",
    t49: "carteira plug-in",
    t50: "Baixar carteira",
    t51: "Idioma",
    t52: "Sair",
    t53: "Conectar carteira",
    t54: "Carregando...",
    t55: "Chega...",
    t56: "Sobre SerDex",
    t57: "Por trás do BeingDex está um grupo de primeiros adotantes da tecnologia blockchain e que acreditam no desenvolvimento futuro do blockchain.",
    t58: "Desde 2018, estabelecemos uma bolsa de criptomoedas e estamos comprometidos em fornecer soluções de negociação seguras e completas para ajudar os usuários a negociar de maneira mais inteligente.",
    t59: "Plataforma de negociação descentralizada de correspondência de ordens pendentes de cadeia completa",
    t60: "Endereço registrado global",
    t61: "100.000+",
    t62: "30 milhões de USDT",
    t63: "Volume diário de negociação",
    t64: "Nossa História",
    t65: 'Este é um grupo de geeks que acreditam firmemente em blockchain e ativos criptografados. Em 2010, compramos nosso primeiro Bitcoin por meio da plataforma de comércio eletrônico OTC. Naquela época, estávamos nervosos e inquietos. À medida que o ciclo da indústria muda, os métodos de transação e as formas dos produtos continuam a inovar e a evoluir, apresentando uma situação em que Cex e Dex se desenvolvem simultaneamente. Mas, ao mesmo tempo, também percebemos que o Dex existente é limitado pelo seu mecanismo de modelo e não pode maximizar a eficiência dos ativos. <br>Ao mesmo tempo, como a indústria de criptografia tem uma influência cada vez mais ampla e profunda em todo o mundo, além das áreas desenvolvidas, cada vez mais pessoas de áreas com infra-estrutura financeira fraca estão começando a aderir, mas têm dificuldade em entender os complexos produtos financeiros e mecanismos algorítmicos tornaram-se uma lacuna que os impede de se conectarem a novos mundos e novos ativos. <br>BeingDex está comprometida em superar essa lacuna e construir produtos de aplicação de cadeia completa e ecologia por meio de novos contratos inteligentes. <br>Ser tem conotações como "existência", "essência" e "vida biológica", que expressam nosso espírito de explorar a origem das coisas, nossa prática fundamental de valor do produto e nossa busca final pela experiência do usuário. Nós nos encorajamos e, ao mesmo tempo, damos as boas-vindas a mais pessoas para abrirem suas mentes e adotarem ativos criptográficos, e ajudá-los a iniciar sua própria jornada de riqueza criptográfica por meio de serviços de produtos fáceis de usar e amigáveis.',
    t66: "Visão",
    t67: "Criar um mundo de riqueza futura mais livre, mais justo e mais transparente através da Web3",
    t68: "Missão",
    t69: "Crie a plataforma de negociação definitiva que todos possam usar e se torne o provedor líder de serviços financeiros de ativos digitais do setor",
    t70: "Nossos valores",
    t71: "Usuário primeiro",
    t72: "Preste atenção às necessidades e atitudes de cada usuário, comunique-se de forma objetiva e sincera e divulgue as informações da plataforma em tempo hábil.",
    t73: "Integridade e rigor",
    t74: 'Aderimos ao princípio de" não fazer o mal "e conquistamos a confiança do mercado e dos usuários por meio da responsabilidade e da responsabilidade.',
    t75: "Inovação e empreendedorismo",
    t76: "Produtos e serviços extremos e construção de vantagens estruturais são nossa eterna busca.",
    t77: "Comece com o fim em mente",
    t78: "Faça coisas de longo prazo com parceiros de longo prazo, compreenda o processo, crie condições, preste atenção aos resultados do feedback e atinja continuamente metas marcantes.",
    t79: "Nossa equipe",
    t80: "Com mais de 150 funcionários de mais de 10 países, a equipe BeingDEX conta com talentos seniores de todos os cantos do planeta, o que nos dá um alcance verdadeiramente global.",
    t81: "Nossos serviços",
    t82: "SerDEX",
    t83: "BeingDex é uma nova bolsa descentralizada baseada no desenvolvimento de múltiplas cadeias. Ela adota um modelo de correspondência de pedidos na cadeia e a ponte entre cadeias suporta cadeias públicas BSC, TRON e OKX.",
    t84: "Ser carteira",
    t85: "Being Wallet adota dois mecanismos principais de segurança: autocustódia dos ativos do usuário e anonimato completo. Sua tecnologia de carteira subjacente oferece suporte a múltiplas proteções de segurança, como criptografia biométrica local e isolamento de segurança, e oferece suporte ao gerenciamento de ativos de múltiplas cadeias para proteger a segurança dos usuários transações.",
    t86: "Ser NFT",
    t87: "Sendo NFT suporta ETH, BSC, Mango, TRON, Polygon, Solana emissão multi-cadeia de NFT com um clique, transações e outras atividades são concluídas através do protocolo de cadeia sem intervenção de terceiros. O NFT organizado pelo DAO é armazenado na carteira. Fundição em cadeia, transações inteligentes, seguras e convenientes.",
    t88: "Comece sua jornada criptográfica agora!",
    t89: "Negocie em uma plataforma confiável para milhões de usuários.",
    t90: "Upload bem-sucedido",
    t91: "Falha no upload",
    t92: "Por favor selecione a cadeia pública à qual você pertence",
    t93: "Por favor, insira o nome do projeto",
    t94: "Por favor carregue o logotipo",
    t95: "Por favor, insira a abreviatura do token",
    t96: "Por favor, insira o endereço do contrato",
    t97: "Insira a quantidade de emissão",
    t98: "Por favor, insira o link do site oficial",
    t99: "Por favor, insira seu endereço de e-mail",
    t100: "Por favor, insira as informações do seu token",
    t101: "Envio bem-sucedido",
    t102: "Aplicativo de listagem de moeda BeingDex",
    t103: "Obrigado por sua atenção ao BeingDex Exchange. Preencha o formulário de inscrição e forneça informações válidas. Analisaremos seu projeto com base nas informações que você forneceu. Envie esta inscrição e seu projeto será enviado ao departamento de listagem de moedas . Revisão. Depois de passar na revisão preliminar, providenciaremos um especialista em listagem de moedas para compartilhar com você o processo e as técnicas de listagem de moedas e orientá-lo durante o processo de listagem de moedas.",
    t104: "Indica necessário",
    t105: "Cadeia pública à qual pertence",
    t106: "Nome do projeto",
    t107: "Abreviatura do token",
    t108: "Endereço do contrato",
    t109: "Quantidade emitida",
    t110: "Link do site oficial",
    t111: "Caixa de correio",
    t112: "Informações do token",
    t113: "Por favor, insira as informações do seu token, não mais que 120 caracteres",
    t114: "Enviar",
    t115: "Enviar após conectar à carteira",
    t116: "Limpar conteúdo do formulário",
    t117: "BDX lidera a revolução na indústria criptográfica",
    t118: "Conecte seus ativos, aplicativos DeFi e NFTs para ajudá-lo a desbloquear o mundo Web3 rapidamente",
    t119: "Obtenha BDX com um clique",
    t120: "Documento Branco BDX",
    t121: "Introdução ao BDX",
    t122: "Segure BDX e desfrute de benefícios infinitos",
    t123: "Nova assinatura",
    t124: "Serviço preferencial",
    t125: "Mecanismo de deflação",
    t126: "Novo on-line",
    t127: "Planejamento",
    t128: "Obter BDX",
    t129: "Informações de lançamento de BDX",
    t130: "Seguro, fácil de usar e intimamente conectado a culturas e ideologias de todo o mundo",
    t131: "Nome do token",
    t132: "Símbolo de token",
    t133: "Cadeia proprietária",
    t134: "Endereço do contrato",
    t135: "Preço de emissão",
    t136: "Fornecimento de circulação",
    t137: "Oferta total",
    t138: "Data de emissão",
    t139: "Substituir BDX",
    t140: "Para resgate de tokens BDX existentes",
    t141: "Motivação da equipe",
    t142: "2% desbloqueado a cada 6 meses, será totalmente desbloqueado em 5 anos (60 meses)",
    t143: "Investimento económico e ecológico",
    t144: "Vá para o ecossistema BeingDex para investimento de fundos",
    t145: "Promoção da marca",
    t146: "Máximo de lançamentos por ano",
    t147: "Entrada do usuário",
    t148: "Fundo de Proteção",
    t149: "Para compensação por potenciais acidentes na plataforma",
    t150: "Trabalhe conosco para criar um ecossistema BDX seguro e confiável e promover o rápido desenvolvimento do Web3",
    t151: "Obtenha BDX com um clique",
    t152: "Recomendado",
    t153: "Blog mais recente",
    t154: "Ainda não há dados",
    t155: "Loja de aplicativos DApp",
    t156: "Pesquisar",
    t157: "Selecionar categoria",
    t158: "Isenção de responsabilidade importante",
    t159: 'Todo o conteúdo fornecido neste site, sites com hiperlinks, aplicativos relacionados, fóruns, blogs, contas de mídia social e outras plataformas (o" Site ") é para sua informação geral obtida apenas de fontes de terceiros. Não somos responsáveis ​​por nossos conteúdo Nenhuma garantia de qualquer tipo é oferecida, incluindo, entre outros, precisão e atualidade. Nenhuma parte do conteúdo que fornecemos constitui aconselhamento financeiro, aconselhamento jurídico ou qualquer outra forma de aconselhamento e é projetado para satisfazer sua confiança específica para qualquer finalidade. Qualquer Qualquer uso ou confiança em nosso conteúdo é feito por sua própria conta e risco. Você deve realizar sua própria pesquisa, revisão, análise e verificação antes de confiar em nosso conteúdo. A negociação é uma atividade de alto risco que pode resultar em perdas significativas, portanto consulte seu consultor financeiro antes de tomar qualquer decisão. Nada em nosso site é uma solicitação ou oferta.',
    t160: "Por favor, insira os detalhes da sugestão",
    t161: "Envio bem-sucedido",
    t162: "Cada uma de suas sugestões",
    t163: "Vamos ouvir com atenção e tratar isso com seriedade",
    t164: "Comentários",
    t165: "Se você encontrar alguma falha ou vulnerabilidade de segurança, envie-nos um feedback oportuno",
    t166: "Se você tiver alguma dúvida, consulte a Central de Ajuda para obter respostas às perguntas mais frequentes.",
    t167: "O que você acha da nossa experiência com o produto?",
    t168: "Não é uma boa experiência!",
    t169: "Para ser melhorado!",
    t170: "Bastante satisfatório!",
    t171: "Super incrível!",
    t172: "Enviar sugestão",
    t173: "Bem-vindo a compartilhar suas sugestões de produtos. BeingDex levará seus comentários a sério. Se você tiver dúvidas urgentes, entre em contato com o atendimento ao cliente.",
    t174: "Categoria sugerida",
    t175: "Recomendações de segurança",
    t176: "Sugestões de recursos",
    t177: "Sugestões de Design",
    t178: "Sugestões de operação",
    t179: "Outras sugestões",
    t180: "Detalhes da sugestão",
    t181: "Por favor, insira seu feedback, não mais que 500 caracteres",
    t182: "Carregar fotos (opcional)",
    t183: "Por favor, carregue capturas de tela relacionadas ao problema. O formato da imagem é JPG ou PNG e o tamanho não deve exceder 2M",
    t184: "Informações de contato (opcional)",
    t185: "Por favor, insira informações de contato",
    t186: "Confirmar envio",
    t187: "Enviar após conectar à carteira",
    t188: "Salvar rascunho",
    t189: "Como funciona?",
    t190: "Enviar sugestão",
    t191: "Revisão da equipe",
    t192: "Distribuir recompensas",
    t193: "BeingDex atende usuários em todo o mundo. Consideramos o desenvolvimento seguro e estável da plataforma como nossa principal prioridade. Aguardamos suas sugestões valiosas. Vamos melhorar a qualidade do produto e criar um futuro melhor juntos.",
    t194: "Um protocolo em que os usuários Web3 podem confiar<br>permite que os usuários Defi concluam transações facilmente",
    t195: "Autocustódia de ativos, transações de correspondência ponto a ponto de carteira",
    t196: "Segurança com zero acidentes e execução de contrato puramente inteligente",
    t197: "Gráfico de linha K descentralizado original, vantagens nativas",
    t198: "Criptomoedas Populares",
    t199: "Ecologia BeingDex",
    t200: "Gerencie seus ativos facilmente",
    t201: "BeingDex é uma plataforma de negociação descentralizada que combina carteira de pedidos construída com contratos puramente inteligentes. O layout ecológico geral cobre Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, pools de mineração e outras indústrias.",
    t202: "Um produto descentralizado que integra carteira e transação",
    t203: "BeingDex - uma plataforma de negociação descentralizada de correspondência de ordens construída com contratos puramente inteligentes",
    t204: "Aplicação - Produtos ecológicos diversificados BeingDex",
    t205: "Carteira - Gerencie seus ativos multi-chain",
    t206: "A negociação deve ser feita a qualquer hora e em qualquer lugar",
    t207: "Baixe o aplicativo e nós o ajudaremos a negociar 24 horas por dia, 7 dias por semana",
    t208: "Digitalizar para baixar",
    t209: "Recursos de mídia",
    t210: "Conformidade e Política",
    t211: "Certificação oficial global de conformidade de segurança para garantir a segurança dos ativos do usuário",
    t212: "Obter licença MSB dos EUA",
    t213: "28 de novembro de 2023",
    t214: "O pedido de licença DMCC de Dubai está pendente",
    t215: "Pedido de licenças da Comissão Reguladora de Valores Mobiliários de Hong Kong/VARA/DIFC/ADGM/US MTL etc.",
    t216: "Nossos parceiros",
    t217: "Mais de 15 anos de experiência em tecnologia da informação.<br>Computação em nuvem/DevOps sênior altamente qualificado e arquiteto de aplicativos com experiência em AWS, GCP, Azure e ferramentas DevOps/SystemOps/DevOps e amplo conhecimento de serviços.<br>8 + anos de experiência trabalhando como arquiteto de nuvem/DevSecOps/aplicações no setor financeiro<br>Projetei o primeiro protótipo de carteira de hardware de criptomoeda do Canadá para minha startup Blockchain Mind.",
    t218: "Convide amigos e ganhe até<br>9.000 USDT",
    t219: "Link de convite",
    t220: "Convidar agora",
    t221: "Convidar após conectar à carteira",
    t222: "Registro de convite",
    t223: "Nome de usuário",
    t224: "Hora de registro",
    t225: "Recarga atinge o padrão",
    t226: "Transação atende ao padrão",
    t227: "Bônus de depósito",
    t228: "Caixa cega",
    t229: "Eventos Populares",
    t230: "Regras",
    t231: '1. Quando o amigo convidado conclui a tarefa de recarga, quem convida pode receber um cupom de desconto de 100 USDT. Depois que o amigo convidado conclui a tarefa de transação, quem convida pode sortear aleatoriamente uma recompensa de caixa cega de 5 a 500 USDT.<br > 2. Tarefa de recarga: Dentro de 30 dias após o registro do amigo convidado, recarregue através dos canais designados e o depósito líquido cumulativo excede 50USDT.<br> 3. Tarefas de negociação: Dentro de 30 dias após o registro do amigo convidado, o spot cumulativo ou transação de contrato o volume excede 200USDT. <br>4. Os amigos convidados devem concluir a tarefa de recarga antes que você possa desbloquear a recompensa da tarefa de negociação. Se o seu amigo convidado não concluir a tarefa de recarga com êxito, você não poderá obter a recompensa mesmo que a transação excede 200USDT.<br> 5. Canal de recarga designado: recarga válida Somente recargas em rede, recargas em moeda legal, compras com cartão, transações C2C e pagamentos de terceiros são permitidas. Transferências internas e envelopes vermelhos não estão incluídos na recarga efetiva. 6. Os convidados podem receber até 15 cupons de dedução de taxas e 15 prêmios em dinheiro por mês Blind Box.<br> 7. Período de validade: Os cupons de dedução de taxas de manuseio devem ser coletados em até 14 dias após a emissão e são válidos por 14 dias após a coleta. Preste atenção ao recebê-los e usá-los a tempo para evitar a expiração da recompensa; o período de validade para o resgate da recompensa da caixa cega é de 90 dias. Resgate a recompensa do cupom em dinheiro o mais rápido possível após receber a recompensa. O cupom em dinheiro é válido por 14 dias após o resgate.<br> 8. Convites do mesmo endereço IP ou dispositivo serão considerados como autoconvite. O autoconvite fará com que o usuário perca as recompensas obtidas e as qualificações para receber recompensas no futuro. BeingDex reserva-se o direito de congelar contas ilegais e confiscar os ativos das contas.<br>9. Quando as recompensas forem emitidas, o sistema determinará automaticamente se as duas partes atuais têm status de parceiro exclusivo. Se o autor do convite ou Se algum dos convidados for um parceiro exclusivo, a recompensa entrará em conflito com a recompensa do desconto do parceiro exclusivo e a recompensa não será emitida. Além disso, as subcontas não podem participar de atividades como contas independentes e os dados não serão mesclados na conta principal.<br > 10. As regras acima entrarão em vigor a partir das 18h do dia 11 de maio de 2023 (UTC+8). A BeingDex reserva-se o direito de interpretação final desta atividade. Caso seja descoberto qualquer comportamento malicioso ou ilegal e antiético que explore vulnerabilidades da plataforma , BeingDex terá o direito de gerenciar contas e ativos de usuários.<br> 11. Você não pode fingir ser oficial do BeingDex e fazer declarações enganosas, incluindo, mas não se limitando a, comprar palavras-chave como "BeingDex", "BeingDex Login", " BeingDex Official", "BeingDex C2C" Promova nos motores de busca. Aqueles que violarem os requisitos serão desqualificados para recompensas e promoções.',
    t232: "Conformidade e Segurança",
    t233: "BeingDex insiste na implementação de um sistema abrangente de conformidade e governança de segurança e segue padrões e processos rigorosos formulados pela equipe de consultoria de conformidade para garantir gerenciamento e monitoramento de riscos abrangentes.<br>A plataforma realiza regularmente avaliações de risco abrangentes para identificar riscos potenciais Os pontos incluem risco de mercado e risco operacional. Implemente estratégias eficazes de gerenciamento de risco, rastreie e identifique ativamente possíveis riscos internos e externos e tome medidas de resposta apropriadas. Para riscos causados ​​por fatores externos, a BeingDex usará criptografia avançada A tecnologia protege a segurança dos dados. Para riscos internos , estabelecer um mecanismo de controle interno rigoroso, incluindo um mecanismo de autorização para esclarecer responsabilidades, e realizar auditorias internas e externas regulares.<br>Ao coordenar regularmente com agências reguladoras locais e realizar análises de conformidade, isso inclui leis e regulamentos externos nacionais, especialmente aqueles relativos serviços financeiros, proteção de dados e combate à lavagem de dinheiro (AML), garantem a conformidade e a segurança das operações da empresa e garantem que a plataforma esteja em conformidade com todos os regulamentos e padrões financeiros aplicáveis.",
    t234: "Estrutura de Gestão de Conformidade",
    t235: "Identificação",
    t236: "Avaliação",
    t237: "Executar",
    t238: "avaliação",
    t239: "1. Gestão de conformidade",
    t240: "Sob a supervisão de uma equipe de especialistas em conformidade, o BeingDex segue rígidos padrões e protocolos de conformidade, implementa uma estrutura abrangente de gerenciamento de conformidade e conduz identificação, avaliação, execução e avaliação eficazes.<br>BeingDex detecta e identifica ativamente fontes externas e riscos internos e tomar as medidas corretivas necessárias. Riscos externos referem-se a riscos que podem ser causados ​​por mudanças externas, como informações erradas publicadas por anúncios de terceiros de agentes BeingDex.<br> Os riscos internos referem-se a riscos que podem vir de dentro do riscos da organização, como conduta não autorizada, inadequada, ilegal ou antiética por parte de funcionários internos.<br>BeingDex trabalha com reguladores locais por meio de uma combinação de avaliações e revisões anuais de conformidade para garantir que nossos padrões de conformidade atendam aos requisitos locais.",
    t241: "Tecnologia 2.eKYC",
    t242: "BeingDex adota verificação eletrônica de identidade (eKYC) para proteger a plataforma e reduzir possíveis fraudes e riscos ilegais. Além disso, BeingDex possui sanções e políticas anti-lavagem de dinheiro (AML) em vigor para cumprir todas as jurisdições relevantes, e evitar falsificação ou outras atividades criminosas na plataforma.<br>A eficiência é crucial para a Due Diligence do Cliente (CDD), portanto, a BeingDex adota a tecnologia eKYC para otimizar o processo de verificação de identidade do usuário (KYC) sob a premissa de conformidade. <br>Isso A tecnologia permite o reconhecimento facial e a correspondência cruzada automática entre a identificação fornecida pelo usuário e retratos em tempo real, evitando assim identidades falsas e também reduzindo significativamente o tempo para os usuários realizarem a verificação de identidade pessoal na plataforma BeingDex.",
    t243: "2. Análise de blockchain",
    t244: "BeingDex implanta ferramentas externas de análise de blockchain para monitorar de perto as transações na plataforma e reduzir o risco de atividades fraudulentas e o surgimento de usuários de alto risco*. A natureza imutável e transparente do blockchain nos permite detectar de forma abrangente as transações na plataforma Todas as transações.<br>*Usuários de alto risco incluem, mas não estão limitados a:<br>- Clientes em países ou regiões sensíveis<br>- Funcionários do governo<br>- Clientes de setores sensíveis (como empresas de capital intensivo) <br >Com base na avaliação da nossa equipe de risco e governança, tomaremos diversas medidas contra usuários de alto risco, que podem incluir apreensão de ativos, múltiplas revisões ou auditorias, etc., dependendo da situação específica.",
    t245: "3.Segurança de rede",
    t246: "BeingDex consulta especialistas independentes em segurança de rede para melhorar a segurança e a estabilidade da plataforma. Ao mesmo tempo, testes de penetração de rede e avaliações de vulnerabilidade são realizados duas vezes por ano para lidar prontamente e rapidamente com ameaças potenciais detectadas.<br>Além de Após os testes acima, o BeingDex também criptografa todos os dados confidenciais para evitar riscos como roubo, acesso não autorizado ou modificação. Todos os dados transferidos ou salvos são criptografados e armazenados com segurança em um armazenamento tolerante a falhas.",
    t247: "Operação bem sucedida",
    t248: "Tudo lido",
    t249: "Citações",
    t250: "Mudança de hoje",
    t251: "Volume de negociação 24 horas",
    t252: "Volume de transações 24H",
    t253: "Moedas populares",
    t254: "Moeda mais recente",
    t255: "A moeda com maior valorização",
    t256: "Moeda com maior volume de negociação",
    t257: "Transações mais rápidas, melhores ativos",
    t258: "Sua futura carteira de transações Web3",
    t259: "Super portal do universo Web3",
    t260: "Junte-se a 12 milhões de usuários, navegue facilmente no maior mercado NFT e interaja com segurança com mais de 20.000 DApps na carteira BeingDex",
    t261: "Aproveite a plataforma NFT mais abrangente e fácil de usar",
    t262: "Agregação de vários mercados NFT convencionais, suporte para colocação de pedidos em lote com um clique e compra de NFTs em qualquer moeda",
    t263: "Comprar",
    t264: "Deixe o blockchain acontecer em todos os lugares",
    t265: "Carteira multi-cadeia, segura e fácil de usar, entrada blockchain",
    t266: "Carteira de código aberto",
    t267: "Carteira de código aberto, chave privada autossustentável, criptografia multicamadas",
    t268: "Siga seu coração e sinta-se à vontade",
    t269: "Cross-chain, conveniente, descentralizado, demanda única",
    t270: "Carteira descentralizada",
    t271: "Separação de ativos quentes e frios, Token 40000+ seguro e conveniente",
    t272: "Criptoativos",
    t273: "Mais de 40.000 ativos criptográficos suportam vários ativos para negociação em DEX.",
    t274: "Tecnologia de criptografia múltipla",
    t275: "Armazene criptomoedas com segurança e controle seus próprios ativos.",
    t276: "Modo de ganho múltiplo",
    t277: "Estaqueamento, mineração, DeFi, jogos em cadeia.",
    t278: "Autocustódia de ativos, correspondência ponto a ponto de transações de carteira",
    t279: "Segurança com zero acidentes e execução de contrato puramente inteligente",
    t280: "Gráfico de linha K descentralizado original, vantagens nativas",
    t281: "Sua escolha é igual à deles",
    t282: "Confiança e escolha de mais de 1.000 empresas líderes",
    t283: "carteira plug-in",
    t284: "Tutorial de instalação do plug-in",
    t285: "A ferramenta líder mundial de gerenciamento de ativos digitais blockchain",
    t286: "Execução de contrato puramente inteligente",
    t287: "Baixar agora",
    t288: "Entrada Ecológica DApp",
    t289: "Explore DeFi, GameFi, etc. e brinque rapidamente com a economia DApp",
    t290: "Vamos começar! Clique aqui para enviar sugestões ou comentários",
    t291: "Ver mais",
    t292: "Tipo de token",
    t293: "BeingDex, plataforma de negociação de gerenciamento de ativos completa<br>acionada por múltiplas cadeias<br>segura, eficiente e de baixo custo",
    t294: "Ponte de cadeia cruzada BeingDex",
    t295: "Português",
    t296: "Ainda não aberto",
    t297: "operar",
    t298: "carteira",
    t299: "Trocar",
    t300: "Dapp",
    t301: "Blogue"
  }
}