export default {
  text: {
    t1: "Hem",
    t2: "Gå med oss",
    t3: "Google Store",
    t4: "Apple Store",
    t5: "Ladda ner appen",
    t6: "Chrome Download",
    t7: "Lokal nedladdning",
    t8: "BDX valutapris",
    t9: "Handelsvolym",
    t10: "Community User",
    t11: "Antal transaktioner",
    t12: "BDX total transaktionsvolym",
    t13: "Tillväxtlista",
    t14: "Avvisa lista",
    t15: "Ny myntlista",
    t16: "Transaktionsvolymlista",
    t17: "namn",
    t18: "Senaste pris",
    t19: "pris",
    t20: "Dagens ökning",
    t21: "Öka eller minska",
    t22: "24H handelsvolym",
    t23: "Transaktion",
    t24: "Inga data ännu",
    t25: "Visa alla",
    t26: "Säker, effektiv, låg kostnad",
    t27: "Kundtjänst online",
    t28: "Affärssamarbete",
    t29: "Företag",
    t30: "Om oss",
    t31: "Hjälpcenter",
    t32: "Meddelande",
    t33: "BDX Token",
    t34: "produkt",
    t35: "Köp mynt",
    t36: "Web3 plånbok",
    t37: "Service",
    t38: "Feedback",
    t39: "Ansökan om valutanotering",
    t40: "Väninbjudan",
    t41: "Juridisk information och riskupplysning",
    t42: "Compliance license",
    t43: "Anti-penningtvättspolicy",
    t44: "Sekretesspolicy",
    t45: "Användaravtal",
    t46: "Legal Statement",
    t47: "Riskvarning",
    t48: "ST-regel",
    t49: "plug-in plånbok",
    t50: "Ladda ner plånbok",
    t51: "Språk",
    t52: "Logga ut",
    t53: "Anslut plånbok",
    t54: "Laddar...",
    t55: "Inga mer...",
    t56: "Om BeingDex",
    t57: "Bakom BeingDex står en grupp tidiga användare av blockchain-teknik och som tror på den framtida utvecklingen av blockchain.",
    t58: "Sedan 2018 har vi etablerat en kryptovalutabörs och har förbundit oss att tillhandahålla säkra handelslösningar för att hjälpa användare att handla smartare.",
    t59: "Väntande ordermatchning i hela kedjan decentraliserad handelsplattform",
    t60: "Global registrerad adress",
    t61: "100 000+",
    t62: "30 miljoner USDT",
    t63: "Daglig handelsvolym",
    t64: "Vår berättelse",
    t65: 'Det här är en grupp nördar som har en fast tro på blockchain och krypterade tillgångar. 2010 köpte vi vår första Bitcoin via e-handels OTC-plattformen. Vid den tiden var vi nervösa och oroliga. När branschens cykel förändras fortsätter transaktionsmetoder och produktformer att förnyas och utvecklas, vilket presenterar en situation där Cex och Dex utvecklas samtidigt. Men samtidigt inser vi också att den befintliga Dex är begränsad av sin modellmekanism och inte kan maximera tillgångens effektivitet. <br>Samtidigt som krypteringsindustrin har ett allt bredare och djupare inflytande runt om i världen, förutom utvecklade områden, börjar fler och fler människor från områden med svag finansiell infrastruktur ansluta sig, men de har svårt att förstå komplexa finansiella produkter och algoritmiska mekanismer har blivit en lucka som hindrar dem från att ansluta till nya världar och nya tillgångar. <br>BeingDex har åtagit sig att överbrygga denna klyfta och bygga applikationsprodukter och ekologi i hela kedjan genom nya smarta kontrakt. <br>Being har konnotationer som "existens", "essens" och "biologiskt liv", vilket uttrycker vår anda av att utforska sakers ursprung, vår grundläggande praxis för produktvärde och vår ultimata strävan efter användarupplevelse. Vi uppmuntrar oss själva och samtidigt välkomnar vi fler människor att öppna sina sinnen och omfamna kryptotillgångar och hjälpa dem att starta sin egen kryptorikedomsresa genom lättanvända och vänliga produkttjänster.',
    t66: "Vision",
    t67: "Skapa en friare, mer rättvis och mer transparent framtida välståndsvärld genom Web3",
    t68: "Uppdrag",
    t69: "Skapa den ultimata handelsplattformen som alla kan använda och bli den ledande leverantören av finansiella tjänster för digitala tillgångar i branschen",
    t70: "Våra värderingar",
    t71: "Användaren först",
    t72: "Var uppmärksam på varje användares behov och attityder, kommunicera objektivt och ärligt och släpp plattformsinformation i tid.",
    t73: "Integritet och rigor",
    t74: 'Vi följer principen om "gör inte ont" och vinner marknadens och användarnas förtroende genom ansvar och ansvar.',
    t75: "Innovation och företagsamhet",
    t76: "Extrema produkter och tjänster och byggnadsstrukturella fördelar är vår eviga strävan.",
    t77: "Börja med slutet i åtanke",
    t78: "Gör långsiktiga saker med långsiktiga partners, greppa processen, skapa förutsättningar, var uppmärksam på feedbackresultat och uppnå kontinuerligt milstolpemål.",
    t79: "Vårt team",
    t80: "Med över 150 anställda från över 10 länder har BeingDEX-teamet seniora talanger från alla hörn av planeten, vilket ger oss en verkligt global räckvidd.",
    t81: "Våra tjänster",
    t82: "BeingDEX",
    t83: "BeingDex är en ny decentraliserad börs baserad på utveckling av flera kedjor. Den använder en modell för matchning av beställningar i kedjan och den tvärkedjebrygga stöder de offentliga kedjorna BSC, TRON och OKX.",
    t84: "Being Wallet",
    t85: "Being Wallet använder två viktiga säkerhetsmekanismer: självvård av användartillgångar och fullständig anonymitet. Dess underliggande plånboksteknologi stöder flera säkerhetsskydd såsom lokal biometrisk kryptering och säkerhetsisolering, och stöder tillgångshantering med flera kedjor för att skydda användarnas säkerhet transaktioner.",
    t86: "Att vara NFT",
    t87: "Att vara NFT stöder ETH, BSC, Mango, TRON, Polygon, Solana multi-chain one-click-emission av NFT, transaktioner och andra aktiviteter slutförs genom kedjeprotokollet utan ingripande från tredje part. NFT som organiseras av DAO är lagras i plånboken. Casting i kedjan, intelligenta transaktioner, säkert och bekvämt.",
    t88: "Starta din kryptoresa nu!",
    t89: "Handla på en plattform som miljontals användare litar på.",
    t90: "Uppladdningen lyckades",
    t91: "Uppladdning misslyckades",
    t92: "Välj den offentliga kedjan du tillhör",
    t93: "Vänligen ange projektnamnet",
    t94: "Vänligen ladda upp logotyp",
    t95: "Vänligen ange tokenförkortningen",
    t96: "Vänligen ange kontraktsadressen",
    t97: "Vänligen ange emissionskvantiteten",
    t98: "Vänligen ange den officiella webbplatslänken",
    t99: "Vänligen ange din e-postadress",
    t100: "Vänligen ange din tokeninformation",
    t101: "Sändningen lyckades",
    t102: "BeingDex valutanoteringsapplikation",
    t103: "Tack för din uppmärksamhet på BeingDex Exchange. Vänligen fyll i ansökningsformuläret och ange giltig information. Vi kommer att granska ditt projekt baserat på den information du angett. Skicka in den här ansökan och ditt projekt kommer att skickas till valutalistningsavdelningen . Granskning. När du har klarat den preliminära granskningen kommer vi att ordna en valutanoteringsspecialist som delar valutanoteringsprocessen och teknikerna med dig och guidar dig genom valutanoteringsprocessen.",
    t104: "Indikerar nödvändigt",
    t105: "Offentlig kedja som den tillhör",
    t106: "Projektnamn",
    t107: "Token förkortning",
    t108: "Kontraktsadress",
    t109: "Utgivningskvantitet",
    t110: "Officiell webbplatslänk",
    t111: "Mailbox",
    t112: "Token information",
    t113: "Vänligen ange din tokeninformation, inte mer än 120 tecken",
    t114: "Skicka",
    t115: "Skicka efter anslutning till plånbok",
    t116: "Rensa formulärinnehåll",
    t117: "BDX leder revolutionen inom kryptoindustrin",
    t118: "Anslut dina tillgångar, DeFi-applikationer och NFT:er för att hjälpa dig låsa upp Web3-världen snabbt",
    t119: "Hämta BDX med ett klick",
    t120: "BDX White Paper",
    t121: "Introduktion till BDX",
    t122: "Håll BDX och njut av oändliga fördelar",
    t123: "Ny prenumeration",
    t124: "Företrädestjänst",
    t125: "Deflationsmekanism",
    t126: "Ny online",
    t127: "Planering",
    t128: "Hämta BDX",
    t129: "BDX release information",
    t130: "Säker, lätt att använda och nära kopplad till kulturer och ideologier runt om i världen",
    t131: "Tokennamn",
    t132: "Token symbol",
    t133: "Ägande kedja",
    t134: "Kontraktsadress",
    t135: "Emissionspris",
    t136: "Cirkulationsförsörjning",
    t137: "Totalt utbud",
    t138: "Utgivningsdatum",
    t139: "Ersätt BDX",
    t140: "För inlösen av befintliga BDX-tokens",
    t141: "Team Motivation",
    t142: "2 % upplåst var sjätte månad, kommer att vara helt upplåst om 5 år (60 månader)",
    t143: "Ekonomiska och ekologiska investeringar",
    t144: "Gå till BeingDex ekosystem för fondinvestering",
    t145: "Varumärkeskampanj",
    t146: "Maximala utsläpp per år",
    t147: "Användarinmatning",
    t148: "Skyddsfond",
    t149: "För kompensation för potentiella olyckor på plattformen",
    t150: "Arbeta med oss ​​för att skapa ett säkert och pålitligt BDX-ekosystem och främja den snabba utvecklingen av Web3",
    t151: "Hämta BDX med ett klick",
    t152: "Rekommenderas",
    t153: "Senaste bloggen",
    t154: "Inga data ännu",
    t155: "DApp Application Store",
    t156: "Sök",
    t157: "Välj kategori",
    t158: "Viktig ansvarsfriskrivning",
    t159: 'Allt innehåll som tillhandahålls på denna webbplats, hyperlänkade webbplatser, relaterade applikationer, forum, bloggar, konton för sociala medier och andra plattformar ("Webbplatsen") är endast för din allmänna information som erhållits från tredje parts källor. Vi är inte ansvariga för vår innehåll Inga garantier av något slag lämnas, inklusive men inte begränsat till noggrannhet och valuta. Ingen del av innehållet vi tillhandahåller utgör finansiell rådgivning, juridisk rådgivning eller någon annan form av rådgivning och är utformad för att tillfredsställa din specifika tillit för något syfte. All användning av eller beroende av vårt innehåll sker på egen risk och eget gottfinnande. Du bör göra din egen forskning, granskning, analys och verifiering innan du förlitar dig på vårt innehåll. Handel är en högriskaktivitet som kan resultera i betydande förluster , så vänligen rådfråga din finansiella rådgivare innan du fattar några beslut. Ingenting på vår webbplats är en uppmaning eller ett erbjudande.',
    t160: "Vänligen ange förslagsinformationen",
    t161: "Sändningen lyckades",
    t162: "Var och en av dina förslag",
    t163: "Vi kommer att lyssna noga och behandla det seriöst",
    t164: "Feedback",
    t165: "Om du hittar några säkerhetsbrister eller sårbarheter, vänligen ge oss feedback i tid",
    t166: "Om du har några frågor, kontakta hjälpcentret för svar på vanliga frågor.",
    t167: "Vad tycker du om vår produktupplevelse?",
    t168: "Inte en bra upplevelse!",
    t169: "Ska förbättras!",
    t170: "Ganska tillfredsställande!",
    t171: "Superhäftigt!",
    t172: "Skicka förslag",
    t173: "Välkommen att dela med dig av dina produktförslag. BeingDex tar din feedback på allvar. Om du har brådskande frågor, vänligen kontakta kundtjänst.",
    t174: "Föreslagen kategori",
    t175: "Säkerhetsrekommendationer",
    t176: "Funktionsförslag",
    t177: "Designförslag",
    t178: "Operationsförslag",
    t179: "Andra förslag",
    t180: "Förslagsdetaljer",
    t181: "Vänligen ange din feedback, högst 500 tecken",
    t182: "Ladda upp bilder (valfritt)",
    t183: "Vänligen ladda upp skärmdumpar relaterade till problemet. Bildformatet är JPG eller PNG, och storleken får inte överstiga 2M",
    t184: "Kontaktinformation (valfritt)",
    t185: "Ange kontaktinformation",
    t186: "Bekräfta inlämning",
    t187: "Skicka efter anslutning till plånbok",
    t188: "Spara utkast",
    t189: "Hur fungerar det?",
    t190: "Skicka förslag",
    t191: "Teamrecension",
    t192: "Dela ut belöningar",
    t193: "BeingDex servar användare över hela världen. Vi ser en säker och stabil utveckling av plattformen som vår högsta prioritet. Vi ser fram emot dina värdefulla förslag. Låt oss förbättra produktkvaliteten och skapa en bättre framtid tillsammans.",
    t194: "Ett protokoll som Web3-användare kan lita på<br>gör det möjligt för Defi-användare att enkelt slutföra transaktioner",
    t195: "Självvårdande tillgångar, plånbok punkt-till-punkt matchande transaktioner",
    t196: "Säkerhet med noll olyckor och rent smart kontraktsutförande",
    t197: "Originalt decentraliserat K-linjediagram, inbyggda fördelar",
    t198: "Populära kryptovalutor",
    t199: "BeingDex Ecology",
    t200: "Hantera dina tillgångar enkelt",
    t201: "BeingDex är en orderbok som matchar decentraliserad handelsplattform byggd med rena smarta kontrakt. Den övergripande ekologiska layouten täcker Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, gruvpooler och andra industrier.",
    t202: "En decentraliserad produkt som integrerar plånbok och transaktion",
    t203: "BeingDex - en ordermatchande decentraliserad handelsplattform byggd med rena smarta kontrakt",
    t204: "Applikation - BeingDex diversifierade ekologiska produkter",
    t205: "Plånbok - Hantera dina tillgångar med flera kedjor",
    t206: "Handel bör göras när som helst och var som helst",
    t207: "Ladda ner appen så hjälper vi dig att handla 24/7",
    t208: "Skanna för att ladda ner",
    t209: "Medieresurser",
    t210: "Efterlevnad och policy",
    t211: "Global officiell certifiering av säkerhetsefterlevnad för att säkerställa säkerheten för användartillgångar",
    t212: "Erhåll amerikansk MSB-licens",
    t213: "28 november 2023",
    t214: "Ansökan om Dubai DMCC-licens väntar",
    t215: "Ansökan om licenser från Hong Kong Securities Regulatory Commission/VARA/DIFC/ADGM/US MTL etc.",
    t216: "Våra partners",
    t217: "15+ års erfarenhet av informationsteknologi.<br>Mycket skicklig senior molndator/DevOps och applikationsarkitekt med erfarenhet av AWS, GCP, Azure och DevOps/SystemOps/DevOps-verktyg och omfattande förståelse för tjänster.<br>8 + års erfarenhet av att arbeta som moln/DevSecOps/applikationsarkitekt i finanssektorn<br>Designade Kanadas första cryptocurrency-hårdvaruplånboksprototyp för min startup Blockchain Mind.",
    t218: "Bjud in vänner och vinn upp till<br>9 000 USDT",
    t219: "Inbjudningslänk",
    t220: "Bjud in nu",
    t221: "Bjud in efter anslutning till plånbok",
    t222: "Inbjudningspost",
    t223: "Användarnamn",
    t224: "Registreringstid",
    t225: "Recharge når standard",
    t226: "Transaktion uppfyller standard",
    t227: "Insättningsbonus",
    t228: "Blind låda",
    t229: "Populära evenemang",
    t230: "Regler",
    t231: '1. När en inbjuden vän slutför laddningsuppgiften kommer inbjudaren att få en rabattkupong på 100 USDT. Efter att den inbjudna vännen har slutfört transaktionsuppgiften kan inbjudaren slumpmässigt dra en blind box-belöning på 5-500 USDT. <br> 2. Laddningsuppgift: Inom 30 dagar efter att den inbjudna vännen har registrerat sig, ladda genom angivna kanaler och den kumulativa nettoladdningen överstiger 50USDT. <br> 3. Handelsuppgift: Inom 30 dagar efter att den inbjudna vännen registrerat sig överstiger den kumulativa transaktionsvolymen för spot- eller kontraktstransaktioner 200USDT. <br>4. Inbjudna vänner måste slutföra laddningsuppgiften innan du kan låsa upp belöningarna för handelsuppgiften. Om din inbjudna vän inte lyckas slutföra laddningsuppgiften kommer du inte att kunna få belöningen även om transaktionen överstiger 200USDT. <br> 5. Angivna laddningskanaler: Giltig laddning är begränsad till laddning i kedjan, laddning av fiatvaluta, kortköp, C2C-transaktioner och tredje parts betalningar. Interna överföringar och röda kuvert ingår inte i den effektiva laddningen. 6. Inbjudaren kan få upp till 15 avdragskuponger för hanteringsavgifter och 15 kontantbelöningar per månad. <br> 7. Giltighetstid: Avdragskupongen för expeditionsavgiften måste hämtas inom 14 dagar efter utfärdandet. Den giltiga användningsperioden efter hämtning är 14 dagar. Var uppmärksam på att ta emot och använda den i tid för att undvika att belöningen löper ut ; Inlösningsperioden för blind box-belöning är giltig i 90 dagar. Lös in kontantkupongbelöningen så snart som möjligt efter att du har mottagit belöningen. Efter inlösen är kontantkupongen giltig i 14 dagar. <br> 8. Inbjudningar från samma IP-adress eller enhet kommer att betraktas som självinbjudningar. Självinbjudan kommer att resultera i att användaren förlorar de belöningar som redan tjänats in och berättigar till framtida belöningar. BeingDex förbehåller sig rätten att frysa olagliga konton och konfiskera tillgångarna på kontona. <br>9. När belöningarna delas ut kommer systemet automatiskt att avgöra om de nuvarande två parterna har exklusiv partnerstatus. Om antingen inbjudaren eller den inbjudna är en exklusiv partner kommer belöningen att stå i konflikt med den exklusiva partnerrabatten och belöningen kommer inte att utfärdas. Dessutom kan underkonton inte delta i aktiviteter som oberoende konton, och data kommer inte att slås samman till huvudkontot. <br> 10. Reglerna ovan träder i kraft från kl. 18.00 den 11 maj 2023 (UTC+8). BeingDex förbehåller sig rätten till slutlig tolkning av denna aktivitet. BeingDex förbehåller sig rätten att hantera användarkonton och tillgångar om något skadligt beteende eller olagligt och oetiskt beteende som utnyttjar plattformssårbarheter upptäcks. <br> 11. Du får inte låtsas vara BeingDex officiell och göra vilseledande uttalanden, inklusive men inte begränsat till att köpa nyckelord som "BeingDex", "BeingDex login", "BeingDex official", "BeingDex C2C" etc. för att marknadsföra på sökmotorer. De som bryter mot kraven kommer att diskvalificeras från belöningar och kampanjer.',
    t232: "Compliance and Security",
    t233: "BeingDex insisterar på att implementera ett omfattande efterlevnads- och säkerhetsstyrningssystem och följer strikta standarder och processer formulerade av efterlevnadsrådgivningsteamet för att säkerställa allsidig riskhantering och övervakning.<br>Plattformen genomför regelbundet omfattande riskbedömningar för att identifiera potentiella risker punkter inkluderar marknadsrisk och operativ risk. Implementera effektiva riskhanteringsstrategier, aktivt spåra och identifiera möjliga interna och externa risker, och vidta lämpliga åtgärder. För risker orsakade av externa faktorer kommer BeingDex att använda avancerad krypteringsteknik som skyddar datasäkerheten. För interna risker , upprätta en strikt intern kontrollmekanism, inklusive en auktoriseringsmekanism för att klargöra ansvarsområden, och genomföra regelbundna interna och externa revisioner.<br>Genom att regelbundet samordna med lokala tillsynsmyndigheter och genomföra efterlevnadsgranskningar, inkluderar detta inhemska externa lagar och förordningar, särskilt de som gäller finansiella tjänster, dataskydd och anti-penningtvätt (AML), säkerställa efterlevnaden och säkerheten för företagets verksamhet och säkerställa att plattformen följer alla tillämpliga finansiella regler och standarder.",
    t234: "Compliance Management Framework",
    t235: "Identifiering",
    t236: "Utvärdering",
    t237: "Kör",
    t238: "utvärdering",
    t239: "1. Efterlevnadshantering",
    t240: "Under överinseende av ett team av efterlevnadsexperter följer BeingDex strikta efterlevnadsstandarder och protokoll, implementerar en omfattande efterlevnadshanteringsstruktur och genomför effektiv identifiering, bedömning, utförande och utvärdering.<br>BeingDex upptäcker och identifierar aktivt källor från externa och interna risker och vidta nödvändiga korrigerande åtgärder. Externa risker avser risker som kan orsakas av externa förändringar, såsom felaktig information publicerad av tredjepartsannonser från BeingDex-agenter.<br> Interna risker avser risker som kan komma inifrån organisation Risker, såsom obehörigt, olämpligt, olagligt eller oetiskt beteende från interna anställda.<br>BeingDex arbetar med lokala tillsynsmyndigheter genom en kombination av bedömningar och årliga efterlevnadsgranskningar för att säkerställa att våra efterlevnadsstandarder uppfyller lokala krav.",
    t241: "2.eKYC-teknik",
    t242: "BeingDex antar elektronisk identitetsverifiering (eKYC) för att säkra plattformen och minska potentiella bedrägerier och olagliga risker. Utöver detta har BeingDex sanktioner och anti-penningtvätt (AML) policyer på plats för att följa alla relevanta jurisdiktioner, och förhindra förfalskning eller andra kriminella aktiviteter på plattformen.<br>Effektivitet är avgörande för Customer Due Diligence (CDD), därför använder BeingDex eKYC-teknik för att optimera processen för verifiering av användaridentitet (KYC) under förutsättningen av efterlevnad. <br>Detta Tekniken möjliggör ansiktsigenkänning och automatisk korsmatchning mellan användartillhandahållen identifiering och realtidsporträtt, vilket förhindrar falska identiteter och förkortar också avsevärt tiden för användare att utföra personlig identitetsverifiering på BeingDex-plattformen.",
    t243: "2. Blockkedjeanalys",
    t244: "BeingDex distribuerar externa blockkedjeanalysverktyg för att noggrant övervaka transaktioner på plattformen och minska risken för bedrägliga aktiviteter och uppkomsten av högriskanvändare*. Blockkedjans oföränderliga och transparenta karaktär tillåter oss att heltäckande upptäcka transaktioner på plattformen Alla transaktioner.<br>*Högriskanvändare inkluderar men är inte begränsade till:<br>- Kunder i känsliga länder eller regioner<br>- Offentliga tjänstemän<br>- Kunder från känsliga branscher (som kapitalintensiva företag) <br>Baserat på bedömningen av vårt risk- och ledningsteam kommer vi att vidta olika åtgärder mot högriskanvändare, vilket kan inkludera beslagtagande av tillgångar, flera granskningar eller revisioner etc., beroende på den specifika situationen.",
    t245: "3.Nätverkssäkerhet",
    t246: "BeingDex konsulterar oberoende nätverkssäkerhetsexperter för att förbättra plattformens säkerhet och stabilitet. Samtidigt genomförs nätverkspenetrationstestning och sårbarhetsbedömningar två gånger om året för att snabbt och snabbt hantera upptäckta potentiella hot.<br>Utöver ovanstående tester krypterar BeingDex även all känslig data för att förhindra risker som stöld, obehörig åtkomst eller modifiering. All data som överförs eller sparas är krypterad och lagras säkert i feltolerant lagring.",
    t247: "Operationen lyckades",
    t248: "Alla lästa",
    t249: "Citat",
    t250: "Dagens förändring",
    t251: "24H handelsvolym",
    t252: "24H transaktionsvolym",
    t253: "Populära valutor",
    t254: "Senaste valuta",
    t255: "Valutan med den största ökningen",
    t256: "Högsta handelsvolym valuta",
    t257: "Snabbare transaktioner, bättre tillgångar",
    t258: "Din framtida Web3-transaktionsplånbok",
    t259: "Superportal för Web3-universum",
    t260: "Gå med 12 miljoner användare, bläddra enkelt på den största NFT-marknaden och interagera säkert med 20 000+ DApps på BeingDex Wallet",
    t261: "Njut av den mest omfattande och lättanvända NFT-plattformen",
    t262: "Aggregerar flera vanliga NFT-marknader, stödjer en-klicks-batchplacering av beställningar och köp av NFTs i valfri valuta",
    t263: "Köp",
    t264: "Låt blockchain hända överallt",
    t265: "Multi-chain plånbok, säker och lätt att använda, blockchain-ingång",
    t266: "Plånbok med öppen källkod",
    t267: "Plånbok med öppen källkod, självförsörjande privat nyckel, flerskiktskryptering",
    t268: "Följ ditt hjärta och känn dig lugn",
    t269: "Kedjeöverskridande, bekvämt, decentraliserat, en enda efterfrågan",
    t270: "Decentraliserad plånbok",
    t271: "Separation av varma och kalla tillgångar, säker och bekväm Token 40000+",
    t272: "Kryptotillgångar",
    t273: "Kryptotillgångar 40 000+ stöder olika tillgångar för handel på DEX.",
    t274: "Flera krypteringsteknik",
    t275: "Lagra kryptovaluta säkert och kontrollera dina egna tillgångar.",
    t276: "Multiple gain mode",
    t277: "Insats, gruvdrift, DeFi, kedjespel.",
    t278: "Självvård av tillgångar, peer-to-peer-matchning av plånbokstransaktioner",
    t279: "Säkerhet med noll olyckor och rent smart kontraktsutförande",
    t280: "Originalt decentraliserat K-linjediagram, inbyggda fördelar",
    t281: "Ditt val är detsamma som deras",
    t282: "Förtroende och val av 1 000+ ledande företag",
    t283: "plug-in plånbok",
    t284: "Instruktion för plugin-installation",
    t285: "Världens ledande blockchain-verktyg för digital tillgångshantering",
    t286: "Rent smart kontraktsutförande",
    t287: "Ladda ner nu",
    t288: "DApp Ecological Entrance",
    t289: "Utforska DeFi, GameFi, etc., och spela snabbt med DApp-ekonomin",
    t290: "Låt oss komma igång! Klicka här för att skicka förslag eller feedback",
    t291: "Visa mer",
    t292: "Token typ",
    t293: "BeingDex, multikedjedriven<br>en-stop-handelsplattform för kapitalförvaltning<br>säker, effektiv och låg kostnad",
    t294: "BeingDex cross-chain bridge",
    t295: "svenska",
    t296: "Inte öppet ännu",
    t297: "fungera",
    t298: "plånbok",
    t299: "Swap",
    t300: "Dapp",
    t301: "Blogg"
  }
}