export default {
  text: {
    t1: "Ev",
    t2: "Bize katılın",
    t3: "Google Mağazası",
    t4: "Apple Mağazası",
    t5: "Uygulamayı İndir",
    t6: "Chrome İndirme",
    t7: "Yerel indirme",
    t8: "BDX döviz fiyatı",
    t9: "İşlem hacmi",
    t10: "Topluluk Kullanıcısı",
    t11: "İşlem sayısı",
    t12: "BDX toplam işlem hacmi",
    t13: "Büyüme Listesi",
    t14: "Reddet listesi",
    t15: "Yeni Coin Listesi",
    t16: "İşlem Hacmi Listesi",
    t17: "isim",
    t18: "Son fiyat",
    t19: "fiyat",
    t20: "Bugünkü artış",
    t21: "Artır veya azalt",
    t22: "24 saatlik işlem hacmi",
    t23: "İşlem",
    t24: "Henüz veri yok",
    t25: "Tümünü görüntüle",
    t26: "Güvenli, verimli, düşük maliyetli",
    t27: "Çevrimiçi müşteri hizmetleri",
    t28: "Ticari İşbirliği",
    t29: "Şirket",
    t30: "Hakkımızda",
    t31: "Yardım Merkezi",
    t32: "Duyuru",
    t33: "BDX Jetonu",
    t34: "ürün",
    t35: "Para satın al",
    t36: "Web3 cüzdanı",
    t37: "Hizmet",
    t38: "Geri Bildirim",
    t39: "Para birimi listeleme başvurusu",
    t40: "Arkadaş daveti",
    t41: "Yasal ve Risk Açıklaması",
    t42: "Uyum lisansı",
    t43: "Kara Para Aklamanın Önlenmesi Politikası",
    t44: "Gizlilik Politikası",
    t45: "Kullanıcı Sözleşmesi",
    t46: "Yasal Bildirim",
    t47: "Risk Uyarısı",
    t48: "ST kuralı",
    t49: "eklenti cüzdanı",
    t50: "Cüzdanı indir",
    t51: "Dil",
    t52: "Oturumu kapat",
    t53: "Cüzdanı bağla",
    t54: "Yükleniyor...",
    t55: "Artık yok...",
    t56: "OlmakDex Hakkında",
    t57: "BeingDex'in arkasında blockchain teknolojisini ilk benimseyenlerden ve blockchain'in gelecekteki gelişimine inananlardan oluşan bir grup var.",
    t58: "2018'den beri bir kripto para borsası kurduk ve kullanıcıların daha akıllı ticaret yapmasına yardımcı olmak için güvenli, tek elden ticaret çözümleri sunmaya kendimizi adadık.",
    t59: "Merkezi olmayan ticaret platformuyla eşleşen tam zincirli bekleyen emir",
    t60: "Global kayıtlı adres",
    t61: "100.000+",
    t62: "30 milyon USDT",
    t63: "Günlük işlem hacmi",
    t64: "Hikayemiz",
    t65: 'Bunlar, blockchain ve şifreli varlıklara sıkı bir inancı olan bir grup inek. 2010 yılında ilk Bitcoin imizi e-ticaret OTC platformu üzerinden satın aldık. O zamanlar gergin ve tedirgindik. Endüstri döngüsü değiştikçe işlem yöntemleri ve ürün formları yenilenmeye ve gelişmeye devam ediyor; bu da Cex ve Dex in aynı anda geliştiği bir durumu ortaya koyuyor. Ancak aynı zamanda mevcut Dex in model mekanizmasıyla sınırlı olduğunu ve varlık verimliliğini maksimuma çıkaramadığını da fark ediyoruz. <br>Aynı zamanda, şifreleme endüstrisi dünya çapında giderek daha geniş ve derin bir etkiye sahip olduğundan, gelişmiş bölgelerin yanı sıra, mali altyapısı zayıf olan bölgelerden de giderek daha fazla insan katılmaya başlıyor, ancak karmaşıklığı anlamakta zorluk çekiyorlar. finansal ürünler ve Algoritmik mekanizma, onların yeni dünyalara, yeni varlıklara bağlanmasını engelleyen bir boşluk haline geldi. <br>BeingDex, bu boşluğu doldurmaya ve yeni akıllı sözleşmeler yoluyla tam zincirli uygulama ürünleri ve ekoloji oluşturmaya kararlıdır. <br>Varlık, şeylerin kökenini keşfetme ruhumuzu, temel ürün değeri uygulamamızı ve nihai kullanıcı deneyimi arayışımızı ifade eden "varlık", "öz" ve "biyolojik yaşam" gibi çağrışımlara sahiptir. ve aynı zamanda daha fazla insanın zihinlerini açmasını, kripto varlıklarını benimsemesini ve kullanımı kolay ve kullanıcı dostu ürün hizmetleri aracılığıyla kendi kripto serveti yolculuğuna başlamalarına yardımcı olmasını memnuniyetle karşılıyoruz.',
    t66: "Vizyon",
    t67: "Web3 aracılığıyla daha özgür, daha adil ve daha şeffaf bir gelecek zenginlik dünyası yaratın",
    t68: "Görev",
    t69: "Herkesin kullanabileceği nihai ticaret platformunu yaratın ve sektördeki lider dijital varlık finansal hizmet sağlayıcısı olun",
    t70: "Değerlerimiz",
    t71: "Önce kullanıcı",
    t72: "Her kullanıcının ihtiyaç ve tutumlarına dikkat edin, objektif ve samimi iletişim kurun, platform bilgilerini zamanında yayınlayın.",
    t73: "Dürüstlük ve titizlik",
    t74: "'Kötülük yapma' ilkesine bağlı kalarak sorumluluk ve sorumlulukla piyasanın ve kullanıcıların güvenini kazanırız.",
    t75: "Yenilikçi ve girişimci",
    t76: "Extreme ürün ve hizmetler ile yapısal avantajlar oluşturmak ebedi arayışımızdır.",
    t77: "Sonunu düşünerek başla",
    t78: "Uzun vadeli ortaklarla uzun vadeli işler yapın, süreci kavrayın, koşullar yaratın, geri bildirim sonuçlarına dikkat edin ve kilometre taşı hedeflerine sürekli ulaşın.",
    t79: "Ekibimiz",
    t80: "10'dan fazla ülkeden 150'den fazla çalışanıyla BeingDEX ekibi, gezegenin her köşesinden üst düzey yeteneklere sahip ve bize gerçek anlamda küresel bir erişim sağlıyor.",
    t81: "Hizmetlerimiz",
    t82: "DEX Olmak",
    t83: "BeingDex, çoklu zincir gelişimine dayanan yeni bir merkezi olmayan borsadır. Zincir içi sipariş eşleştirme modelini benimser ve zincirler arası köprü, halka açık zincirler BSC, TRON ve OKX'i destekler.",
    t84: "Cüzdan Olmak",
    t85: "Being Wallet iki ana güvenlik mekanizmasını benimser: kullanıcı varlıklarının kendi gözetimi ve tam anonimlik. Temel cüzdan teknolojisi, yerel biyometrik şifreleme ve güvenlik izolasyonu gibi çoklu güvenlik korumalarını destekler ve kullanıcıların güvenliğini korumak için çok zincirli varlık yönetimini destekler. işlemler.",
    t86: "NFT Olmak",
    t87: "NFT olmak, ETH, BSC, Mango, TRON, Polygon, Solana'nın çok zincirli tek tıklamayla NFT düzenlenmesini destekler, işlemler ve diğer faaliyetler üçüncü taraf müdahalesi olmadan zincir protokolü aracılığıyla tamamlanır. DAO tarafından düzenlenen NFT, cüzdanda saklanır. Zincir üzerinde yayın, akıllı işlemler, güvenli ve kullanışlı.",
    t88: "Kripto yolculuğunuza şimdi başlayın!",
    t89: "Milyonlarca kullanıcının güvendiği bir platformda işlem yapın.",
    t90: "Yükleme başarılı",
    t91: "Yükleme başarısız oldu",
    t92: "Lütfen ait olduğunuz genel zinciri seçin",
    t93: "Lütfen proje adını girin",
    t94: "Lütfen logoyu yükleyin",
    t95: "Lütfen belirteç kısaltmasını girin",
    t96: "Lütfen sözleşme adresini giriniz",
    t97: "Lütfen ihraç miktarını giriniz",
    t98: "Lütfen resmi web sitesi bağlantısını girin",
    t99: "Lütfen e-posta adresinizi giriniz",
    t100: "Lütfen jeton bilgilerinizi giriniz",
    t101: "Gönderim başarılı",
    t102: "BeingDex para listeleme uygulaması",
    t103: "BeingDex Exchange'e gösterdiğiniz ilgi için teşekkür ederiz. Lütfen başvuru formunu doldurun ve geçerli bilgiler sağlayın. Verdiğiniz bilgilere göre projenizi inceleyeceğiz. Lütfen bu başvuruyu gönderin ve projeniz döviz listeleme departmanına gönderilecektir. İnceleme. Ön incelemeyi geçtikten sonra, döviz listeleme sürecini ve tekniklerini sizinle paylaşacak ve döviz listeleme sürecinde size rehberlik edecek bir döviz listeleme uzmanı ayarlayacağız.",
    t104: "Gerekli olduğunu gösterir",
    t105: "Ait olduğu halka açık zincir",
    t106: "Proje adı",
    t107: "Jeton kısaltması",
    t108: "Sözleşme adresi",
    t109: "İhraç miktarı",
    t110: "Resmi web sitesi bağlantısı",
    t111: "Posta Kutusu",
    t112: "Jeton bilgisi",
    t113: "Lütfen jeton bilgilerinizi girin, en fazla 120 karakter olsun",
    t114: "Gönder",
    t115: "Cüzdana bağlandıktan sonra gönder",
    t116: "Form içeriğini temizle",
    t117: "BDX kripto endüstrisinde devrime öncülük ediyor",
    t118: "Web3 dünyasının kilidini hızla açmanıza yardımcı olmak için varlıklarınızı, DeFi uygulamalarınızı ve NFT'lerinizi bağlayın",
    t119: "BDX'i tek tıkla edinin",
    t120: "BDX Teknik Raporu",
    t121: "BDX'e Giriş",
    t122: "BDX'i tutun ve sonsuz avantajların tadını çıkarın",
    t123: "Yeni abonelik",
    t124: "Tercihli hizmet",
    t125: "Söndürme mekanizması",
    t126: "Yeni çevrimiçi",
    t127: "Planlama",
    t128: "BDX'i al",
    t129: "BDX sürüm bilgisi",
    t130: "Güvenli, kullanımı kolay ve dünya çapındaki kültür ve ideolojilerle yakından bağlantılı",
    t131: "Belirteç adı",
    t132: "Jeton sembolü",
    t133: "Zincire sahip olma",
    t134: "Sözleşme adresi",
    t135: "İhraç fiyatı",
    t136: "Dolaşım beslemesi",
    t137: "Toplam arz",
    t138: "Yayınlanma tarihi",
    t139: "BDX'i Değiştir",
    t140: "Mevcut BDX belirteçlerinin kullanılması için",
    t141: "Takım Motivasyonu",
    t142: "6 ayda bir %2 kilit açılır, 5 yıl (60 ay) sonra tamamen açılır",
    t143: "Ekonomik ve ekolojik yatırım",
    t144: "Fon yatırımı için BeingDex ekosistemine gidin",
    t145: "Marka Tanıtımı",
    t146: "Yıl başına maksimum sürüm",
    t147: "Kullanıcı girişi",
    t148: "Koruma Fonu",
    t149: "Platformda meydana gelebilecek kazaların telafisi için",
    t150: "Güvenli ve güvenilir bir BDX ekosistemi oluşturmak ve Web3'ün hızlı gelişimini desteklemek için bizimle çalışın",
    t151: "BDX'i tek tıkla edinin",
    t152: "Önerilen",
    t153: "En Son Blog",
    t154: "Henüz veri yok",
    t155: "DApp Uygulama Mağazası",
    t156: "Ara",
    t157: "Kategori seç",
    t158: "Önemli Sorumluluk Reddi",
    t159: 'Bu web sitesi, hiperlinkli web siteleri, ilgili uygulamalar, forumlar, bloglar, sosyal medya hesapları ve diğer platformlarda ("Site") sunulan tüm içerik, yalnızca üçüncü taraf kaynaklardan elde edilen genel bilgilerinize yöneliktir. içerik Doğruluk ve güncellik dahil ancak bunlarla sınırlı olmamak üzere hiçbir garanti verilmemektedir.Sağladığımız içeriğin hiçbir kısmı mali tavsiye, hukuki tavsiye veya başka herhangi bir tavsiye niteliğinde değildir ve herhangi bir amaç için özel güveninizi karşılamak üzere tasarlanmamıştır. İçeriğimizin herhangi bir şekilde kullanılması veya bunlara güvenilmesi, kendi sorumluluğunuzdadır ve kendi takdirinize bağlıdır. İçeriğimize güvenmeden önce kendi araştırmanızı, incelemenizi, analizinizi ve doğrulamanızı yapmalısınız. Ticaret, önemli kayıplarla sonuçlanabilecek yüksek riskli bir faaliyettir, bu nedenle Lütfen herhangi bir karar vermeden önce mali müşavirinize danışın. Sitemizde yer alan hiçbir şey talep veya teklif değildir.',
    t160: "Lütfen öneri ayrıntılarını girin",
    t161: "Gönderim başarılı",
    t162: "Önerilerinizin her biri",
    t163: "Dikkatle dinleyip ciddiye alacağız",
    t164: "Geri Bildirim",
    t165: "Herhangi bir güvenlik açığı veya güvenlik açığı bulursanız lütfen bize zamanında geri bildirimde bulunun",
    t166: "Herhangi bir sorunuz varsa sık sorulan soruların yanıtları için lütfen Yardım Merkezi'ne başvurun.",
    t167: "Ürün deneyimimiz hakkında ne düşünüyorsunuz?",
    t168: "İyi bir deneyim değil!",
    t169: "Geliştirilecek!",
    t170: "Oldukça tatmin edici!",
    t171: "Süper harika!",
    t172: "Öneriyi gönder",
    t173: "Ürün önerilerinizi paylaşmaya hoş geldiniz. BeingDex geri bildiriminizi ciddiye alacaktır. Acil sorularınız varsa lütfen müşteri hizmetleriyle iletişime geçin.",
    t174: "Önerilen kategori",
    t175: "Güvenlik önerileri",
    t176: "Özellik Önerileri",
    t177: "Tasarım Önerileri",
    t178: "İşlem Önerileri",
    t179: "Diğer öneriler",
    t180: "Öneri ayrıntıları",
    t181: "Lütfen geri bildiriminizi girin, en fazla 500 karakter",
    t182: "Resimleri yükle (isteğe bağlı)",
    t183: "Lütfen sorunla ilgili ekran görüntülerini yükleyin. Resim formatı JPG veya PNG'dir ve boyutu 2M'yi geçmemelidir",
    t184: "İletişim bilgileri (isteğe bağlı)",
    t185: "Lütfen iletişim bilgilerinizi giriniz",
    t186: "Gönderimi onayla",
    t187: "Cüzdana bağlandıktan sonra gönder",
    t188: "Taslağı kaydet",
    t189: "Nasıl çalışıyor?",
    t190: "Öneriyi gönder",
    t191: "Takım incelemesi",
    t192: "Ödülleri dağıt",
    t193: "BeingDex dünyanın her yerindeki kullanıcılara hizmet veriyor. Platformun güvenli ve istikrarlı gelişimini en büyük önceliğimiz olarak görüyoruz. Değerli önerilerinizi bekliyoruz. Ürün kalitesini artıralım ve birlikte daha iyi bir gelecek yaratalım.",
    t194: "Web3 kullanıcılarının güvenebileceği bir protokol<br>Defi kullanıcılarının işlemleri kolayca tamamlamasına olanak tanır",
    t195: "Varlığın kendi saklaması, cüzdandan noktadan noktaya eşleştirme işlemleri",
    t196: "Sıfır kaza ve saf akıllı sözleşme uygulamasıyla güvenlik",
    t197: "Orijinal merkezi olmayan K çizgisi grafiği, yerel avantajlar",
    t198: "Popüler Kripto Para Birimleri",
    t199: "BeingDex Ekolojisi",
    t200: "Varlıklarınızı kolayca yönetin",
    t201: "BeingDex, saf akıllı sözleşmelerle oluşturulmuş, merkezi olmayan ticaret platformuyla eşleşen bir sipariş defteridir. Genel ekolojik düzen, Kripto, Cüzdan, DEX, DeFi, GameFi, DAO, NFT, madencilik havuzları ve diğer endüstrileri kapsar.",
    t202: "Cüzdan ve işlemi entegre eden merkezi olmayan bir ürün",
    t203: "BeingDex - saf akıllı sözleşmelerle oluşturulmuş merkezi olmayan ticaret platformuyla eşleşen emir",
    t204: "Uygulama - BeingDex çeşitlendirilmiş ekolojik ürünler",
    t205: "Cüzdan - Çoklu zincir varlıklarınızı yönetin",
    t206: "Ticaret her zaman ve her yerde yapılmalı",
    t207: "Uygulamayı indirin, 7/24 işlem yapmanıza yardımcı olalım",
    t208: "İndirmek için tara",
    t209: "Medya Kaynakları",
    t210: "Uyum ve Politika",
    t211: "Kullanıcı varlıklarının güvenliğini sağlamak için küresel resmi güvenlik uyumluluğu sertifikası",
    t212: "ABD MSB lisansını alın",
    t213: "28 Kasım 2023",
    t214: "Dubai DMCC lisansı başvurusu beklemede",
    t215: "Hong Kong Menkul Kıymetler Düzenleme Komisyonu/VARA/DIFC/ADGM/US MTL vb.'den lisans başvurusu.",
    t216: "Ortaklarımız",
    t217: "Bilgi teknolojisinde 15 yıldan fazla deneyim.<br>AWS, GCP, Azure ve DevOps/SystemOps/DevOps araçlarında deneyime ve kapsamlı hizmet anlayışına sahip yüksek vasıflı kıdemli bulut bilişim/DevOps ve uygulama mimarı.<br>8 + finans sektöründe Bulut/DevSecOps/Uygulama Mimarı olarak uzun yıllara dayanan deneyim<br>Başlangıcım Blockchain Mind için Kanada'nın ilk kripto para birimi donanım cüzdanı prototipini tasarladım.",
    t218: "Arkadaşlarınızı davet edin ve<br>9.000 USDT'ye kadar kazanın",
    t219: "Davetiye bağlantısı",
    t220: "Şimdi davet et",
    t221: "Cüzdana bağlandıktan sonra davet et",
    t222: "Davet kaydı",
    t223: "Kullanıcı adı",
    t224: "Kayıt zamanı",
    t225: "Şarj standarda ulaştı",
    t226: "İşlem standardı karşılıyor",
    t227: "Para yatırma bonusu",
    t228: "Kör kutu",
    t229: "Popüler Etkinlikler",
    t230: "Kurallar",
    t231: "1. Davet edilen bir arkadaş yükleme görevini tamamladığında, davet eden kişi 100 USDT'lik bir indirim kuponu alacaktır. Davet edilen arkadaş işlem görevini tamamladıktan sonra, davet eden kişi rastgele 5-500 USDT tutarında bir kör kutu ödülü çekebilir. <br> 2. Yeniden yükleme görevi: Davet edilen arkadaşınız kaydolduktan sonraki 30 gün içinde, belirlenen kanallar aracılığıyla yükleme yapın ve kümülatif net yükleme 50 USDT'yi aşsın. <br> 3. Ticaret görevi: Davet edilen arkadaşın kaydolmasından sonraki 30 gün içinde, kümülatif spot veya sözleşme işlem hacmi 200 USDT'yi aşar. <br>4. Ticaret görevi ödüllerinin kilidini açabilmeniz için davet edilen arkadaşlarınızın yeniden yükleme görevini tamamlaması gerekir. Davet ettiğiniz arkadaşınız yükleme görevini başarıyla tamamlayamazsa, işlem 200USDT'yi aşsa bile ödülü alamayacaksınız. <br> 5. Belirlenmiş yükleme kanalları: Geçerli yükleme, zincir içi yükleme, fiat para yükleme, kart satın alımları, C2C işlemleri ve üçüncü taraf ödemeleriyle sınırlıdır. Dahili transferler ve kırmızı zarflar etkin yüklemeye dahil değildir. 6. Davet eden kişi, her ay en fazla 15 işlem ücreti kesinti kuponu ve 15 nakit kör kutu ödülü alabilir. <br> 7. Geçerlilik süresi: İşlem ücreti kesinti kuponu düzenlendikten sonra 14 gün içinde alınmalıdır. Tahsilattan sonraki geçerli kullanım süresi 14 gündür. Ödül süresinin dolmaması için lütfen zamanında alıp kullanmaya dikkat edin. ; Kör kutu ödülü kullanım süresi 90 gün geçerlidir. Lütfen nakit kupon ödülünü ödülü aldıktan sonra mümkün olan en kısa sürede kullanın. Kullandıktan sonra nakit kupon 14 gün geçerlidir. <br> 8. Aynı IP adresinden veya cihazdan gelen davetler, kendi kendine davet olarak kabul edilecektir. Kendi kendine davet, kullanıcının halihazırda kazanmış olduğu ödülleri kaybetmesine ve gelecekteki ödüllere uygunluğuna yol açacaktır. BeingDex, yasa dışı hesapları dondurma ve hesaplardaki varlıklara el koyma hakkını saklı tutar. <br>9. Ödüller dağıtıldığında sistem, mevcut iki tarafın özel ortak statüsüne sahip olup olmadığını otomatik olarak belirleyecektir. Davet eden veya davet edilen kişi özel bir ortaksa ödül, özel ortak indirimi ödülüyle çelişecek ve ödül verilmeyecektir. Ayrıca alt hesaplar bağımsız hesap olarak faaliyetlere katılamayacak ve veriler ana hesaba birleştirilmeyecektir. <br> 10. Yukarıdaki kurallar 11 Mayıs 2023 18:00 (UTC+8) tarihinden itibaren geçerli olacaktır. BeingDex bu aktivitenin nihai yorumunu yapma hakkını saklı tutar. BeingDex, platformdaki güvenlik açıklarından yararlanan herhangi bir kötü niyetli davranışın veya yasa dışı ve etik olmayan davranışın tespit edilmesi durumunda kullanıcı hesapları ve varlıklarıyla ilgilenme hakkını saklı tutar. <br> 11. BeingDex yetkilisi gibi davranamaz ve yanıltıcı beyanlarda bulunamazsınız; bunlara tanıtım amacıyla 'BeingDex', 'BeingDex girişi', 'BeingDex resmi', 'BeingDex C2C' vb. anahtar kelimeler satın alamazsınız. arama motorlarında. Gereksinimleri ihlal edenler ödül ve promosyonlardan diskalifiye edilecektir.",
    t232: "Uyumluluk ve Güvenlik",
    t233: "BeingDex kapsamlı bir uyumluluk ve güvenlik yönetişim sistemi uygulamakta ısrar ediyor ve çok yönlü risk yönetimi ve izlemeyi sağlamak için uyumluluk danışma ekibi tarafından formüle edilen katı standartları ve süreçleri takip ediyor.<br>Platform, Potansiyel riskleri belirlemek için düzenli olarak kapsamlı risk değerlendirmeleri yürütüyor noktalar piyasa riski ve operasyonel riski içerir.Etkili risk yönetimi stratejilerini uygulayın, olası iç ve dış riskleri aktif olarak takip edip tanımlayın ve uygun müdahale önlemlerini alın.Dış faktörlerden kaynaklanan riskler için BeingDex gelişmiş şifreleme kullanacak Veri güvenliğini koruyan teknoloji.İç riskler için , sorumlulukları açıklığa kavuşturmak için bir yetkilendirme mekanizması da dahil olmak üzere sıkı bir iç kontrol mekanizması oluşturun ve düzenli iç ve dış denetimler gerçekleştirin.<br>Yerel düzenleyici kurumlarla düzenli olarak koordinasyon sağlanarak ve uyumluluk incelemeleri gerçekleştirilerek, buna, özellikle aşağıdakilerle ilgili olanlar dahil olmak üzere, yerel Dış yasa ve düzenlemeler dahildir: finansal hizmetler, veri koruma ve kara para aklamayı önleme (AML), şirket operasyonlarının uyumluluğunu ve güvenliğini sağlar ve platformun geçerli tüm finansal düzenlemelere ve standartlara uygun olmasını sağlar.",
    t234: "Uyum Yönetimi Çerçevesi",
    t235: "Kimlik Tanımlama",
    t236: "Değerlendirme",
    t237: "Yürüt",
    t238: "değerlendirme",
    t239: "1. Uyumluluk yönetimi",
    t240: "Uyum uzmanlarından oluşan bir ekibin denetimi altında, BeingDex katı uyumluluk standartlarını ve protokollerini takip eder, kapsamlı bir uyumluluk yönetimi yapısı uygular ve etkili tanımlama, değerlendirme, yürütme ve değerlendirme gerçekleştirir.<br>BeingDex, Harici kaynaklardan gelen kaynakları aktif olarak tespit eder ve tanımlar. ve iç riskler ve gerekli iyileştirici önlemlerin alınması. Dış riskler, BeingDex acentelerinin üçüncü taraf reklamlarının yayınladığı yanlış bilgiler gibi dış değişikliklerden kaynaklanabilecek riskleri ifade eder.<br> İç riskler, şirket içinden gelebilecek riskleri ifade eder. Kuruluş içi çalışanların izinsiz, uygunsuz, yasa dışı veya etik olmayan davranışları gibi riskler.<br>BeingDex, uyumluluk standartlarımızın yerel gereklilikleri karşıladığından emin olmak için değerlendirmeler ve yıllık uyumluluk incelemeleri yoluyla yerel düzenleyicilerle birlikte çalışır.",
    t241: "2.eKYC teknolojisi",
    t242: "BeingDex, platformu güvence altına almak ve potansiyel dolandırıcılık ve yasa dışı riskleri azaltmak için elektronik kimlik doğrulamayı (eKYC) benimser. Buna ek olarak, BeingDex'in ilgili tüm yargı bölgelerine uyum sağlamak için yaptırımları ve kara para aklamayı önleme (AML) politikaları vardır ve platformda sahteciliği veya diğer suç faaliyetlerini önleyin.<br>Verimlilik, Müşteri Durum Tespiti (CDD) için çok önemlidir, bu nedenle BeingDex, uyumluluk öncülü altında kullanıcı kimliği doğrulama (KYC) sürecini optimize etmek için eKYC teknolojisini benimser.<br>Bu teknoloji, yüz tanımayı ve kullanıcı tarafından sağlanan tanımlama ile gerçek zamanlı portreler arasında otomatik çapraz eşleştirmeyi mümkün kılıyor, böylece sahte kimlikleri önlüyor ve aynı zamanda kullanıcıların BeingDex platformunda kişisel kimlik doğrulaması yapma süresini büyük ölçüde kısaltıyor.",
    t243: "2. Blockchain analizi",
    t244: "BeingDex, platformdaki işlemleri yakından izlemek, dolandırıcılık faaliyetleri ve yüksek riskli kullanıcıların ortaya çıkması riskini azaltmak için harici blockchain analiz araçlarını kullanıyor*. Blockchain'in değişmez ve şeffaf yapısı, platformdaki işlemleri kapsamlı bir şekilde tespit etmemize olanak tanıyor Tüm işlemler.<br>*Yüksek riskli kullanıcılara aşağıdakiler dahildir ancak bunlarla sınırlı değildir:<br>- Hassas ülke veya bölgelerdeki müşteriler<br>- Devlet yetkilileri<br>- Hassas sektörlerden müşteriler (sermaye yoğun işletmeler gibi) <br >Risk ve yönetim ekibimizin değerlendirmesine dayanarak, yüksek riskli kullanıcılara karşı, belirli duruma bağlı olarak varlıklara el konulması, birden fazla inceleme veya denetim vb. içerebilecek çeşitli önlemler alacağız.",
    t245: "3.Ağ güvenliği",
    t246: "BeingDex, platformun güvenliğini ve istikrarını geliştirmek için bağımsız ağ güvenliği uzmanlarına danışıyor. Aynı zamanda, tespit edilen potansiyel tehditlerin hızlı ve hızlı bir şekilde ele alınması için yılda iki kez ağ sızma testi ve güvenlik açığı değerlendirmeleri yapılıyor.<br>Ayrıca, yılda iki kez ağ sızma testleri ve güvenlik açığı değerlendirmeleri yapılıyor. Yukarıdaki testler sonucunda BeingDex ayrıca hırsızlık, yetkisiz erişim veya değişiklik gibi riskleri önlemek için tüm hassas verileri şifreler. Aktarılan veya kaydedilen tüm veriler şifrelenir ve hataya dayanıklı depolama alanında güvenli bir şekilde saklanır.",
    t247: "İşlem başarılı",
    t248: "Tümü okundu",
    t249: "Alıntılar",
    t250: "Bugünün değişimi",
    t251: "24 saatlik işlem hacmi",
    t252: "24 saatlik işlem hacmi",
    t253: "Popüler para birimleri",
    t254: "En son para birimi",
    t255: "En çok artış gösteren para birimi",
    t256: "En yüksek işlem hacmine sahip para birimi",
    t257: "Daha hızlı işlemler, daha iyi varlıklar",
    t258: "Gelecekteki Web3 işlem cüzdanınız",
    t259: "Web3 evreninin süper portalı",
    t260: "12 milyon kullanıcıya katılın, en büyük NFT pazarına kolayca göz atın ve BeingDex Cüzdanındaki 20.000'den fazla DApp ile güvenli bir şekilde etkileşime geçin",
    t261: "En kapsamlı ve kullanımı kolay NFT platformunun keyfini çıkarın",
    t262: "Birden fazla ana akım NFT pazarını bir araya getirmek, tek tıklamayla toplu sipariş verilmesini ve NFT'lerin herhangi bir para biriminde satın alınmasını desteklemek",
    t263: "Satın Alma",
    t264: "Blockchain'in her yerde gerçekleşmesine izin verin",
    t265: "Çok zincirli cüzdan, güvenli ve kullanımı kolay, blockchain girişi",
    t266: "Açık kaynak cüzdan",
    t267: "Açık kaynak cüzdan, kendi kendini idame ettiren özel anahtar, çok katmanlı şifreleme",
    t268: "Kalbinin sesini dinle ve rahat ol",
    t269: "Zincirler arası, kullanışlı, merkezi olmayan, tek noktadan talep",
    t270: "Merkezi olmayan cüzdan",
    t271: "Sıcak ve soğuk varlıkların ayrılması, güvenli ve kullanışlı Token 40000+",
    t272: "Kripto varlıklar",
    t273: "40.000'den fazla kripto varlığı DEX'te alım satım için çeşitli varlıkları destekler.",
    t274: "Çoklu şifreleme teknolojisi",
    t275: "Kripto para birimini güvenli bir şekilde saklayın ve kendi varlıklarınızı kontrol edin.",
    t276: "Çoklu kazanç modu",
    t277: "Stake etme, madencilik, DeFi, zincirleme oyunlar.",
    t278: "Varlıkların kendi kendine saklanması, cüzdan işlemlerinin eşler arası eşleştirilmesi",
    t279: "Sıfır kaza ve saf akıllı sözleşme uygulamasıyla güvenlik",
    t280: "Orijinal merkezi olmayan K çizgisi grafiği, yerel avantajlar",
    t281: "Seçiminiz onlarınkiyle aynı",
    t282: "1.000'den fazla lider firmanın güveni ve tercihi",
    t283: "eklenti cüzdanı",
    t284: "Eklenti yükleme eğitimi",
    t285: "Dünyanın lider blockchain dijital varlık yönetimi aracı",
    t286: "Saf akıllı sözleşme yürütme",
    t287: "Şimdi indir",
    t288: "DApp Ekolojik Girişi",
    t289: "DeFi, GameFi vb.'yi keşfedin ve DApp ekonomisiyle hızla oynayın",
    t290: "Hadi başlayalım! Öneri veya geri bildirim göndermek için burayı tıklayın",
    t291: "Daha fazlasını görüntüle",
    t292: "Jeton türü",
    t293: "BeingDex, çok zincirli<br>tek noktadan varlık yönetimi ticaret platformu<br>güvenli, verimli ve düşük maliyetli",
    t294: "BeingDex çapraz zincir köprüsü",
    t295: "Türkçe",
    t296: "Henüz açık değil",
    t297: "işletmek",
    t298: "cüzdan",
    t299: "Değiştir",
    t300: "Dapp",
    t301: "Blog"
  }
}