export default {
  text: {
    t1: "Uy",
    t2: "Bizga qo'shiling",
    t3: "Google Store",
    t4: "Apple Store",
    t5: "Ilovani yuklab olish",
    t6: "Chrome yuklab olish",
    t7: "Mahalliy yuklab olish",
    t8: "BDX valyuta narxi",
    t9: "Savdo hajmi",
    t10: "Hamjamiyat foydalanuvchisi",
    t11: "Tranzaksiyalar soni",
    t12: "BDX umumiy tranzaksiya hajmi",
    t13: "O'sish ro'yxati",
    t14: "Rad qilish ro'yxati",
    t15: "Yangi tangalar ro'yxati",
    t16: "Tranzaktsiyalar hajmi ro'yxati",
    t17: "ism",
    t18: "Oxirgi narx",
    t19: "narx",
    t20: "Bugungi o'sish",
    t21: "O'sish yoki kamaytirish",
    t22: "24 soatlik savdo hajmi",
    t23: "Tranzaksiya",
    t24: "Hali hech qanday ma'lumot yo'q",
    t25: "Hammasini ko'rish",
    t26: "Xavfsiz, samarali, arzon narx",
    t27: "Mijozlarga onlayn xizmat ko'rsatish",
    t28: "Biznes hamkorligi",
    t29: "Kompaniya",
    t30: "Biz haqimizda",
    t31: "Yordam markazi",
    t32: "E'lon",
    t33: "BDX tokeni",
    t34: "mahsulot",
    t35: "Tangalar sotib oling",
    t36: "Web3 hamyon",
    t37: "Xizmat",
    t38: "Fikr-mulohaza",
    t39: "Valyuta listingiga ariza",
    t40: "Do'st taklifi",
    t41: "Huquqiy va xavflarni oshkor qilish",
    t42: "Muvofiqlik litsenziyasi",
    t43: "Pul yuvishga qarshi siyosat",
    t44: "Maxfiylik siyosati",
    t45: "Foydalanuvchi shartnomasi",
    t46: "Huquqiy bayonot",
    t47: "Xavf haqida ogohlantirish",
    t48: "ST qoidasi",
    t49: "plugin hamyon",
    t50: "Hamyonni yuklab olish",
    t51: "Til",
    t52: "Chiqish",
    t53: "Hamyonni ulash",
    t54: "Yuklanmoqda...",
    t55: "Boshqa emas...",
    t56: "BeingDex haqida",
    t57: "BeingDex ortida blokcheyn texnologiyasini erta qo'llovchilar va blokcheynning kelajakdagi rivojlanishiga ishonuvchilar guruhi turibdi.",
    t58: "2018 yildan beri biz kriptovalyuta birjasini tashkil qildik va foydalanuvchilarga yanada oqilona savdo qilishlariga yordam berish uchun xavfsiz, bir martalik savdo echimlarini taqdim etishga qaror qildik.",
    t59: "Markazlashtirilmagan savdo platformasiga mos keladigan to'liq zanjirli kutilayotgan buyurtma",
    t60: "Global ro'yxatdan o'tgan manzil",
    t61: "100 000+",
    t62: "30 million USDT",
    t63: "Kundalik savdo hajmi",
    t64: "Bizning hikoyamiz",
    t65: "Bu blokcheyn va shifrlangan aktivlarga qattiq ishonadigan geekslar guruhi. 2010 yilda biz elektron tijorat OTC platformasi orqali birinchi Bitcoinni sotib oldik. O‘sha paytda biz asabiy va bezovta edik. Sanoat tsikli o'zgargan sari, tranzaksiya usullari va mahsulot shakllari innovatsiyalar va rivojlanishda davom etmoqda, bu Cex va Dex bir vaqtning o'zida rivojlanayotgan vaziyatni taqdim etadi. Shu bilan birga, biz mavjud Dex o'zining model mexanizmi bilan cheklanganligini va aktivlarning samaradorligini maksimal darajada oshira olmasligini ham tushunamiz. <br>Shu bilan birga, shifrlash sanoati butun dunyo bo'ylab tobora kengroq va chuqur ta'sirga ega bo'lganligi sababli, rivojlangan hududlardan tashqari, zaif moliyaviy infratuzilmaga ega bo'lgan hududlardan ham tobora ko'proq odamlar qo'shila boshladilar, ammo ular kompleksni tushunishda qiynalmoqda. moliyaviy mahsulotlar va Algoritmik mexanizm ularning yangi dunyolar va yangi aktivlarga ulanishiga to'sqinlik qiladigan bo'shliqqa aylandi. <br>BeingDex ushbu bo'shliqni engib o'tishga va yangi aqlli shartnomalar orqali to'liq zanjirli dastur mahsulotlari va ekologiyasini yaratishga intiladi. <br>Mavjudlik 'mavjudlik', 'mohiyat' va 'biologik hayot' kabi ma'nolarga ega bo'lib, bu bizning narsalarning kelib chiqishini o'rganish ruhimizni, mahsulot qiymati bo'yicha asosiy amaliyotimizni va foydalanuvchi tajribasiga intilishimizni ifodalaydi. Biz o'zimizni rag'batlantiramiz. va shu bilan birga, biz ko'proq odamlarni o'z fikrlarini ochishlari va kripto aktivlarini qabul qilishlari va ulardan foydalanish oson va do'stona mahsulot xizmatlari orqali kripto boyliklari bo'yicha o'zlarining sayohatlarini boshlashlariga yordam berishlarini taklif qilamiz.",
    t66: "Vision",
    t67: "Web3 orqali yanada erkin, adolatli va shaffofroq kelajak boylik dunyosini yarating",
    t68: "Missiya",
    t69: "Hamma foydalanishi mumkin bo'lgan yakuniy savdo platformasini yarating va sanoatda raqamli aktivlar moliyaviy xizmatlarini ko'rsatuvchi yetakchi provayderga aylang",
    t70: "Bizning qadriyatlarimiz",
    t71: "Birinchi foydalanuvchi",
    t72: "Har bir foydalanuvchining ehtiyojlari va munosabatlariga e'tibor bering, ob'ektiv va samimiy muloqot qiling va platforma ma'lumotlarini o'z vaqtida chiqaring.",
    t73: "Yaxlitlik va qat'iylik",
    t74: "Biz 'yomonlik qilmang' tamoyiliga amal qilamiz va mas'uliyat va mas'uliyat orqali bozor va foydalanuvchilarning ishonchini qozonamiz.",
    t75: "Innovatsiya va tashabbuskor",
    t76: "Ekstremal mahsulotlar va xizmatlar va tizimli afzalliklarni yaratish bizning abadiy izlanishimizdir.",
    t77: "Oxirini yodda tutgan holda boshlang",
    t78: "Uzoq muddatli sheriklar bilan uzoq muddatli ishlarni bajaring, jarayonni tushuning, shart-sharoitlarni yarating, fikr-mulohazalar natijalariga e'tibor bering va doimiy ravishda muhim maqsadlarga erishing.",
    t79: "Bizning jamoamiz",
    t80: "10 dan ortiq mamlakatlardan 150 dan ortiq xodimlarga ega BeingDEX jamoasi sayyoramizning har bir burchagidan kelgan katta iste'dodlarga ega bo'lib, bizga chinakam global kirish imkoniyatini beradi.",
    t81: "Bizning xizmatlarimiz",
    t82: "BeingDEX",
    t83: "BeingDex - bu ko'p zanjirli rivojlanishga asoslangan yangi markazlashtirilmagan birja. U zanjirdagi tartibni moslashtirish modelini qabul qiladi va o'zaro zanjirli ko'prik BSC, TRON va OKX ommaviy zanjirlarini qo'llab-quvvatlaydi.",
    t84: "Hamyon bo'lish",
    t85: "Being Wallet ikkita asosiy xavfsizlik mexanizmini qabul qiladi: foydalanuvchi aktivlarini o'z-o'zini saqlash va to'liq anonimlik. Uning asosiy hamyon texnologiyasi mahalliy biometrik shifrlash va xavfsizlik izolyatsiyasi kabi bir nechta xavfsizlik himoyasini qo'llab-quvvatlaydi va foydalanuvchilarning xavfsizligini himoya qilish uchun ko'p zanjirli aktivlarni boshqarishni qo'llab-quvvatlaydi. tranzaktsiyalar.",
    t86: "NFT bo'lish",
    t87: "NFT bo'lish ETH, BSC, Mango, TRON, Polygon, Solana ko'p zanjirli bir marta bosish orqali NFT chiqarishni qo'llab-quvvatlaydi, tranzaktsiyalar va boshqa harakatlar uchinchi tomon aralashuvisiz zanjir protokoli orqali amalga oshiriladi. DAO tomonidan tashkil etilgan NFT hamyonda saqlanadi. On-zanjirli kasting, aqlli tranzaktsiyalar, xavfsiz va qulay.",
    t88: "Kripto sayohatingizni hoziroq boshlang!",
    t89: "Millionlab foydalanuvchilar ishonadigan platformada savdo qiling.",
    t90: "Yuklash muvaffaqiyatli",
    t91: "Yuklash muvaffaqiyatsiz tugadi",
    t92: "Iltimos, siz tegishli bo'lgan umumiy zanjirni tanlang",
    t93: "Iltimos, loyiha nomini kiriting",
    t94: "Iltimos, logotipni yuklang",
    t95: "Iltimos, token qisqartmasini kiriting",
    t96: "Iltimos, shartnoma manzilini kiriting",
    t97: "Emissiya miqdorini kiriting",
    t98: "Iltimos, rasmiy veb-sayt havolasini kiriting",
    t99: "Iltimos, elektron pochta manzilingizni kiriting",
    t100: "Iltimos, token ma'lumotlarini kiriting",
    t101: "Yuborish muvaffaqiyatli",
    t102: "BeingDex valyuta listing ilovasi",
    t103: "BeingDex Exchange'ga e'tiboringiz uchun tashakkur. Iltimos, ariza formasini to'ldiring va to'g'ri ma'lumot bering. Siz taqdim etgan ma'lumotlar asosida loyihangizni ko'rib chiqamiz. Iltimos, ushbu arizani yuboring va loyihangiz valyuta listing bo'limiga yuboriladi. Ko‘rib chiqish. Dastlabki ko‘rib chiqishdan o‘tganingizdan so‘ng, biz valyuta listingi bo‘yicha mutaxassisni siz bilan valyuta listing jarayoni va usullarini baham ko‘rishi va valyuta listingi jarayoni bo‘yicha sizga yo‘l-yo‘riq ko‘rsatishi uchun tashkil qilamiz.",
    t104: "kerak ekanligini bildiradi",
    t105: "U tegishli bo'lgan jamoat zanjiri",
    t106: "Loyiha nomi",
    t107: "Token qisqartmasi",
    t108: "Shartnoma manzili",
    t109: "Emissiya miqdori",
    t110: "Rasmiy veb-sayt havolasi",
    t111: "Pochta qutisi",
    t112: "Token ma'lumotlari",
    t113: "Iltimos, token ma'lumotlarini kiriting, 120 belgidan oshmasligi kerak",
    t114: "Yuborish",
    t115: "Hamyonga ulangandan keyin yuboring",
    t116: "Shakl tarkibini tozalash",
    t117: "BDX kripto sanoatidagi inqilobni boshqaradi",
    t118: "Web3 dunyosini tezda ochishga yordam berish uchun aktivlaringizni, DeFi ilovalarini va NFTlarni ulang",
    t119: "BDXni bir marta bosish bilan oling",
    t120: "BDX oq qog'ozi",
    t121: "BDX ga kirish",
    t122: "BDX-ni ushlab turing va cheksiz imtiyozlardan bahramand bo'ling",
    t123: "Yangi obuna",
    t124: "Imtiyozli xizmat",
    t125: "Deflyatsiya mexanizmi",
    t126: "Yangi onlayn",
    t127: "Rejalashtirish",
    t128: "BDXni oling",
    t129: "BDX nashri haqida ma'lumot",
    t130: "Xavfsiz, ishlatish uchun qulay va butun dunyodagi madaniyatlar va mafkuralar bilan chambarchas bog'liq",
    t131: "Token nomi",
    t132: "Token belgisi",
    t133: "Egalik zanjiri",
    t134: "Shartnoma manzili",
    t135: "Emissiya narxi",
    t136: "aylanma ta'minoti",
    t137: "Jami ta'minot",
    t138: "Emissiya sanasi",
    t139: "BDXni almashtiring",
    t140: "Mavjud BDX tokenlarini sotib olish uchun",
    t141: "Jamoa motivatsiyasi",
    t142: "Har 6 oyda 2% qulfdan chiqariladi, 5 yildan keyin (60 oy) toʻliq ochiladi",
    t143: "Iqtisodiy va ekologik investitsiyalar",
    t144: "Fond sarmoyasi uchun BeingDex ekotizimiga o'ting",
    t145: "Brendni ilgari surish",
    t146: "Yiliga maksimal nashrlar",
    t147: "Foydalanuvchi kiritishi",
    t148: "Himoya fondi",
    t149: "Platformada yuzaga kelishi mumkin bo'lgan baxtsiz hodisalar uchun kompensatsiya uchun",
    t150: "Xavfsiz va ishonchli BDX ekotizimini yaratish va Web3 ning jadal rivojlanishiga yordam berish uchun biz bilan ishlang",
    t151: "BDXni bir marta bosish bilan oling",
    t152: "Tavsiya etiladi",
    t153: "Oxirgi blog",
    t154: "Hali hech qanday ma'lumot yo'q",
    t155: "DApp ilovalari do'koni",
    t156: "Qidirish",
    t157: "Kategoriyani tanlang",
    t158: "Muhim Rad etish",
    t159: "Ushbu veb-saytda taqdim etilgan barcha kontent, giperhavola qilingan veb-saytlar, tegishli ilovalar, forumlar, bloglar, ijtimoiy media hisoblari va boshqa platformalar ('Sayt') faqat uchinchi tomon manbalaridan olingan umumiy ma'lumotlaringiz uchundir. Biz o'zimiz uchun javobgar emasmiz. kontent Hech qanday kafolatlar berilmaydi, shu jumladan, aniqlik va valyuta bilan cheklanmagan. Biz taqdim etayotgan kontentning hech bir qismi moliyaviy maslahat, yuridik maslahat yoki boshqa har qanday maslahat shaklini tashkil etmaydi va har qanday maqsadda sizning maxsus ishonchingizni qondirish uchun moʻljallangan. Kontentimizdan har qanday foydalanish yoki unga tayanish sizning xavf-xataringiz va ixtiyoringiz ostida amalga oshiriladi. Kontentimizga tayanishdan oldin siz o‘zingiz tadqiqot, ko‘rib chiqish, tahlil va tekshirishni o‘tkazishingiz kerak. Savdo katta yo‘qotishlarga olib kelishi mumkin bo‘lgan yuqori xavfli faoliyatdir, shuning uchun Har qanday qaror qabul qilishdan oldin moliyaviy maslahatchi bilan maslahatlashing. Bizning veb-saytimizda hech narsa taklif yoki taklif emas.",
    t160: "Iltimos, taklif tafsilotlarini kiriting",
    t161: "Yuborish muvaffaqiyatli",
    t162: "Har bir taklifingiz",
    t163: "Biz diqqat bilan tinglaymiz va unga jiddiy munosabatda bo'lamiz",
    t164: "Fikr-mulohaza",
    t165: "Agar siz biron bir xavfsizlik kamchiligi yoki zaifligini topsangiz, iltimos, bizga o'z vaqtida fikr-mulohaza bildiring",
    t166: "Agar sizda biron bir savol bo'lsa, tez-tez beriladigan savollarga javob olish uchun Yordam markaziga murojaat qiling.",
    t167: "Mahsulotimiz haqida qanday fikrdasiz?",
    t168: "Yaxshi tajriba emas!",
    t169: "Yaxshilanishi kerak!",
    t170: "Juda qoniqarli!",
    t171: "Ajoyib!",
    t172: "Taklifni yuborish",
    t173: "Mahsulot takliflaringizni baham ko'rishga xush kelibsiz. BeingDex sizning fikr-mulohazalaringizni jiddiy qabul qiladi. Agar shoshilinch savollaringiz bo'lsa, mijozlarga xizmat ko'rsatish bilan bog'laning.",
    t174: "Tavsiya etilgan toifa",
    t175: "Xavfsizlik bo'yicha tavsiyalar",
    t176: "Xususiyatlar takliflari",
    t177: "Dizayn takliflari",
    t178: "Operatsiya bo'yicha takliflar",
    t179: "Boshqa takliflar",
    t180: "Taklif tafsilotlari",
    t181: "Iltimos, fikr-mulohazangizni kiriting, 500 belgidan oshmasligi kerak",
    t182: "Rasmlarni yuklash (ixtiyoriy)",
    t183: "Iltimos, muammoga oid skrinshotlarni yuklang. Rasm formati JPG yoki PNG va hajmi 2M dan oshmasligi kerak",
    t184: "Kontakt ma'lumotlari (ixtiyoriy)",
    t185: "Iltimos, kontakt ma'lumotlarini kiriting",
    t186: "Yuborishni tasdiqlang",
    t187: "Hamyonga ulangandan keyin yuboring",
    t188: "Qoralamani saqlash",
    t189: "Bu qanday ishlaydi?",
    t190: "Taklifni yuborish",
    t191: "Jamoani ko'rib chiqish",
    t192: "Mukofotlarni tarqatish",
    t193: "BeingDex butun dunyo bo'ylab foydalanuvchilarga xizmat qiladi. Biz platformaning xavfsiz va barqaror rivojlanishini o'zimizning eng ustuvor vazifamiz deb bilamiz. Sizning qimmatli takliflaringizni kutamiz. Keling, mahsulot sifatini yaxshilaymiz va birgalikda yaxshi kelajak yaratamiz.",
    t194: "Web3 foydalanuvchilari ishonishi mumkin bo'lgan protokol<br>Defi foydalanuvchilariga tranzaktsiyalarni osonlik bilan yakunlash imkonini beradi",
    t195: "Aktivlarni o'z-o'zini saqlash, hamyonni nuqtadan nuqtaga mos keladigan operatsiyalar",
    t196: "Nolinchi baxtsiz hodisalar bilan xavfsizlik va sof aqlli shartnomani bajarish",
    t197: "Asl markazlashtirilmagan K-chiziq diagrammasi, mahalliy afzalliklar",
    t198: "Mashhur kriptovalyutalar",
    t199: "BeingDex Ekologiyasi",
    t200: "O'z aktivlaringizni osongina boshqaring",
    t201: "BeingDex - bu sof aqlli shartnomalar bilan qurilgan markazlashmagan savdo platformasiga mos keladigan buyurtmalar kitobi. Umumiy ekologik tartib Crypto, Wallet, DEX, DeFi, GameFi, DAO, NFT, kon hovuzlari va boshqa sohalarni qamrab oladi.",
    t202: "Hamyon va tranzaksiyani birlashtirgan markazlashtirilmagan mahsulot",
    t203: "BeingDex - sof aqlli shartnomalar bilan qurilgan markazlashtirilmagan savdo platformasiga mos keladigan buyurtma",
    t204: "Ilova - BeingDex diversifikatsiyalangan ekologik mahsulotlar",
    t205: "Hamyon - ko'p zanjirli aktivlaringizni boshqaring",
    t206: "Savdo istalgan vaqtda va istalgan joyda amalga oshirilishi kerak",
    t207: "Ilovani yuklab oling va biz sizga 24/7 savdo qilishda yordam beramiz",
    t208: "Yuklab olish uchun skanerlash",
    t209: "Media resurslari",
    t210: "Muvofiqlik va siyosat",
    t211: "Foydalanuvchi aktivlarining xavfsizligini ta'minlash uchun xavfsizlik muvofiqligini global rasmiy sertifikatlash",
    t212: "AQSh MSB litsenziyasini oling",
    t213: "2023 yil 28-noyabr",
    t214: "Dubay DMCC litsenziyasi uchun ariza kutilmoqda",
    t215: "Gongkong Qimmatli qog'ozlarni tartibga solish komissiyasi/VARA/DIFC/ADGM/US MTL va boshqalar litsenziyalari uchun ariza",
    t216: "Bizning hamkorlarimiz",
    t217: "Axborot texnologiyalari sohasida 15+ yillik tajriba.<br>AWS, GCP, Azure va DevOps/SystemOps/DevOps vositalarida tajribaga ega yuqori malakali bulutli hisoblash/DevOps va ilovalar arxitektori va xizmatlar haqida keng tushunchaga ega.<br>8 + Moliyaviy sektorda Cloud/DevSecOps/Application Arxitektori sifatida ishlagan yillik tajriba<br>Mening Blockchain Mind startapim uchun Kanadadagi birinchi kriptovalyuta apparat hamyoni prototipini ishlab chiqdi.",
    t218: "Do'stlaringizni taklif qiling va<br>9 000 USDT gacha yutib oling",
    t219: "Taklif havolasi",
    t220: "Hozir taklif qiling",
    t221: "Hamyonga ulangandan keyin taklif qiling",
    t222: "Taklif yozuvi",
    t223: "Foydalanuvchi nomi",
    t224: "Ro'yxatdan o'tish vaqti",
    t225: "To'ldirish standartga yetdi",
    t226: "Tranzaksiya standartga javob beradi",
    t227: "Depozit bonusi",
    t228: "Ko'r quti",
    t229: "Ommaviy hodisalar",
    t230: "Qoidalar",
    t231: "1. Taklif etilgan do‘st to‘ldirish vazifasini bajarsa, taklif qiluvchi 100 USDT chegirma kuponiga ega bo‘ladi. Taklif etilgan do'st tranzaksiya topshirig'ini bajargandan so'ng, taklif qiluvchi tasodifiy ravishda 5-500 USDT miqdoridagi ko'r quti mukofotini olishi mumkin. <br> 2. To'ldirish vazifasi: Taklif etilgan do'st ro'yxatdan o'tganidan keyin 30 kun ichida belgilangan kanallar orqali to'ldiring va to'plangan to'lov 50USDT dan oshadi. <br> 3. Savdo vazifasi: Taklif etilgan do'st ro'yxatdan o'tganidan keyin 30 kun ichida to'plangan spot yoki shartnoma tranzaksiyalari hajmi 200USDT dan oshadi. <br>4. Taklif etilgan doʻstlar savdo topshirigʻi mukofotini ochishdan oldin toʻldirish vazifasini bajarishlari kerak. Agar taklif qilingan do'stingiz to'ldirish topshirig'ini muvaffaqiyatli bajara olmasa, tranzaksiya 200USDT dan oshgan taqdirda ham siz mukofotni qo'lga kirita olmaysiz. <br> 5. Belgilangan to'ldirish kanallari: Yaroqli to'ldirish zanjirda to'ldirish, fiat valyutasini to'ldirish, karta xaridlari, C2C tranzaksiyalari va uchinchi tomon to'lovlari bilan cheklangan. Ichki o'tkazmalar va qizil konvertlar samarali to'ldirishga kiritilmagan. 6. Taklif etuvchi har oyda 15 tagacha ishlov berish to'lovi chegirma kuponlari va 15 ta pul mukofotlarini olishi mumkin. <br> 7. Amal qilish muddati: Ishlov berish to'lovi chegirib tashlangan kupon berilgandan keyin 14 kun ichida olinishi kerak. To'lovdan keyin amal qilish muddati - 14 kun. Iltimos, mukofot muddati tugamasligi uchun uni o'z vaqtida olish va ishlatishga e'tibor bering. ; koʻr-koʻrona sovgʻadan foydalanish muddati 90 kun davomida amal qiladi. Iltimos, mukofotni olganingizdan soʻng, pul kuponini imkon qadar tezroq qaytarib oling. Qabul qilingandan soʻng, naqd pul kuponi 14 kun davomida amal qiladi. <br> 8. Xuddi shu IP-manzil yoki qurilmadan kelgan taklifnomalar o'z-o'zidan taklif qilingan deb hisoblanadi. O'z-o'zini taklif qilish foydalanuvchining allaqachon qo'lga kiritgan mukofotlarini va kelajakdagi mukofotlarni olish huquqidan mahrum bo'lishiga olib keladi. BeingDex noqonuniy hisoblarni muzlatish va hisoblardagi aktivlarni musodara qilish huquqini o'zida saqlab qoladi. <br>9. Mukofotlar taqsimlanganda, tizim joriy ikki tomonning eksklyuziv hamkor maqomiga ega ekanligini avtomatik ravishda aniqlaydi. Agar taklif qiluvchi yoki taklif etuvchi eksklyuziv hamkor bo'lsa, mukofot hamkorning eksklyuziv chegirma mukofotiga zid keladi va mukofot berilmaydi. Bundan tashqari, sub-hisoblar mustaqil hisoblar sifatida faoliyatda qatnasha olmaydi va ma'lumotlar asosiy hisobga birlashtirilmaydi. <br> 10. Yuqoridagi qoidalar 2023-yil 11-may soat 18:00 dan (UTC+8) kuchga kiradi. BeingDex ushbu faoliyatni yakuniy talqin qilish huquqini o'zida saqlab qoladi. BeingDex platforma zaifliklaridan foydalanadigan har qanday zararli xatti-harakatlar yoki noqonuniy va axloqsiz xatti-harakatlar aniqlansa, foydalanuvchi hisoblari va aktivlari bilan ishlash huquqini o'zida saqlab qoladi. <br> 11. Siz oʻzingizni BeingDex rasmiysi sifatida koʻrsata olmaysiz va notoʻgʻri bayonotlar bera olmaysiz, jumladan, “BeingDex”, “BeingDex login”, “BeingDex official”, “BeingDex C2C” kabi kalit soʻzlarni xarid qilish, lekin ular bilan cheklanmagan holda reklama qilish uchun. qidiruv tizimlarida. Talablarni buzganlar mukofotlar va ko'tarilishlardan mahrum qilinadi.",
    t232: "Muvofiqlik va xavfsizlik",
    t233: "BeingDex keng qamrovli muvofiqlik va xavfsizlikni boshqarish tizimini joriy qilishni talab qiladi va xavflarni har tomonlama boshqarish va monitoringini ta'minlash uchun muvofiqlik bo'yicha maslahat guruhi tomonidan ishlab chiqilgan qat'iy standartlar va jarayonlarga amal qiladi.<br>Platforma potentsial xavfni aniqlash uchun muntazam ravishda keng qamrovli xavflarni baholashni amalga oshiradi. punktlari bozor xavfi va operatsion riskni o'z ichiga oladi.Tavakkalchilikni boshqarishning samarali strategiyalarini amalga oshiring, mumkin bo'lgan ichki va tashqi xavflarni faol kuzatib boring va aniqlang va tegishli javob choralarini ko'ring.Tashqi omillardan kelib chiqadigan xavflar uchun BeingDex ilg'or shifrlash texnologiyasidan foydalanadi.Ma'lumotlar xavfsizligini himoya qiladi.Ichki xavflar uchun. , qat'iy ichki nazorat mexanizmini, jumladan, mas'uliyatni aniqlashtirish uchun ruxsat berish mexanizmini o'rnatish va muntazam ravishda ichki va tashqi auditlarni o'tkazish.<br>Mahalliy nazorat qiluvchi organlar bilan muntazam ravishda muvofiqlashtirish va muvofiqlikni tekshirish orqali bunga ichki tashqi qonunlar va qoidalar kiradi, ayniqsa moliyaviy xizmatlar, ma'lumotlarni himoya qilish va pul yuvishga qarshi kurash (AML), kompaniya faoliyatining muvofiqligi va xavfsizligini ta'minlash va platformaning barcha amaldagi moliyaviy qoidalar va standartlarga muvofiqligini ta'minlash.",
    t234: "Muvofiqlikni boshqarish tizimi",
    t235: "Identifikatsiya",
    t236: "Baholash",
    t237: "Bajarish",
    t238: "baholash",
    t239: "1. Muvofiqlikni boshqarish",
    t240: "Muvofiqlik bo'yicha mutaxassislar guruhi nazorati ostida BeingDex qat'iy muvofiqlik standartlari va protokollariga amal qiladi, muvofiqlikni boshqarishning keng qamrovli tuzilmasini amalga oshiradi va samarali identifikatsiya, baholash, bajarish va baholashni amalga oshiradi.<br>BeingDex tashqi manbalarni faol ravishda aniqlaydi va aniqlaydi. va ichki xavflarni bartaraf etish va zarur chora-tadbirlarni ko'rish.Tashqi xavflar tashqi o'zgarishlar natijasida yuzaga kelishi mumkin bo'lgan xavflarni bildiradi, masalan, BeingDex agentlarining uchinchi tomon reklamalari tomonidan chop etilgan noto'g'ri ma'lumotlar.<br> Ichki xavflar tashqi o'zgarishlardan kelib chiqadigan xavflarni anglatadi. Tashkilot Ichki xodimlar tomonidan ruxsat etilmagan, nomaqbul, noqonuniy yoki axloqsiz xatti-harakatlar kabi xavflar.<br>BeingDex muvofiqlik standartlarimiz mahalliy talablarga javob berishini ta'minlash uchun baholash va yillik muvofiqlik tekshiruvlari kombinatsiyasi orqali mahalliy tartibga solish organlari bilan ishlaydi.",
    t241: "2.eKYC texnologiyasi",
    t242: "BeingDex platformani himoya qilish va potentsial firibgarlik va noqonuniy xavflarni kamaytirish uchun elektron identifikatsiyani (eKYC) tasdiqlaydi. Bunga qo'shimcha ravishda, BeingDex barcha tegishli yurisdiktsiyalarga rioya qilish uchun sanktsiyalar va pul yuvishga qarshi (AML) siyosatiga ega va platformada qalbakilashtirish yoki boshqa jinoiy faoliyatning oldini olish.<br>Mijozlarni tekshirish (CDD) uchun samaradorlik juda muhim, shuning uchun BeingDex muvofiqlik asosi ostida foydalanuvchi identifikatorini tekshirish (KYC) jarayonini optimallashtirish uchun eKYC texnologiyasini qabul qiladi. <br>Bu. texnologiya yuzni tanib olish va foydalanuvchi tomonidan taqdim etilgan identifikatsiya va real vaqtda portretlar oʻrtasida avtomatik oʻzaro moslashish imkonini beradi, shu bilan soxta identifikatorlarning oldini oladi va foydalanuvchilarning BeingDex platformasida shaxsiy identifikatorini tekshirish vaqtini sezilarli darajada qisqartiradi.",
    t243: "2. Blokcheyn tahlili",
    t244: "BeingDex platformadagi tranzaktsiyalarni yaqindan kuzatib borish va firibgarlik faoliyati va yuqori xavfli foydalanuvchilar paydo boʻlishi xavfini kamaytirish uchun tashqi blokcheyn tahlil vositalarini oʻrnatadi*. Blokcheynning oʻzgarmas va shaffof tabiati bizga platformadagi tranzaktsiyalarni har tomonlama aniqlash imkonini beradi. Barcha tranzaksiyalar.<br>*Yuqori xavfli foydalanuvchilar kiradi, lekin ular bilan cheklanmaydi:<br>- Nozik mamlakatlar yoki mintaqalardagi mijozlar<br>- Hukumat rasmiylari<br>- Nozik sohalardagi mijozlar (masalan, kapital talab qiluvchi korxonalar) <br>Tavakkalchilik va boshqaruv guruhimizni baholashga asoslanib, biz yuqori xavfli foydalanuvchilarga qarshi turli choralarni ko'ramiz, jumladan, muayyan vaziyatga qarab aktivlarni musodara qilish, bir nechta ko'rib chiqishlar yoki auditlar va hokazo.",
    t245: "3.Tarmoq xavfsizligi",
    t246: "BeingDex platforma xavfsizligi va barqarorligini yaxshilash uchun tarmoq xavfsizligi boʻyicha mustaqil ekspertlar bilan maslahatlashadi. Shu bilan birga, aniqlangan potentsial tahdidlarni tez va tezkor hal qilish uchun tarmoqqa kirish testi va zaifliklarni baholash yiliga ikki marta oʻtkaziladi.<br>Bundan tashqari Yuqoridagi testlar , BeingDex shuningdek, o'g'irlik, ruxsatsiz kirish yoki o'zgartirish kabi xavflarning oldini olish uchun barcha nozik ma'lumotlarni shifrlaydi. O'tkazilgan yoki saqlangan barcha ma'lumotlar shifrlangan va xatoga chidamli xotirada xavfsiz tarzda saqlanadi.",
    t247: "Operatsiya muvaffaqiyatli",
    t248: "Hammasi o'qilgan",
    t249: "Iqtiboslar",
    t250: "Bugungi o'zgarish",
    t251: "24 soatlik savdo hajmi",
    t252: "24 soatlik tranzaksiya hajmi",
    t253: "Ommaviy valyutalar",
    t254: "Oxirgi valyuta",
    t255: "Eng katta o'sish bo'lgan valyuta",
    t256: "Eng yuqori savdo hajmi valyutasi",
    t257: "Tezroq tranzaksiyalar, yaxshiroq aktivlar",
    t258: "Sizning kelajakdagi Web3 tranzaksiya hamyoningiz",
    t259: "Web3 olamining super portali",
    t260: "12 million foydalanuvchiga qo'shiling, eng katta NFT bozorini osongina ko'rib chiqing va BeingDex Wallet-da 20 000+ DApps bilan xavfsiz o'zaro aloqada bo'ling",
    t261: "Eng keng qamrovli va ishlatish uchun qulay NFT platformasidan rohatlaning",
    t262: "Bir nechta asosiy NFT bozorlarini jamlash, buyurtmalarni bir marta bosish orqali ommaviy joylashtirishni qo'llab-quvvatlash va istalgan valyutada NFTlarni sotib olish",
    t263: "Sotib olish",
    t264: "Blokcheyn hamma joyda sodir bo'lsin",
    t265: "Ko'p zanjirli hamyon, xavfsiz va ishlatish uchun qulay, blokcheyn kirish",
    t266: "Ochiq manbali hamyon",
    t267: "Ochiq manbali hamyon, o'z-o'zini himoya qiladigan shaxsiy kalit, ko'p qatlamli shifrlash",
    t268: "Yuragingizga ergashing va o'zingizni xotirjam his qiling",
    t269: "O'zaro zanjirli, qulay, markazlashtirilmagan, bir martalik talab",
    t270: "Markazlashtirilmagan hamyon",
    t271: "Issiq va sovuq aktivlarni ajratish, xavfsiz va qulay Token 40000+",
    t272: "Kriptoaktivlar",
    t273: "40 000+ kripto aktivlari DEXda savdo qilish uchun turli aktivlarni qo'llab-quvvatlaydi.",
    t274: "Ko'p shifrlash texnologiyasi",
    t275: "Kripto valyutani xavfsiz saqlang va o'z aktivlaringizni boshqaring.",
    t276: "Ko'p daromadli rejim",
    t277: "Stakeing, konchilik, DeFi, zanjirli o'yinlar.",
    t278: "Aktivlarni o'z-o'zini saqlash, hamyon operatsiyalarini tengdoshga moslashtirish",
    t279: "Nolinchi baxtsiz hodisalar bilan xavfsizlik va sof aqlli shartnomani bajarish",
    t280: "Asl markazlashtirilmagan K-chiziq diagrammasi, mahalliy afzalliklar",
    t281: "Sizning tanlovingiz ularniki bilan bir xil",
    t282: "1000+ yetakchi kompaniyalarning ishonchi va tanlovi",
    t283: "plugin hamyon",
    t284: "Pluginni o'rnatish bo'yicha qo'llanma",
    t285: "Dunyodagi yetakchi blokcheyn raqamli aktivlarni boshqarish vositasi",
    t286: "Sof aqlli shartnoma bajarilishi",
    t287: "Hozir yuklab oling",
    t288: "DApp Ekologik kirish",
    t289: "DeFi, GameFi va boshqalarni o'rganing va DApp iqtisodini tezda o'ynang",
    t290: "Boshlaymiz! Taklif yoki fikr-mulohaza yuborish uchun shu yerni bosing",
    t291: "Ko'proq ko'rish",
    t292: "Token turi",
    t293: "BeingDex, ko'p zanjirli<br>bir martalik aktivlarni boshqarish savdo platformasi<br>xavfsiz, samarali va arzon",
    t294: "BeingDex o'zaro zanjirli ko'prik",
    t295: "o'zbek",
    t296: "Hali ochilmagan",
    t297: "ishlaydi",
    t298: "hamyon",
    t299: "Almashtirish",
    t300: "Dapp",
    t301: "Blog"
  }
}