export default {
  text: {
    t1: "Nhà",
    t2: "Tham gia với chúng tôi",
    t3: "Cửa hàng Google",
    t4: "Cửa hàng Apple",
    t5: "Tải xuống ứng dụng",
    t6: "Tải xuống Chrome",
    t7: "Tải xuống cục bộ",
    t8: "Giá tiền tệ BDX",
    t9: "Khối lượng giao dịch",
    t10: "Người dùng cộng đồng",
    t11: "Số lượng giao dịch",
    t12: "Tổng khối lượng giao dịch BDX",
    t13: "Danh sách tăng trưởng",
    t14: "Danh sách từ chối",
    t15: "Danh sách tiền xu mới",
    t16: "Danh sách khối lượng giao dịch",
    t17: "tên",
    t18: "Giá mới nhất",
    t19: "giá",
    t20: "Mức tăng hôm nay",
    t21: "Tăng hoặc giảm",
    t22: "Khối lượng giao dịch 24 giờ",
    t23: "Giao dịch",
    t24: "Chưa có dữ liệu",
    t25: "Xem tất cả",
    t26: "An toàn, hiệu quả, chi phí thấp",
    t27: "Dịch vụ khách hàng trực tuyến",
    t28: "Hợp tác kinh doanh",
    t29: "Công ty",
    t30: "Giới thiệu về chúng tôi",
    t31: "Trung tâm trợ giúp",
    t32: "Thông báo",
    t33: "Mã thông báo BDX",
    t34: "sản phẩm",
    t35: "Mua xu",
    t36: "Ví Web3",
    t37: "Dịch vụ",
    t38: "Phản hồi",
    t39: "Đơn xin niêm yết tiền tệ",
    t40: "Lời mời kết bạn",
    t41: "Tiết lộ rủi ro và pháp lý",
    t42: "Giấy phép tuân thủ",
    t43: "Chính sách chống rửa tiền",
    t44: "Chính sách quyền riêng tư",
    t45: "Thỏa thuận người dùng",
    t46: "Tuyên bố pháp lý",
    t47: "Cảnh báo rủi ro",
    t48: "quy tắc ST",
    t49: "ví cắm",
    t50: "Tải ví xuống",
    t51: "Ngôn ngữ",
    t52: "Đăng xuất",
    t53: "Kết nối ví",
    t54: "Đang tải...",
    t55: "Không còn nữa...",
    t56: "Giới thiệu về BeingDex",
    t57: "Đằng sau BeingDex là một nhóm những người sớm áp dụng công nghệ blockchain và tin tưởng vào sự phát triển của blockchain trong tương lai.",
    t58: "Kể từ năm 2018, chúng tôi đã thiết lập một sàn giao dịch tiền điện tử và cam kết cung cấp các giải pháp giao dịch một cửa, an toàn để giúp người dùng giao dịch thông minh hơn.",
    t59: "Đơn hàng chờ xử lý toàn chuỗi khớp với nền tảng giao dịch phi tập trung",
    t60: "Địa chỉ đăng ký toàn cầu",
    t61: "100.000+",
    t62: "30 triệu USDT",
    t63: "Khối lượng giao dịch hàng ngày",
    t64: "Câu chuyện của chúng tôi",
    t65: 'Đây là nhóm những người đam mê công nghệ có niềm tin vững chắc vào blockchain và tài sản mã hóa. Vào năm 2010, chúng tôi đã mua Bitcoin đầu tiên thông qua nền tảng thương mại điện tử OTC. Vào thời điểm đó, chúng tôi rất lo lắng và bất an. Theo chu kỳ của ngành những thay đổi, phương thức giao dịch và hình thức sản phẩm tiếp tục đổi mới và phát triển, tạo ra tình huống Cex và Dex phát triển đồng thời. Tuy nhiên, chúng tôi cũng nhận thấy rằng Dex hiện tại tuân theo cơ chế mô hình của nó và không thể tối đa hóa hiệu quả tài sản.<br >Đồng thời Hiện nay, khi ngành công nghiệp mã hóa có ảnh hưởng ngày càng rộng rãi và sâu sắc trên quy mô toàn cầu, bên cạnh các khu vực phát triển, ngày càng có nhiều người từ các khu vực có cơ sở hạ tầng tài chính yếu kém bắt đầu tham gia nhưng họ gặp khó khăn trong việc hiểu các sản phẩm tài chính phức tạp và cơ chế thuật toán. . , đây đã trở thành một khoảng cách ngăn cản họ kết nối thế giới mới và các tài sản mới.<br>BeingDex cam kết vượt qua khoảng cách này và xây dựng các sản phẩm và hệ sinh thái ứng dụng toàn chuỗi thông qua các hợp đồng thông minh mới.<br>Tồn tại có "sự tồn tại" " Các ý nghĩa như "bản chất" và "đời sống sinh học" thể hiện tinh thần khám phá nguồn gốc của sự vật, thực tiễn cơ bản về giá trị sản phẩm và mục tiêu cuối cùng của chúng tôi là trải nghiệm người dùng. Chúng tôi khuyến khích bản thân và chào đón nhiều người hơn nữa mở mang đầu óc và nắm bắt các tài sản mã hóa và giúp họ bắt đầu hành trình làm giàu bằng tiền điện tử của riêng mình thông qua các dịch vụ sản phẩm thân thiện và dễ sử dụng.',
    t66: "Tầm nhìn",
    t67: "Tạo ra một thế giới thịnh vượng trong tương lai tự do hơn, công bằng hơn và minh bạch hơn thông qua Web3",
    t68: "Sứ mệnh",
    t69: "Tạo nền tảng giao dịch tối ưu mà mọi người đều có thể sử dụng và trở thành nhà cung cấp dịch vụ tài chính tài sản kỹ thuật số hàng đầu trong ngành",
    t70: "Giá trị của chúng tôi",
    t71: "Người dùng là trên hết",
    t72: "Chú ý đến nhu cầu và thái độ của từng người dùng, giao tiếp khách quan và thẳng thắn, đồng thời cung cấp thông tin nền tảng kịp thời.",
    t73: "Chính trực và nghiêm khắc",
    t74: 'Chúng tôi tuân thủ nguyên tắc "không làm điều ác" và chiếm được lòng tin của thị trường cũng như người dùng thông qua trách nhiệm và trách nhiệm.',
    t75: "Đổi mới và dám nghĩ dám làm",
    t76: "Các sản phẩm và dịch vụ hoàn hảo cũng như việc xây dựng lợi thế về cấu trúc là mục tiêu theo đuổi vĩnh viễn của chúng tôi.",
    t77: "Bắt đầu với mục tiêu cuối cùng",
    t78: "Làm việc lâu dài với đối tác lâu dài, nắm bắt quy trình, tạo điều kiện, chú ý đến kết quả phản hồi và liên tục đạt được các mục tiêu quan trọng.",
    t79: "Đội của chúng tôi",
    t80: "Với hơn 150 nhân viên từ hơn 10 quốc gia, nhóm BeingDEX có những tài năng cấp cao từ mọi nơi trên hành tinh, mang lại cho chúng tôi phạm vi tiếp cận toàn cầu thực sự.",
    t81: "Dịch vụ của chúng tôi",
    t82: "BeingDEX",
    t83: "BeingDex là một sàn giao dịch phi tập trung mới dựa trên sự phát triển đa chuỗi. Nó áp dụng mô hình khớp lệnh trên chuỗi và cầu nối chuỗi chéo hỗ trợ các chuỗi công khai BSC, TRON và OKX.",
    t84: "Là Ví",
    t85: "Being Wallet áp dụng hai cơ chế bảo mật chính: tự quản lý tài sản của người dùng và ẩn danh hoàn toàn. Công nghệ ví cơ bản của nó hỗ trợ nhiều biện pháp bảo vệ như mã hóa sinh trắc học cục bộ và cách ly bảo mật, đồng thời hỗ trợ quản lý tài sản đa chuỗi để bảo vệ sự an toàn của người dùng giao dịch.",
    t86: "Là NFT",
    t87: "Là NFT hỗ trợ ETH, BSC, Mango, TRON, Polygon, Solana phát hành NFT đa chuỗi chỉ bằng một cú nhấp chuột, các giao dịch và các hoạt động khác được hoàn thành thông qua giao thức chuỗi mà không có sự can thiệp của bên thứ ba. NFT do DAO tổ chức là được lưu trữ trong ví. Truyền trực tuyến, giao dịch thông minh, an toàn và thuận tiện.",
    t88: "Bắt đầu hành trình tiền điện tử của bạn ngay bây giờ!",
    t89: "Giao dịch trên nền tảng được hàng triệu người dùng tin cậy.",
    t90: "Tải lên thành công",
    t91: "Tải lên không thành công",
    t92: "Vui lòng chọn chuỗi công khai mà bạn thuộc về",
    t93: "Xin vui lòng nhập tên dự án",
    t94: "Xin vui lòng tải lên logo",
    t95: "Xin vui lòng nhập tên viết tắt của token",
    t96: "Xin vui lòng nhập địa chỉ hợp đồng",
    t97: "Xin vui lòng nhập số lượng phát hành",
    t98: "Xin vui lòng nhập liên kết trang web chính thức",
    t99: "Xin vui lòng nhập địa chỉ email của bạn",
    t100: "Vui lòng nhập thông tin mã thông báo của bạn",
    t101: "Gửi thành công",
    t102: "Ứng dụng niêm yết tiền tệ BeingDex",
    t103: "Cảm ơn bạn đã quan tâm đến BeingDex Exchange. Vui lòng điền vào mẫu đơn đăng ký và cung cấp thông tin hợp lệ. Chúng tôi sẽ xem xét dự án của bạn dựa trên thông tin bạn cung cấp. Vui lòng gửi đơn đăng ký này và dự án của bạn sẽ được gửi đến bộ phận niêm yết tiền tệ . Đánh giá. Sau khi bạn vượt qua đánh giá sơ bộ, chúng tôi sẽ sắp xếp để một chuyên gia niêm yết tiền tệ chia sẻ quy trình và kỹ thuật niêm yết tiền tệ với bạn cũng như hướng dẫn bạn thực hiện quy trình niêm yết tiền tệ.",
    t104: "Cho biết bắt buộc",
    t105: "Chuỗi công khai mà nó thuộc về",
    t106: "Tên dự án",
    t107: "Viết tắt mã thông báo",
    t108: "Địa chỉ hợp đồng",
    t109: "Số lượng phát hành",
    t110: "Liên kết trang web chính thức",
    t111: "Hộp thư",
    t112: "Thông tin mã thông báo",
    t113: "Vui lòng nhập thông tin token của bạn, không quá 120 ký tự",
    t114: "Gửi",
    t115: "Gửi sau khi kết nối với ví",
    t116: "Xóa nội dung biểu mẫu",
    t117: "BDX dẫn đầu cuộc cách mạng trong ngành tiền điện tử",
    t118: "Kết nối tài sản, ứng dụng DeFi và NFT của bạn để giúp bạn mở khóa thế giới Web3 một cách nhanh chóng",
    t119: "Nhận BDX chỉ bằng một cú nhấp chuột",
    t120: "Sách trắng BDX",
    t121: "Giới thiệu về BDX",
    t122: "Giữ BDX và tận hưởng lợi ích vô tận",
    t123: "Đăng ký mới",
    t124: "Dịch vụ ưu đãi",
    t125: "Cơ chế giảm phát",
    t126: "Mới trực tuyến",
    t127: "Quy hoạch",
    t128: "Nhận BDX",
    t129: "Thông tin phát hành BDX",
    t130: "An toàn, dễ sử dụng và kết nối chặt chẽ với các nền văn hóa, tư tưởng trên thế giới",
    t131: "Tên mã thông báo",
    t132: "Biểu tượng mã thông báo",
    t133: "Chuỗi sở hữu",
    t134: "Địa chỉ hợp đồng",
    t135: "Giá phát hành",
    t136: "Cung cấp lưu thông",
    t137: "Tổng nguồn cung",
    t138: "Ngày phát hành",
    t139: "Thay thế BDX",
    t140: "Để đổi mã thông báo BDX hiện có",
    t141: "Động lực của nhóm",
    t142: "2% được mở khóa sau mỗi 6 tháng, sẽ được mở khóa hoàn toàn sau 5 năm (60 tháng)",
    t143: "Đầu tư kinh tế và sinh thái",
    t144: "Vào hệ sinh thái BeingDex để đầu tư quỹ",
    t145: "Quảng cáo thương hiệu",
    t146: "Số lượng phát hành tối đa mỗi năm",
    t147: "Đầu vào của người dùng",
    t148: "Quỹ bảo vệ",
    t149: "Để bồi thường cho các tai nạn có thể xảy ra trên sân ga",
    t150: "Hợp tác với chúng tôi để tạo ra một hệ sinh thái BDX an toàn và đáng tin cậy, đồng thời thúc đẩy sự phát triển nhanh chóng của Web3",
    t151: "Nhận BDX chỉ bằng một cú nhấp chuột",
    t152: "Được khuyến nghị",
    t153: "Blog mới nhất",
    t154: "Chưa có dữ liệu",
    t155: "Cửa hàng ứng dụng DApp",
    t156: "Tìm kiếm",
    t157: "Chọn danh mục",
    t158: "Tuyên bố từ chối trách nhiệm quan trọng",
    t159: 'Tất cả nội dung được cung cấp trên trang web này, các trang web siêu liên kết, ứng dụng liên quan, diễn đàn, blog, tài khoản mạng xã hội và các nền tảng khác ("Trang web") chỉ dành cho thông tin chung của bạn thu được từ các nguồn của bên thứ ba. Chúng tôi không chịu trách nhiệm về những thông tin chung của mình nội dung Không có đảm bảo nào được đưa ra, bao gồm nhưng không giới hạn ở tính chính xác và tiền tệ. Không có phần nội dung nào chúng tôi cung cấp cấu thành tư vấn tài chính, tư vấn pháp lý hoặc bất kỳ hình thức tư vấn nào khác và được thiết kế để đáp ứng sự tin cậy cụ thể của bạn cho bất kỳ mục đích nào. Bất kỳ Bất kỳ việc sử dụng hoặc dựa vào nội dung của chúng tôi đều do bạn tự chịu rủi ro và tùy ý quyết định. Bạn nên tiến hành nghiên cứu, đánh giá, phân tích và xác minh của riêng mình trước khi dựa vào nội dung của chúng tôi. Giao dịch là một hoạt động có rủi ro cao có thể dẫn đến thua lỗ đáng kể, vì vậy vui lòng tham khảo ý kiến ​​cố vấn tài chính của bạn trước khi đưa ra bất kỳ quyết định nào. Không có gì trên trang web của chúng tôi là lời mời chào hay đề nghị.',
    t160: "Xin vui lòng nhập chi tiết gợi ý",
    t161: "Gửi thành công",
    t162: "Mỗi đề xuất của bạn",
    t163: "Chúng tôi sẽ lắng nghe cẩn thận và xử lý nghiêm túc",
    t164: "Phản hồi",
    t165: "Nếu bạn phát hiện bất kỳ sai sót hoặc lỗ hổng bảo mật nào, vui lòng phản hồi kịp thời cho chúng tôi",
    t166: "Nếu bạn có bất kỳ câu hỏi nào, vui lòng tham khảo Trung tâm trợ giúp để biết câu trả lời cho các câu hỏi thường gặp.",
    t167: "Bạn nghĩ gì về trải nghiệm sản phẩm của chúng tôi?",
    t168: "Trải nghiệm không mấy tốt đẹp!",
    t169: "Để được cải thiện!",
    t170: "Khá thỏa đáng!",
    t171: "Siêu tuyệt vời!",
    t172: "Gửi đề xuất",
    t173: "Chào mừng bạn chia sẻ đề xuất sản phẩm của mình. BeingDex sẽ xem xét phản hồi của bạn một cách nghiêm túc. Nếu bạn có thắc mắc khẩn cấp, vui lòng liên hệ với bộ phận dịch vụ khách hàng.",
    t174: "Danh mục được đề xuất",
    t175: "Khuyến nghị an toàn",
    t176: "Gợi ý tính năng",
    t177: "Gợi ý thiết kế",
    t178: "Gợi ý hoạt động",
    t179: "Các đề xuất khác",
    t180: "Chi tiết đề xuất",
    t181: "Vui lòng nhập phản hồi của bạn, không quá 500 ký tự",
    t182: "Tải ảnh lên (tùy chọn)",
    t183: "Vui lòng tải lên ảnh chụp màn hình liên quan đến sự cố. Định dạng hình ảnh là JPG hoặc PNG và kích thước không được vượt quá 2M",
    t184: "Thông tin liên hệ (tùy chọn)",
    t185: "Xin vui lòng nhập thông tin liên hệ",
    t186: "Xác nhận gửi",
    t187: "Gửi sau khi kết nối với ví",
    t188: "Lưu bản nháp",
    t189: "Nó hoạt động như thế nào?",
    t190: "Gửi đề xuất",
    t191: "Đánh giá nhóm",
    t192: "Phân phối phần thưởng",
    t193: "BeingDex phục vụ người dùng trên toàn thế giới. Chúng tôi coi sự phát triển an toàn và ổn định của nền tảng là ưu tiên hàng đầu của chúng tôi. Chúng tôi mong nhận được những đề xuất có giá trị của bạn. Hãy cùng cải thiện chất lượng sản phẩm và cùng nhau tạo ra một tương lai tốt đẹp hơn.",
    t194: "Một giao thức mà người dùng Web3 có thể tin cậy<br>cho phép người dùng Defi dễ dàng hoàn tất giao dịch",
    t195: "Tự quản lý tài sản, giao dịch khớp điểm-điểm ví",
    t196: "An toàn không có tai nạn và thực hiện hợp đồng thông minh thuần túy",
    t197: "Biểu đồ K-line phi tập trung gốc, lợi thế bản địa",
    t198: "Các loại tiền điện tử phổ biến",
    t199: "Hệ sinh thái BeingDex",
    t200: "Quản lý tài sản của bạn một cách dễ dàng",
    t201: "BeingDex là một sổ đặt hàng phù hợp với nền tảng giao dịch phi tập trung được xây dựng bằng các hợp đồng thông minh thuần túy. Bố cục sinh thái tổng thể bao gồm Tiền điện tử, Ví, DEX, DeFi, GameFi, DAO, NFT, nhóm khai thác và các ngành khác.",
    t202: "Một sản phẩm phi tập trung tích hợp ví và giao dịch",
    t203: "BeingDex - một nền tảng giao dịch phi tập trung khớp lệnh được xây dựng bằng các hợp đồng thông minh thuần túy",
    t204: "Ứng dụng - Sản phẩm sinh thái đa dạng BeingDex",
    t205: "Ví - Quản lý tài sản đa chuỗi của bạn",
    t206: "Giao dịch nên được thực hiện mọi lúc, mọi nơi",
    t207: "Tải App và chúng tôi sẽ giúp bạn giao dịch 24/7",
    t208: "Quét để tải xuống",
    t209: "Tài nguyên truyền thông",
    t210: "Tuân thủ và chính sách",
    t211: "Chứng nhận chính thức toàn cầu về tuân thủ bảo mật để đảm bảo an toàn cho tài sản của người dùng",
    t212: "Lấy giấy phép MSB của Hoa Kỳ",
    t213: "28 tháng 11 năm 2023",
    t214: "Đơn xin giấy phép Dubai DMCC đang chờ xử lý",
    t215: "Đơn xin giấy phép từ Ủy ban Điều tiết Chứng khoán Hồng Kông/VARA/DIFC/ADGM/US MTL, v.v.",
    t216: "Đối tác của chúng tôi",
    t217: "Hơn 15 năm kinh nghiệm trong lĩnh vực công nghệ thông tin.<br>Kiến trúc sư ứng dụng và điện toán đám mây/DevOps cấp cao có tay nghề cao, có kinh nghiệm về các công cụ AWS, GCP, Azure và DevOps/SystemOps/DevOps cũng như hiểu biết sâu rộng về dịch vụ.<br>8 + nhiều năm kinh nghiệm làm Kiến trúc sư ứng dụng/DevSecOps/đám mây trong lĩnh vực tài chính<br>Đã thiết kế nguyên mẫu ví phần cứng tiền điện tử đầu tiên của Canada cho công ty khởi nghiệp Blockchain Mind của tôi.",
    t218: "Mời bạn bè và giành giải thưởng lên tới<br>9.000 USDT",
    t219: "Liên kết lời mời",
    t220: "Mời ngay",
    t221: "Mời sau khi kết nối với ví",
    t222: "Bản ghi lời mời",
    t223: "Tên người dùng",
    t224: "Thời gian đăng ký",
    t225: "Nạp tiền đạt tiêu chuẩn",
    t226: "Giao dịch đạt tiêu chuẩn",
    t227: "Tiền thưởng gửi tiền",
    t228: "Hộp mù",
    t229: "Sự kiện phổ biến",
    t230: "Quy tắc",
    t231: '1. Khi người bạn được mời hoàn thành nhiệm vụ nạp tiền, người mời có thể nhận được phiếu giảm giá 100 USDT. Sau khi người bạn được mời hoàn thành nhiệm vụ giao dịch, người mời có thể rút ngẫu nhiên phần thưởng hộp mù từ 5-500 USDT.<br > 2. Nhiệm vụ nạp tiền: Trong vòng 30 ngày sau khi người bạn được mời đăng ký, hãy nạp tiền qua các kênh được chỉ định và số tiền gửi ròng tích lũy vượt quá 50USDT.<br> 3. Nhiệm vụ giao dịch: Trong vòng 30 ngày sau khi người bạn được mời đăng ký, giao dịch giao ngay hoặc hợp đồng tích lũy khối lượng vượt quá 200USDT. <br>4. Những người bạn được mời phải hoàn thành nhiệm vụ nạp tiền trước khi bạn có thể mở khóa phần thưởng nhiệm vụ giao dịch. Nếu người bạn được mời của bạn không hoàn thành thành công nhiệm vụ nạp tiền, bạn sẽ không thể nhận được phần thưởng ngay cả khi giao dịch vượt quá 200USDT.<br> 5. Kênh nạp tiền được chỉ định: Nạp tiền hợp lệ Chỉ cho phép nạp tiền trên chuỗi, nạp tiền bằng tiền hợp pháp, mua thẻ, giao dịch C2C và thanh toán của bên thứ ba. Chuyển khoản nội bộ và phong bì màu đỏ không được bao gồm trong lần nạp tiền hiệu quả. 6. Người mời có thể nhận được tối đa 15 phiếu giảm phí và 15 phiếu thưởng tiền mặt mỗi tháng.<br> 7. Thời hạn hiệu lực: Phiếu giảm phí xử lý phải được thu trong vòng 14 ngày sau khi phát hành và có giá trị trong 14 ngày sau khi thu. Vui lòng chú ý nhận và sử dụng kịp thời để tránh hết hạn phần thưởng, thời hạn hiệu lực của việc đổi phần thưởng hộp mù là 90 ngày. Vui lòng đổi phần thưởng phiếu tiền mặt càng sớm càng tốt sau khi nhận được phần thưởng. Phiếu tiền mặt có giá trị trong 14 ngày sau khi đổi quà.<br> 8. Lời mời từ cùng một địa chỉ IP hoặc thiết bị sẽ được coi là tự mời. Tự mời sẽ khiến người dùng mất Phần thưởng nhận được và tư cách nhận phần thưởng trong tương lai. BeingDex bảo lưu quyền đóng băng các tài khoản bất hợp pháp và tịch thu tài sản trong tài khoản.<br>9. Khi phần thưởng được phát hành, hệ thống sẽ tự động xác định xem hai bên hiện tại có tư cách đối tác độc quyền hay không. đối tác độc quyền, phần thưởng sẽ xung đột với phần thưởng giảm giá dành cho đối tác độc quyền và phần thưởng sẽ không được phát hành. Ngoài ra, các tài khoản phụ không thể tham gia các hoạt động với tư cách là tài khoản độc lập và dữ liệu sẽ không được hợp nhất vào tài khoản chính.<br > 10. Các quy định trên sẽ có hiệu lực từ 18:00 ngày 11 tháng 5 năm 2023 (UTC + 8). BeingDex có quyền giải thích cuối cùng về hoạt động này. Nếu phát hiện bất kỳ hành vi độc hại hoặc hành vi bất hợp pháp và phi đạo đức nào khai thác lỗ hổng nền tảng , BeingDex sẽ có quyền xử lý tài khoản và tài sản của người dùng.<br> 11. Bạn không được giả vờ là chính thức của BeingDex và đưa ra những tuyên bố sai lệch, bao gồm nhưng không giới hạn ở việc mua các từ khóa như "BeingDex", "Đăng nhập BeingDex", " BeingDex Official", "BeingDex C2C" Quảng bá trên các công cụ tìm kiếm. Những người vi phạm yêu cầu sẽ bị loại khỏi phần thưởng và khuyến mãi.',
    t232: "Tuân thủ và bảo mật",
    t233: "BeingDex kiên quyết triển khai hệ thống quản trị bảo mật và tuân thủ toàn diện, đồng thời tuân theo các tiêu chuẩn và quy trình nghiêm ngặt do nhóm tư vấn tuân thủ xây dựng để đảm bảo quản lý và giám sát rủi ro toàn diện.<br>Nền tảng thường xuyên tiến hành đánh giá rủi ro toàn diện để xác định rủi ro tiềm ẩn điểm bao gồm rủi ro thị trường và rủi ro hoạt động.Thực hiện các chiến lược quản lý rủi ro hiệu quả, chủ động theo dõi và xác định các rủi ro bên trong và bên ngoài có thể xảy ra, đồng thời thực hiện các biện pháp ứng phó phù hợp.Đối với các rủi ro do yếu tố bên ngoài gây ra, BeingDex sẽ sử dụng Công nghệ mã hóa tiên tiến để bảo vệ an toàn dữ liệu.Đối với các rủi ro nội bộ , thiết lập cơ chế kiểm soát nội bộ chặt chẽ, bao gồm cơ chế ủy quyền để làm rõ trách nhiệm và tiến hành kiểm toán nội bộ và bên ngoài thường xuyên.<br>Bằng cách thường xuyên phối hợp với các cơ quan quản lý địa phương và tiến hành đánh giá tuân thủ, điều này bao gồm các luật và quy định đối ngoại trong nước, đặc biệt là các quy định liên quan đến dịch vụ tài chính, bảo vệ dữ liệu và chống rửa tiền (AML), đảm bảo tính tuân thủ và bảo mật cho hoạt động của công ty cũng như đảm bảo rằng nền tảng tuân thủ tất cả các quy định và tiêu chuẩn tài chính hiện hành.",
    t234: "Khung quản lý tuân thủ",
    t235: "Nhận dạng",
    t236: "Đánh giá",
    t237: "Thực thi",
    t238: "đánh giá",
    t239: "1. Quản lý tuân thủ",
    t240: "Dưới sự giám sát của nhóm chuyên gia tuân thủ, BeingDex tuân theo các tiêu chuẩn và giao thức tuân thủ nghiêm ngặt, thực hiện cấu trúc quản lý tuân thủ toàn diện và tiến hành xác định, đánh giá, thực thi và đánh giá hiệu quả.<br>BeingDex tích cực phát hiện và xác định các nguồn từ Bên ngoài và rủi ro nội bộ và thực hiện các biện pháp khắc phục cần thiết.Rủi ro bên ngoài là những rủi ro có thể do những thay đổi bên ngoài gây ra, chẳng hạn như thông tin sai lệch được công bố bởi quảng cáo của bên thứ ba của đại lý BeingDex.<br> Rủi ro nội bộ là những rủi ro có thể đến từ bên trong tổ chức Rủi ro, chẳng hạn như hành vi trái phép, không phù hợp, bất hợp pháp hoặc phi đạo đức của nhân viên nội bộ.<br>BeingDex làm việc với các cơ quan quản lý địa phương thông qua việc kết hợp các đánh giá và đánh giá tuân thủ hàng năm để đảm bảo rằng các tiêu chuẩn tuân thủ của chúng tôi đáp ứng các yêu cầu của địa phương.",
    t241: "Công nghệ 2.eKYC",
    t242: "BeingDex áp dụng xác minh danh tính điện tử (eKYC) để bảo mật nền tảng và giảm rủi ro gian lận và bất hợp pháp tiềm ẩn. Ngoài ra, BeingDex còn áp dụng các chính sách trừng phạt và chống rửa tiền (AML) để tuân thủ tất cả các khu vực pháp lý có liên quan và ngăn chặn hàng giả hoặc các hoạt động tội phạm khác trên nền tảng.<br>Tính hiệu quả là rất quan trọng đối với sự thẩm định khách hàng (CDD), do đó, BeingDex áp dụng công nghệ eKYC để tối ưu hóa quy trình xác minh danh tính người dùng (KYC) dưới tiền đề tuân thủ. <br>Điều này công nghệ cho phép nhận dạng khuôn mặt và tự động đối chiếu chéo giữa nhận dạng do người dùng cung cấp và ảnh chân dung theo thời gian thực, từ đó ngăn chặn danh tính giả mạo và cũng rút ngắn đáng kể thời gian để người dùng tiến hành xác minh danh tính cá nhân trên nền tảng BeingDex.",
    t243: "2. Phân tích chuỗi khối",
    t244: "BeingDex triển khai các công cụ phân tích blockchain bên ngoài để giám sát chặt chẽ các giao dịch trên nền tảng và giảm nguy cơ hoạt động gian lận cũng như sự xuất hiện của những người dùng có rủi ro cao*. Bản chất bất biến và minh bạch của blockchain cho phép chúng tôi phát hiện toàn diện các giao dịch trên nền tảng Tất cả giao dịch.<br>*Người dùng có rủi ro cao bao gồm nhưng không giới hạn ở:<br>- Khách hàng ở các quốc gia hoặc khu vực nhạy cảm<br>- Quan chức chính phủ<br>- Khách hàng từ các ngành nhạy cảm (chẳng hạn như doanh nghiệp thâm dụng vốn) <br >Dựa trên đánh giá của nhóm quản trị và rủi ro, chúng tôi sẽ thực hiện nhiều biện pháp khác nhau chống lại người dùng có mức độ rủi ro cao, có thể bao gồm tịch thu tài sản, xem xét hoặc kiểm tra nhiều lần, v.v., tùy thuộc vào tình huống cụ thể.",
    t245: "3.An ninh mạng",
    t246: "BeingDex tư vấn cho các chuyên gia an ninh mạng độc lập để cải thiện tính bảo mật và tính ổn định của nền tảng. Đồng thời, việc kiểm tra thâm nhập mạng và đánh giá lỗ hổng được tiến hành hai lần một năm để xử lý kịp thời và nhanh chóng các mối đe dọa tiềm ẩn được phát hiện.<br>Ngoài ra Trong các thử nghiệm trên, BeingDex cũng mã hóa tất cả dữ liệu nhạy cảm để ngăn ngừa các rủi ro như trộm cắp, truy cập hoặc sửa đổi trái phép. Tất cả dữ liệu được truyền hoặc lưu đều được mã hóa và lưu trữ an toàn trong bộ lưu trữ có khả năng chịu lỗi.",
    t247: "Thao tác thành công",
    t248: "Đọc tất cả",
    t249: "Trích dẫn",
    t250: "Sự thay đổi của ngày hôm nay",
    t251: "Khối lượng giao dịch 24 giờ",
    t252: "Khối lượng giao dịch 24 giờ",
    t253: "Các loại tiền tệ phổ biến",
    t254: "Tiền tệ mới nhất",
    t255: "Đồng tiền có mức tăng lớn nhất",
    t256: "Đồng tiền có khối lượng giao dịch cao nhất",
    t257: "Giao dịch nhanh hơn, tài sản tốt hơn",
    t258: "Ví giao dịch Web3 trong tương lai của bạn",
    t259: "Siêu cổng thông tin của vũ trụ Web3",
    t260: "Tham gia cùng 12 triệu người dùng, dễ dàng duyệt qua thị trường NFT lớn nhất và tương tác an toàn với hơn 20.000 DApp trên Ví BeingDex",
    t261: "Tận hưởng nền tảng NFT toàn diện và dễ sử dụng nhất",
    t262: "Tổng hợp nhiều thị trường NFT chính thống, hỗ trợ đặt hàng hàng loạt chỉ bằng một cú nhấp chuột và mua NFT bằng bất kỳ loại tiền tệ nào",
    t263: "Mua hàng",
    t264: "Hãy để blockchain xuất hiện ở mọi nơi",
    t265: "Ví đa chuỗi, an toàn và dễ sử dụng, lối vào blockchain",
    t266: "Ví nguồn mở",
    t267: "Ví nguồn mở, khóa riêng tự duy trì, mã hóa nhiều lớp",
    t268: "Hãy nghe theo trái tim mình và cảm thấy thoải mái",
    t269: "Chuỗi chéo, thuận tiện, phi tập trung, nhu cầu một cửa",
    t270: "Ví phi tập trung",
    t271: "Tách tài sản nóng và lạnh, Token 40000+ an toàn tiện lợi",
    t272: "Tài sản tiền điện tử",
    t273: "Hơn 40.000 tài sản tiền điện tử hỗ trợ nhiều tài sản khác nhau để giao dịch trên DEX.",
    t274: "Công nghệ mã hóa đa dạng",
    t275: "Lưu trữ tiền điện tử một cách an toàn và kiểm soát tài sản của riêng bạn.",
    t276: "Chế độ tăng nhiều lần",
    t277: "Stake, khai thác, DeFi, trò chơi chuỗi.",
    t278: "Tự quản lý tài sản, khớp các giao dịch ví ngang hàng",
    t279: "An toàn không có tai nạn và thực hiện hợp đồng thông minh thuần túy",
    t280: "Biểu đồ K-line phi tập trung gốc, lợi thế bản địa",
    t281: "Lựa chọn của bạn cũng giống của họ",
    t282: "Sự tin tưởng và lựa chọn của hơn 1.000 công ty hàng đầu",
    t283: "ví cắm",
    t284: "Hướng dẫn cài đặt plug-in",
    t285: "Công cụ quản lý tài sản kỹ thuật số blockchain hàng đầu thế giới",
    t286: "Thực thi hợp đồng thông minh thuần túy",
    t287: "Tải xuống ngay",
    t288: "Lối vào sinh thái DApp",
    t289: "Khám phá DeFi, GameFi, v.v. và nhanh chóng chơi với nền kinh tế DApp",
    t290: "Hãy bắt đầu! Nhấp vào đây để gửi đề xuất hoặc phản hồi",
    t291: "Xem thêm",
    t292: "Loại mã thông báo",
    t293: "BeingDex, nền tảng giao dịch quản lý tài sản một cửa được điều khiển bằng nhiều chuỗi<br>an toàn, hiệu quả và chi phí thấp",
    t294: "Cầu nối chuỗi BeingDex",
    t295: "Tiếng Việt",
    t296: "Chưa mở",
    t297: "vận hành",
    t298: "ví",
    t299: "Hoán đổi",
    t300: "Dapp",
    t301: "Blog"
  }
}